-- Generated by LuaSTG Editor Sharp
-- Mod name: 
_author = "LuaSTG User"
_mod_version = 4096
_allow_practice = true
_allow_sc_practice =true
-- archive space: void_resource/
_LoadImageFromFile('image:'..'void_bg_0','void_resource/void_bg_0.png',true,0,0,false,0)
_LoadImageFromFile('image:'..'void_bg_pole1','void_resource/void_bg_pole1.png',true,0,0,false,0)
_LoadImageFromFile('image:'..'void_bg_pole2','void_resource/void_bg_pole2.png',true,0,0,false,0)
_LoadImageFromFile('image:'..'void_bg_sun','void_resource/void_bg_sun.png',true,0,0,false,0)
_LoadImageFromFile('image:'..'void_bg_wind','void_resource/void_bg_wind.png',true,0,0,false,0)
_LoadImageFromFile('image:'..'void_new_sc','void_resource/void_new_sc.png',true,0,0,false,0)
_LoadImageFromFile('image:'..'void_sc0','void_resource/void_sc0.png',true,0,0,false,0)
_LoadImageFromFile('image:'..'void_new_censord','void_resource/void_new_censord.png',true,0,0,false,0)
_editor_class["void_sc0"]=Class(_object)
_editor_class["void_sc0"].init=function(self,_x,_y)
    self.x,self.y=_x,_y
    self.img="leaf"
    self.layer=LAYER_TOP+5
    self.group=GROUP_GHOST
    self.hide=true
    self.bound=true
    self.navi=false
    self.hp=10
    self.maxhp=10
    self.colli=false
    self._servants={}
    self._blend,self._a,self._r,self._g,self._b='',255,255,255,255
    lasttask=task.New(self,function()
        last=New(_editor_class["void_sc1"],0, 0)
        last=New(_editor_class["void_sc"],30, -10)
        last=New(_editor_class["void_sc_c"],-80,120)
        _del(self,false)
    end)
end
_editor_class["void_sc"]=Class(_object)
_editor_class["void_sc"].init=function(self,_x,_y)
    self.x,self.y=_x,_y
    self.img="image:void_new_sc"
    self.layer=LAYER_TOP
    self.group=GROUP_GHOST
    self.hide=false
    self.bound=true
    self.navi=false
    self.hp=10
    self.maxhp=10
    self.colli=false
    self._servants={}
    self._blend,self._a,self._r,self._g,self._b='',255,255,255,255
    self.vscale,self.hscale=0.25/1.5, 0.25/1.5
    _object.set_color(self,"",0,255,255,255)
    lasttask=task.New(self,function()
        do
            local _beg_sc1=0 local sc1=_beg_sc1 local _end_sc1=255 local _d_sc1=(_end_sc1-_beg_sc1)/(10-1)
            for _=1,10 do
                task._Wait(1)
                _object.set_color(self,"",sc1,255,255,255)
                sc1=sc1+_d_sc1
            end
        end
        task._Wait(100)
        do
            local _beg_sc1=255 local sc1=_beg_sc1 local _end_sc1=0 local _d_sc1=(_end_sc1-_beg_sc1)/(10-1)
            for _=1,10 do
                task._Wait(1)
                _object.set_color(self,"",sc1,255,255,255)
                sc1=sc1+_d_sc1
            end
        end
        _del(self,false)
    end)
    lasttask=task.New(self,function()
        for _=1,120 do
            task._Wait(1)
            self.y=self.y-0.1
        end
    end)
end
_editor_class["void_sc1"]=Class(_object)
_editor_class["void_sc1"].init=function(self,_x,_y)
    self.x,self.y=_x,_y
    self.img="image:void_sc0"
    self.layer=LAYER_TOP-1
    self.group=GROUP_GHOST
    self.hide=false
    self.bound=true
    self.navi=false
    self.hp=10
    self.maxhp=10
    self.colli=false
    self._servants={}
    self._blend,self._a,self._r,self._g,self._b='',255,255,255,255
    self.vscale,self.hscale=2, 2
    _object.set_color(self,"",0,255,255,255)
    lasttask=task.New(self,function()
        do
            local _beg_sc1=0 local sc1=_beg_sc1 local _end_sc1=255 local _d_sc1=(_end_sc1-_beg_sc1)/(10-1)
            for _=1,10 do
                task._Wait(1)
                _object.set_color(self,"",sc1,255,255,255)
                sc1=sc1+_d_sc1
            end
        end
        task._Wait(100)
        do
            local _beg_sc1=255 local sc1=_beg_sc1 local _end_sc1=0 local _d_sc1=(_end_sc1-_beg_sc1)/(10-1)
            for _=1,10 do
                task._Wait(1)
                _object.set_color(self,"",sc1,255,255,255)
                sc1=sc1+_d_sc1
            end
        end
        _del(self,false)
    end)
    lasttask=task.New(self,function()
        for _=1,120 do
            task._Wait(1)
            self.y=self.y+0.1
        end
    end)
end
_editor_class["void_sc_c"]=Class(_object)
_editor_class["void_sc_c"].init=function(self,_x,_y)
    self.x,self.y=_x,_y
    self.img="image:void_new_censord"
    self.layer=LAYER_TOP+5
    self.group=GROUP_GHOST
    self.hide=false
    self.bound=true
    self.navi=false
    self.hp=10
    self.maxhp=10
    self.colli=false
    self._servants={}
    self._blend,self._a,self._r,self._g,self._b='',255,255,255,255
    _object.set_color(self,"",0,255,255,255)
    lasttask=task.New(self,function()
        do
            local _beg_sc1=0 local sc1=_beg_sc1 local _end_sc1=255 local _d_sc1=(_end_sc1-_beg_sc1)/(10-1)
            for _=1,10 do
                task._Wait(1)
                _object.set_color(self,"",sc1,255,255,255)
                sc1=sc1+_d_sc1
            end
        end
        task._Wait(100)
        do
            local _beg_sc1=255 local sc1=_beg_sc1 local _end_sc1=0 local _d_sc1=(_end_sc1-_beg_sc1)/(10-1)
            for _=1,10 do
                task._Wait(1)
                _object.set_color(self,"",sc1,255,255,255)
                sc1=sc1+_d_sc1
            end
        end
        _del(self,false)
    end)
    lasttask=task.New(self,function()
        do local iy,_d_iy=(self.y),(-0.1) for _=1,120 do
            task._Wait(1)
            self.y = iy+ran:Int(-10, 10)/30
            self.x = -80+ran:Int(-15, 15)/30
        iy=iy+_d_iy end end
    end)
end
MusicRecord('bgm:'..'void_stg_bgm6','void_resource/void_stg_bgm6.ogg',126.032,114.002)
Include'void_resource/void_charge.lua'
local function VOID_RAN(n)
    local result = {}
    for i = 1,n do
    	result[i] = i
    end
    local index
    local temp
    for j = n,1,-1 do
    	index = ran:Int(1,j)
    	temp = result[index]
    	result[index] = result[j]
    	result[j] = temp
    end
    return result
end
local function VOID_HSV(H,S,V)
    local H=H%360
    local C = V*S
    local X= C*(1-abs((H/60)%2-1))
    local m = V-C
    local R,G,B
    if H<=60 then
        R,G,B = C,X,0
    elseif H<=120 then
        R,G,B = X,C,0
    elseif H<=180 then
        R,G,B = 0,C,X
    elseif H<=240 then
        R,G,B = 0,X,C
    elseif H<=300 then
        R,G,B = X,0,C
    elseif H<=360 then
        R,G,B = C,0,X
    else
        return
    end
    R,G,B = 255*(R+m),255*(G+m),255*(B+m)
    return R,G,B
end
local function VOID_ELLI(ra, rb, a1, a2, x, y)
    x, y = x or 0, y or 0
    local x0 = x + ra * cos(a1) * cos(a2) - rb * sin(a1) * sin(a2)
    local y0 = y + ra * cos(a1) * sin(a2) + rb * sin(a1) * cos(a2)
    return x0, y0
end
_editor_class["void_预警"]=Class(_object)
_editor_class["void_预警"].init=function(self,_x,_y,x,y,r,g,b)
    self.x,self.y=_x,_y
    self.img="white"
    self.layer=LAYER_PLAYER+5
    self.group=GROUP_GHOST
    self.hide=false
    self.bound=true
    self.navi=false
    self.hp=10
    self.maxhp=10
    self.colli=false
    self._servants={}
    self._blend,self._a,self._r,self._g,self._b='',255,255,255,255
    self.bound = false
    self.timer = 11
    self.a, self.b = 0, 32 or x    --方框的长与宽
    self.aa = 32 or y
    self.r = 0    --感叹号初始缩放
    self.h = 0    --上边框宽度
    self.al = 192    --感叹号透明度
    self.rr = r
    self.gg = g
    self.bb = b
    lasttask=task.New(self,function()
        lasttask=task.New(self,function()
            do
                local _beg_ih=0 local ih=_beg_ih local _end_ih=1 local _w_ih=0 local _d_w_ih=1/(10-1)
                for _=1,10 do
                    task._Wait(1)
                    self.h = ih
                    _w_ih=_w_ih+_d_w_ih ih=(_beg_ih-_end_ih)*(_w_ih-1)^2+_end_ih
                end
            end
        end)
        do
            local _beg_ia=0 local ia=_beg_ia local _end_ia=self.aa local _w_ia=0 local _d_w_ia=1/(15-1)
            local _beg_ir=0 local ir=_beg_ir local _end_ir=1 local _w_ir=0 local _d_w_ir=1/(15-1)
            local _beg_ih=0 local ih=_beg_ih local _end_ih=1 local _w_ih=0 local _d_w_ih=1/(15-1)
            for _=1,15 do
                task._Wait(1)
                self.a, self.r, self.h = ia, ir, ih
                _w_ia=_w_ia+_d_w_ia ia=(_beg_ia-_end_ia)*(_w_ia-1)^2+_end_ia
                _w_ir=_w_ir+_d_w_ir ir=(_beg_ir-_end_ir)*(_w_ir-1)^2+_end_ir
                _w_ih=_w_ih+_d_w_ih ih=(_beg_ih-_end_ih)*(_w_ih-1)^2+_end_ih
            end
        end
        task._Wait(30)
        do
            local _beg_ia=self.aa local ia=_beg_ia local _end_ia=0 local _w_ia=0 local _d_w_ia=1/(15-1)
            local _beg_ir=1 local ir=_beg_ir local _end_ir=0 local _w_ir=0 local _d_w_ir=1/(15-1)
            local _beg_ih=1 local ih=_beg_ih local _end_ih=0 local _w_ih=0 local _d_w_ih=1/(15-1)
            for _=1,15 do
                task._Wait(1)
                self.a, self.r, self.h = ia, ir, ih
                _w_ia=_w_ia+_d_w_ia ia=(_beg_ia-_end_ia)*(_w_ia-1)^2+_end_ia
                _w_ir=_w_ir+_d_w_ir ir=(_beg_ir-_end_ir)*(_w_ir-1)^2+_end_ir
                _w_ih=_w_ih+_d_w_ih ih=(_beg_ih-_end_ih)*(_w_ih-1)^2+_end_ih
            end
        end
        _del(self,false)
    end)
end
_editor_class["void_预警"].render=function(self)
    SetImageState(self.img,"mul+add",Color(216,self.rr,self.gg,self.bb))
    Render4V(self.img,self.x-self.b-4,self.y+self.a+4*self.h,0.5
                     ,self.x+self.b+4,self.y+self.a+4*self.h,0.5
                     ,self.x+self.b,self.y+self.a,0.5
                     ,self.x-self.b,self.y+self.a,0.5)
    Render4V(self.img,self.x-self.b-4,self.y+self.a+4*self.h,0.5
                     ,self.x-self.b,self.y+self.a,0.5
                     ,self.x-self.b,self.y-self.a,0.5
                     ,self.x-self.b-4,self.y-self.a-4*self.h,0.5)
    Render4V(self.img,self.x-self.b,self.y-self.a,0.5
                     ,self.x+self.b,self.y-self.a,0.5
                     ,self.x+self.b+4,self.y-self.a-4*self.h,0.5
                     ,self.x-self.b-4,self.y-self.a-4*self.h,0.5)
    Render4V(self.img,self.x+self.b,self.y+self.a,0.5
                     ,self.x+self.b+4,self.y+self.a+4*self.h,0.5
                     ,self.x+self.b+4,self.y-self.a-4*self.h,0.5
                     ,self.x+self.b,self.y-self.a,0.5)
    SetImageState(self.img,"mul+add",Color(64,self.rr,self.gg,self.bb))
    Render4V(self.img,self.x-self.b,self.y+self.a,0.5
                     ,self.x+self.b,self.y+self.a,0.5
                     ,self.x+self.b,self.y-self.a,0.5
                     ,self.x-self.b,self.y-self.a,0.5)
    SetImageState(self.img,"mul+add",Color(self.al,self.rr,self.gg,self.bb))
    Render4V(self.img,self.b*(-15/33)+self.x,self.a*(25/33)*self.r+self.y,0.5
                     ,self.b*(15/33)+self.x,self.a*(25/33)*self.r+self.y,0.5
                     ,self.b*(10/33)+self.x,self.a*(-7/33)*self.r+self.y,0.5
                     ,self.b*(-10/33)+self.x,self.a*(-7/33)*self.r+self.y,0.5)
    Render4V(self.img,self.b*(-10/33)+self.x,self.a*(-17/33)*self.r+self.y,0.5
                     ,self.b*(10/33)+self.x,self.a*(-17/33)*self.r+self.y,0.5
                     ,self.b*(10/33)+self.x,self.a*(-27/33)*self.r+self.y,0.5
                     ,self.b*(-10/33)+self.x,self.a*(-27/33)*self.r+self.y,0.5)
    SetImageState(self.img,"",Color(255,255,255,255))
end
_editor_class["void_云2"]=Class(_object)
_editor_class["void_云2"].init=function(self,_x,_y,r,g,b,t)
    self.x,self.y=_x,_y
    self.img="white"
    self.layer=LAYER_ENEMY_BULLET_EF+5
    self.group=GROUP_INDES
    self.hide=false
    self.bound=true
    self.navi=false
    self.hp=10
    self.maxhp=10
    self.colli=false
    self._servants={}
    self._blend,self._a,self._r,self._g,self._b='',255,255,255,255
    self.temp = ran:Float(2.5, 3.5)*4
    self.vscale, self.hscale = self.temp, self.temp
    self.rot = ran:Int(0, 359)
    self.omiga = ran:Float(0.2, 0.5)*ran:Sign()
    self.al = ran:Int(16, 64)*2
    _object.set_color(self,"",0,r,g,b)
    lasttask=task.New(self,function()
        do
            local _beg_ial=0 local ial=_beg_ial local _end_ial=self.al local _d_ial=(_end_ial-_beg_ial)/(30-1)
            for _=1,30 do
                _object.set_color(self,"",ial,r,g,b)
                task._Wait(1)
                ial=ial+_d_ial
            end
        end
        task._Wait(t)
        do
            local _beg_ial=self.al local ial=_beg_ial local _end_ial=0 local _d_ial=(_end_ial-_beg_ial)/(30-1)
            for _=1,30 do
                _object.set_color(self,"",ial,r,g,b)
                task._Wait(1)
                ial=ial+_d_ial
            end
        end
        _del(self,false)
    end)
end
_editor_tasks["void_scale"]=function(h1,v1,h2,v2,mode,t)
    return function()
        local self=task.GetSelf()
        if mode == 1 then
            do
                local _beg_iv=v1 local iv=_beg_iv local _end_iv=v2 local _d_iv=(_end_iv-_beg_iv)/(t-1)
                local _beg_ih=h1 local ih=_beg_ih local _end_ih=h2 local _d_ih=(_end_ih-_beg_ih)/(t-1)
                for _=1,t do
                    self.vscale, self.hscale = iv, ih
                    task._Wait(1)
                    iv=iv+_d_iv
                    ih=ih+_d_ih
                end
            end
        else
            if mode == 2 then
                do
                    local _beg_iv=v1 local iv=_beg_iv local _end_iv=v2 local _w_iv=0  local _d_w_iv=1/(t-1)
                    local _beg_ih=h1 local ih=_beg_ih local _end_ih=h2 local _w_ih=0  local _d_w_ih=1/(t-1)
                    for _=1,t do
                        self.vscale, self.hscale = iv, ih
                        task._Wait(1)
                        _w_iv=_w_iv+_d_w_iv iv=(_end_iv-_beg_iv)*_w_iv^2+_beg_iv
                        _w_ih=_w_ih+_d_w_ih ih=(_end_ih-_beg_ih)*_w_ih^2+_beg_ih
                    end
                end
            else
                if mode == 3 then
                    do
                        local _beg_iv=v1 local iv=_beg_iv local _end_iv=v2 local _w_iv=0 local _d_w_iv=1/(t-1)
                        local _beg_ih=h1 local ih=_beg_ih local _end_ih=h2 local _w_ih=0 local _d_w_ih=1/(t-1)
                        for _=1,t do
                            self.vscale, self.hscale = iv, ih
                            task._Wait(1)
                            _w_iv=_w_iv+_d_w_iv iv=(_beg_iv-_end_iv)*(_w_iv-1)^2+_end_iv
                            _w_ih=_w_ih+_d_w_ih ih=(_beg_ih-_end_ih)*(_w_ih-1)^2+_end_ih
                        end
                    end
                else
                    do
                        local _beg_iv=v1 local iv=_beg_iv local _end_iv=v2 local _w_iv=0 local _d_w_iv=1/(t-1)
                        local _beg_ih=h1 local ih=_beg_ih local _end_ih=h2 local _w_ih=0 local _d_w_ih=1/(t-1)
                        for _=1,t do
                            self.vscale, self.hscale = iv, ih
                            task._Wait(1)
                            _w_iv=_w_iv+_d_w_iv if _w_iv<0.5 then iv=2*(_end_iv-_beg_iv)*_w_iv^2+_beg_iv else iv=(_end_iv-_beg_iv)*(-2*_w_iv^2+4*_w_iv-1)+_beg_iv end
                            _w_ih=_w_ih+_d_w_ih if _w_ih<0.5 then ih=2*(_end_ih-_beg_ih)*_w_ih^2+_beg_ih else ih=(_end_ih-_beg_ih)*(-2*_w_ih^2+4*_w_ih-1)+_beg_ih end
                        end
                    end
                end
            end
        end
    end
end
_editor_class["144_void_non1_1"]=Class(_object)
_editor_class["144_void_non1_1"].init=function(self,_x,_y,w,c,r1,n2,t,n)
    self.x,self.y=_x,_y
    self.img="leaf"
    self.layer=LAYER_ENEMY_BULLET
    self.group=GROUP_INDES
    self.hide=true
    self.bound=false
    self.navi=false
    self.hp=10
    self.maxhp=10
    self.colli=true
    self._servants={}
    self._blend,self._a,self._r,self._g,self._b='',255,255,255,255
    self.r1 = r1
    self.omiga = w
    SetV2(self,ran:Float(0.9, 1.1),90,false,false)
    _set_g(self,0.012)
    lasttask=task.New(self,function()
        do
            local iy=-r1 local _n_iy=(-r1)+(r1)
            local s=-1 local _n_s=(-1)+(1)
            for _=1,2 do
                do
                    local _beg_ix=-r1*s local ix=_beg_ix local _end_ix=r1*s local _d_ix=(_end_ix-_beg_ix)/(n)
                    for _=1,n do
                        last=New(_editor_class["144_void_non1_2"],self.x+ix,self.y+iy,ix, iy, n2, t, c)
                        _connect(self,last,0,true)
                        ix=ix+_d_ix
                    end
                end
                iy=-(iy)+_n_iy
                s=-(s)+_n_s
            end
        end
        do
            local ix=-r1 local _n_ix=(-r1)+(r1)
            local s=1 local _n_s=(1)+(-1)
            for _=1,2 do
                do
                    local _beg_iy=-r1*s local iy=_beg_iy local _end_iy=r1*s local _d_iy=(_end_iy-_beg_iy)/(n)
                    for _=1,n do
                        last=New(_editor_class["144_void_non1_2"],self.x+ix,self.y+iy,ix, iy, n2, t, c)
                        _connect(self,last,0,true)
                        iy=iy+_d_iy
                    end
                end
                ix=-(ix)+_n_ix
                s=-(s)+_n_s
            end
        end
    end)
end
_editor_class["144_void_non1_1"].frame=function(self)
    self.class.base.frame(self)
    if self.y < -255-self.r1*1.42 then
        _del(self,true)
    else
    end
end
_editor_class["144_void_non1_2"]=Class(bullet)
_editor_class["144_void_non1_2"].init=function(self,_x,_y,x,y,n,t,c)
bullet.init(self,ball_mid,c,false,true)
self.x,self.y=_x,_y
    self.bound = false
    lasttask=task.New(self,function()
        do
            local _beg_ix=x local ix=_beg_ix local _end_ix=x*n local _w_ix=0 local _d_w_ix=1/(t-1)
            local _beg_iy=y local iy=_beg_iy local _end_iy=y*n local _w_iy=0 local _d_w_iy=1/(t-1)
            for _=1,t do
                _set_rel_pos(self,ix,iy,0,true)
                task._Wait(1)
                _w_ix=_w_ix+_d_w_ix ix=(_beg_ix-_end_ix)*(_w_ix-1)^2+_end_ix
                _w_iy=_w_iy+_d_w_iy iy=(_beg_iy-_end_iy)*(_w_iy-1)^2+_end_iy
            end
        end
        do
            for _=1,_infinite do
                _set_rel_pos(self,x*n,y*n,0,true)
                task._Wait(1)
            end
        end
    end)
end
_editor_class["144_void_north_1"]=Class(_object)
_editor_class["144_void_north_1"].init=function(self,_x,_y,a,l,n)
    self.x,self.y=_x,_y
    self.img="leaf"
    self.layer=LAYER_ENEMY_BULLET
    self.group=GROUP_INDES
    self.hide=true
    self.bound=false
    self.navi=false
    self.hp=10
    self.maxhp=10
    self.colli=false
    self._servants={}
    self._blend,self._a,self._r,self._g,self._b='',255,255,255,255
    self.rot = a
    lasttask=task.New(self,function()
        local list = {}
        local lw = {8,4,4,4}
        do
            local s=1 local _n_s=(1)+(-1)
            local i=1 local _d_i=(1)
            for _=1,2 do
                last=New(_editor_class["144_void_north_2"],self.x,self.y,s, n, l)
                _connect(self,last,0,true)
                list[i] = last
                s=-(s)+_n_s
                i=i+_d_i
            end
        end
        task._Wait(1)
        last=New(_editor_class["144_void_north_3"],self.x,self.y,list[1], list[2], lw[n%5+1])
        task._Wait(240)
        _del(self,true)
    end)
end
_editor_class["144_void_north_2"]=Class(bullet)
_editor_class["144_void_north_2"].init=function(self,_x,_y,s,n,l)
bullet.init(self,ball_mid,COLOR_CYAN,false,false)
self.x,self.y=_x,_y
    self.class = self.logclass
    self.layer = LAYER_ENEMY_BULLET - self.imgclass.size * 0.001 + self._index * 0.00001
    self.bound = false
    self.colli = false
    do
        local __terminated = false
        local __terminateCount = 0
        local _0 = 0
        local _1 = 255
        local _2 = 255
        local _3 = 255
        task.New(self, function()
            local self = task.GetSelf()
            task.Wait(0)
            local i = 0
            local offset = 0
            local curr, ibeg, ky, kx
            local prev = 0
            local target = offset
            curr = 0
            ibeg = i
            target = 0 + offset
            kx = target - ibeg
            ky = curr - prev
            while i < target do
                _0 = prev + ky * (i - ibeg) / kx
                i = i + 1
                task.Wait()
            end
            _0 = curr
            prev = curr
            curr = 255
            ibeg = i
            target = 90 + offset
            kx = target - ibeg
            ky = curr - prev
            while i < target do
                _0 = prev + ky * (i - ibeg) / kx
                i = i + 1
                task.Wait()
            end
            _0 = curr
            prev = curr
            self.colli = true
            offset = target
            __terminateCount = __terminateCount + 1
        end)
        task.New(self, function()
            local self = task.GetSelf()
            task.Wait(0)
            local i = 0
            local offset = 0
            local curr, ibeg, ky, kx
            local prev = 255
            local target = offset
            curr = 255
            ibeg = i
            target = 0 + offset
            kx = target - ibeg
            ky = curr - prev
            while i < target do
                _1 = prev + ky * (i - ibeg) / kx
                i = i + 1
                task.Wait()
            end
            _1 = curr
            prev = curr
            offset = target
            __terminateCount = __terminateCount + 1
        end)
        task.New(self, function()
            local self = task.GetSelf()
            task.Wait(0)
            local i = 0
            local offset = 0
            local curr, ibeg, ky, kx
            local prev = 255
            local target = offset
            curr = 255
            ibeg = i
            target = 0 + offset
            kx = target - ibeg
            ky = curr - prev
            while i < target do
                _2 = prev + ky * (i - ibeg) / kx
                i = i + 1
                task.Wait()
            end
            _2 = curr
            prev = curr
            offset = target
            __terminateCount = __terminateCount + 1
        end)
        task.New(self, function()
            local self = task.GetSelf()
            task.Wait(0)
            local i = 0
            local offset = 0
            local curr, ibeg, ky, kx
            local prev = 255
            local target = offset
            curr = 255
            ibeg = i
            target = 0 + offset
            kx = target - ibeg
            ky = curr - prev
            while i < target do
                _3 = prev + ky * (i - ibeg) / kx
                i = i + 1
                task.Wait()
            end
            _3 = curr
            prev = curr
            offset = target
            __terminateCount = __terminateCount + 1
        end)
        task.New(self, function()
            local self = task.GetSelf()
            for _ = 1, _infinite do
                _object.set_color(self, "", _0, _1, _2, _3)
                if __terminated or __terminateCount >= 4 then break end
                task.Wait()
            end
        end)
    end
    if n == 0 then
        ChangeBulletImage(self,ball_big,COLOR_CYAN)
    else
    end
    lasttask=task.New(self,function()
        _set_rel_pos(self,-abs(l),0,0,true)
        if s == 1 then
            do
                local _beg_ix=-l*s local ix=_beg_ix local _end_ix=l*s local _w_ix=0 local _d_w_ix=1/(90-1)
                for _=1,90 do
                    task._Wait(1)
                    _set_rel_pos(self,ix,0,0,true)
                    _w_ix=_w_ix+_d_w_ix ix=(_beg_ix-_end_ix)*(_w_ix-1)^2+_end_ix
                end
            end
            task._Wait(90)
            _del(self,true)
        else
            task._Wait(90)
            lasttask=task.New(self,function()
                if n ~= 0 then
                    do
                        local i=ran:Int(1,6) local _d_i=(1)
                        for _=1,30 do
                            do
                                local i = i
                                do
                                    last=New(_straight,ball_small,COLOR_BLUE,self.x+ran:Float(-3,3),self.y+ran:Float(-3,3),0,0,false,0,true,true,0,false,0.01,self.rot+ran:Float(-5,5),3,false)
                                    do
                                        local self = last
                                        if i % 6 ~= 0 then
                                            lasttask=task.New(self,function()
                                                task._Wait(30)
                                                self.colli = false
                                                do
                                                    local __terminated = false
                                                    local __terminateCount = 0
                                                    local _0 = 255
                                                    local _1 = 255
                                                    local _2 = 255
                                                    local _3 = 255
                                                    task.New(self, function()
                                                        local self = task.GetSelf()
                                                        task.Wait(0)
                                                        local i = 0
                                                        local offset = 0
                                                        local curr, ibeg, ky, kx
                                                        local prev = 255
                                                        local target = offset
                                                        curr = 255
                                                        ibeg = i
                                                        target = 0 + offset
                                                        kx = target - ibeg
                                                        ky = curr - prev
                                                        while i < target do
                                                            _0 = prev + ky * (i - ibeg) / kx
                                                            i = i + 1
                                                            task.Wait()
                                                        end
                                                        _0 = curr
                                                        prev = curr
                                                        curr = 0
                                                        ibeg = i
                                                        target = 15 + offset
                                                        kx = target - ibeg
                                                        ky = curr - prev
                                                        while i < target do
                                                            _0 = prev + ky * (i - ibeg) / kx
                                                            i = i + 1
                                                            task.Wait()
                                                        end
                                                        _0 = curr
                                                        prev = curr
                                                        _del(self,false)
                                                        offset = target
                                                        __terminateCount = __terminateCount + 1
                                                    end)
                                                    task.New(self, function()
                                                        local self = task.GetSelf()
                                                        task.Wait(0)
                                                        local i = 0
                                                        local offset = 0
                                                        local curr, ibeg, ky, kx
                                                        local prev = 255
                                                        local target = offset
                                                        curr = 255
                                                        ibeg = i
                                                        target = 0 + offset
                                                        kx = target - ibeg
                                                        ky = curr - prev
                                                        while i < target do
                                                            _1 = prev + ky * (i - ibeg) / kx
                                                            i = i + 1
                                                            task.Wait()
                                                        end
                                                        _1 = curr
                                                        prev = curr
                                                        offset = target
                                                        __terminateCount = __terminateCount + 1
                                                    end)
                                                    task.New(self, function()
                                                        local self = task.GetSelf()
                                                        task.Wait(0)
                                                        local i = 0
                                                        local offset = 0
                                                        local curr, ibeg, ky, kx
                                                        local prev = 255
                                                        local target = offset
                                                        curr = 255
                                                        ibeg = i
                                                        target = 0 + offset
                                                        kx = target - ibeg
                                                        ky = curr - prev
                                                        while i < target do
                                                            _2 = prev + ky * (i - ibeg) / kx
                                                            i = i + 1
                                                            task.Wait()
                                                        end
                                                        _2 = curr
                                                        prev = curr
                                                        offset = target
                                                        __terminateCount = __terminateCount + 1
                                                    end)
                                                    task.New(self, function()
                                                        local self = task.GetSelf()
                                                        task.Wait(0)
                                                        local i = 0
                                                        local offset = 0
                                                        local curr, ibeg, ky, kx
                                                        local prev = 255
                                                        local target = offset
                                                        curr = 255
                                                        ibeg = i
                                                        target = 0 + offset
                                                        kx = target - ibeg
                                                        ky = curr - prev
                                                        while i < target do
                                                            _3 = prev + ky * (i - ibeg) / kx
                                                            i = i + 1
                                                            task.Wait()
                                                        end
                                                        _3 = curr
                                                        prev = curr
                                                        offset = target
                                                        __terminateCount = __terminateCount + 1
                                                    end)
                                                    task.New(self, function()
                                                        local self = task.GetSelf()
                                                        for _ = 1, _infinite do
                                                            _object.set_color(self, "", _0, _1, _2, _3)
                                                            if __terminated or __terminateCount >= 4 then break end
                                                            task.Wait()
                                                        end
                                                    end)
                                                end
                                            end)
                                        else
                                        end
                                    end
                                end
                            end
                            task._Wait(3)
                            i=i+_d_i
                        end
                    end
                else
                end
            end)
            do
                local _beg_ix=l*s local ix=_beg_ix local _end_ix=-l*s local _w_ix=0  local _d_w_ix=1/(90-1)
                for _=1,90 do
                    task._Wait(1)
                    _set_rel_pos(self,ix,0,0,true)
                    _w_ix=_w_ix+_d_w_ix ix=(_end_ix-_beg_ix)*_w_ix^2+_beg_ix
                end
            end
            if n == 0 then
                PlaySound("tan00",0.1,self.x/256,false)
                do
                    local ia=ran:Float(0, 360) local _d_ia=(360/24)
                    local i=1 local _n_i=(1)+(-1)
                    for _=1,24 do
                        do
                            local ia,i = ia,i
                            do
                                last=New(_straight,ball_mid,COLOR_BLUE,self.x,self.y,0,0,false,0,true,true,0,false,0,0,0,false)
                                do
                                    local self = last
                                    do
                                        local __terminated = false
                                        local __terminateCount = 0
                                        local _0 = 3
                                        local _1 = ia
                                        task.New(self, function()
                                            local self = task.GetSelf()
                                            task.Wait(0)
                                            local i = 0
                                            local offset = 0
                                            local curr, ibeg, ky, kx
                                            local prev = 3
                                            local target = offset
                                            curr = 3
                                            ibeg = i
                                            target = 0 + offset
                                            kx = target - ibeg
                                            ky = curr - prev
                                            while i < target do
                                                _0 = prev + ky * (i - ibeg) / kx
                                                i = i + 1
                                                task.Wait()
                                            end
                                            _0 = curr
                                            prev = curr
                                            curr = 0.5
                                            ibeg = i
                                            target = 15 + offset
                                            kx = target - ibeg
                                            ky = curr - prev
                                            while i < target do
                                                _0 = prev + ky * (i - ibeg) / kx
                                                i = i + 1
                                                task.Wait()
                                            end
                                            _0 = curr
                                            prev = curr
                                            curr = 1.5
                                            ibeg = i
                                            target = 120 + offset
                                            kx = target - ibeg
                                            ky = curr - prev
                                            while i < target do
                                                _0 = prev + ky * (i - ibeg) / kx
                                                i = i + 1
                                                task.Wait()
                                            end
                                            _0 = curr
                                            prev = curr
                                            offset = target
                                            __terminateCount = __terminateCount + 1
                                        end)
                                        task.New(self, function()
                                            local self = task.GetSelf()
                                            task.Wait(0)
                                            local i = 0
                                            local offset = 0
                                            local curr, ibeg, ky, kx
                                            local prev = ia
                                            local target = offset
                                            curr = ia
                                            ibeg = i
                                            target = 0 + offset
                                            kx = target - ibeg
                                            ky = curr - prev
                                            while i < target do
                                                _1 = prev + ky * (i - ibeg) / kx
                                                i = i + 1
                                                task.Wait()
                                            end
                                            _1 = curr
                                            prev = curr
                                            offset = target
                                            __terminateCount = __terminateCount + 1
                                        end)
                                        task.New(self, function()
                                            local self = task.GetSelf()
                                            for _ = 1, _infinite do
                                                SetV2(self, _0, _1, false, false)
                                                if __terminated or __terminateCount >= 2 then break end
                                                task.Wait()
                                            end
                                        end)
                                    end
                                    if i == 1 then
                                        lasttask=task.New(self,function()
                                            task._Wait(15)
                                            self.colli = false
                                            do
                                                local __terminated = false
                                                local __terminateCount = 0
                                                local _0 = 255
                                                local _1 = 255
                                                local _2 = 255
                                                local _3 = 255
                                                task.New(self, function()
                                                    local self = task.GetSelf()
                                                    task.Wait(0)
                                                    local i = 0
                                                    local offset = 0
                                                    local curr, ibeg, ky, kx
                                                    local prev = 255
                                                    local target = offset
                                                    curr = 255
                                                    ibeg = i
                                                    target = 0 + offset
                                                    kx = target - ibeg
                                                    ky = curr - prev
                                                    while i < target do
                                                        _0 = prev + ky * (i - ibeg) / kx
                                                        i = i + 1
                                                        task.Wait()
                                                    end
                                                    _0 = curr
                                                    prev = curr
                                                    curr = 0
                                                    ibeg = i
                                                    target = 15 + offset
                                                    kx = target - ibeg
                                                    ky = curr - prev
                                                    while i < target do
                                                        _0 = prev + ky * (i - ibeg) / kx
                                                        i = i + 1
                                                        task.Wait()
                                                    end
                                                    _0 = curr
                                                    prev = curr
                                                    _del(self,false)
                                                    offset = target
                                                    __terminateCount = __terminateCount + 1
                                                end)
                                                task.New(self, function()
                                                    local self = task.GetSelf()
                                                    task.Wait(0)
                                                    local i = 0
                                                    local offset = 0
                                                    local curr, ibeg, ky, kx
                                                    local prev = 255
                                                    local target = offset
                                                    curr = 255
                                                    ibeg = i
                                                    target = 0 + offset
                                                    kx = target - ibeg
                                                    ky = curr - prev
                                                    while i < target do
                                                        _1 = prev + ky * (i - ibeg) / kx
                                                        i = i + 1
                                                        task.Wait()
                                                    end
                                                    _1 = curr
                                                    prev = curr
                                                    offset = target
                                                    __terminateCount = __terminateCount + 1
                                                end)
                                                task.New(self, function()
                                                    local self = task.GetSelf()
                                                    task.Wait(0)
                                                    local i = 0
                                                    local offset = 0
                                                    local curr, ibeg, ky, kx
                                                    local prev = 255
                                                    local target = offset
                                                    curr = 255
                                                    ibeg = i
                                                    target = 0 + offset
                                                    kx = target - ibeg
                                                    ky = curr - prev
                                                    while i < target do
                                                        _2 = prev + ky * (i - ibeg) / kx
                                                        i = i + 1
                                                        task.Wait()
                                                    end
                                                    _2 = curr
                                                    prev = curr
                                                    offset = target
                                                    __terminateCount = __terminateCount + 1
                                                end)
                                                task.New(self, function()
                                                    local self = task.GetSelf()
                                                    task.Wait(0)
                                                    local i = 0
                                                    local offset = 0
                                                    local curr, ibeg, ky, kx
                                                    local prev = 255
                                                    local target = offset
                                                    curr = 255
                                                    ibeg = i
                                                    target = 0 + offset
                                                    kx = target - ibeg
                                                    ky = curr - prev
                                                    while i < target do
                                                        _3 = prev + ky * (i - ibeg) / kx
                                                        i = i + 1
                                                        task.Wait()
                                                    end
                                                    _3 = curr
                                                    prev = curr
                                                    offset = target
                                                    __terminateCount = __terminateCount + 1
                                                end)
                                                task.New(self, function()
                                                    local self = task.GetSelf()
                                                    for _ = 1, _infinite do
                                                        _object.set_color(self, "", _0, _1, _2, _3)
                                                        if __terminated or __terminateCount >= 4 then break end
                                                        task.Wait()
                                                    end
                                                end)
                                            end
                                        end)
                                    else
                                    end
                                end
                            end
                        end
                        ia=ia+_d_ia
                        i=-(i)+_n_i
                    end
                end
            else
            end
            _del(self,true)
        end
    end)
end
_editor_class["144_void_north_3"]=Class(laser)
_editor_class["144_void_north_3"].init=function(self,_x,_y,obj1,obj2,w)
    laser.init(self,COLOR_CYAN,_x,_y,0,1,1,1,w,0,0)
    
    self.bound = false
    lasttask=task.New(self,function()
        laser._TurnOn(self,120,false,true)
    end)
    lasttask=task.New(self,function()
        for _=1,_infinite do
            if IsValid(obj1) and IsValid(obj2) then
                self.rot = Angle(obj1,obj2)
                self.x, self.y = obj1.x,obj1.y
                self.l2 = Dist(obj1,obj2)
            else
                _del(self,true)
            end
            task._Wait(1)
        end
    end)
end
_editor_class["144_void_non2_1"]=Class(_object)
_editor_class["144_void_non2_1"].init=function(self,_x,_y,w,c,r1,n2,t,n,a,r,aw)
    self.x,self.y=_x,_y
    self.img="leaf"
    self.layer=LAYER_ENEMY_BULLET
    self.group=GROUP_INDES
    self.hide=true
    self.bound=false
    self.navi=false
    self.hp=10
    self.maxhp=10
    self.colli=true
    self._servants={}
    self._blend,self._a,self._r,self._g,self._b='',255,255,255,255
    self.omiga = w
    lasttask=task.New(self,function()
        do
            local _beg_ir=0 local ir=_beg_ir local _end_ir=r local _w_ir=0 local _d_w_ir=1/(300-1)
            local ia=a local _d_ia=(aw)
            for _=1,300 do
                self.x = ir*cos(ia)
                self.y = ir*sin(ia)+100
                task._Wait(1)
                _w_ir=_w_ir+_d_w_ir if _w_ir<0.5 then ir=2*(_end_ir-_beg_ir)*_w_ir^2+_beg_ir else ir=(_end_ir-_beg_ir)*(-2*_w_ir^2+4*_w_ir-1)+_beg_ir end
                ia=ia+_d_ia
            end
        end
        do
            local ia=a+aw*301 local _d_ia=(aw)
            for _=1,_infinite do
                self.x = r*cos(ia)
                self.y = r*sin(ia)+100
                task._Wait(1)
                ia=ia+_d_ia
            end
        end
    end)
    lasttask=task.New(self,function()
        do
            local iy=-r1 local _n_iy=(-r1)+(r1)
            local s=-1 local _n_s=(-1)+(1)
            for _=1,2 do
                do
                    local _beg_ix=-r1*s local ix=_beg_ix local _end_ix=r1*s local _d_ix=(_end_ix-_beg_ix)/(n)
                    for _=1,n do
                        last=New(_editor_class["144_void_non2_2"],self.x+ix,self.y+iy,ix, iy, n2, t, c)
                        _connect(self,last,0,true)
                        ix=ix+_d_ix
                    end
                end
                iy=-(iy)+_n_iy
                s=-(s)+_n_s
            end
        end
        do
            local ix=-r1 local _n_ix=(-r1)+(r1)
            local s=1 local _n_s=(1)+(-1)
            for _=1,2 do
                do
                    local _beg_iy=-r1*s local iy=_beg_iy local _end_iy=r1*s local _d_iy=(_end_iy-_beg_iy)/(n)
                    for _=1,n do
                        last=New(_editor_class["144_void_non2_2"],self.x+ix,self.y+iy,ix, iy, n2, t, c)
                        _connect(self,last,0,true)
                        iy=iy+_d_iy
                    end
                end
                ix=-(ix)+_n_ix
                s=-(s)+_n_s
            end
        end
    end)
end
_editor_class["144_void_non2_2"]=Class(bullet)
_editor_class["144_void_non2_2"].init=function(self,_x,_y,x,y,n,t,c)
bullet.init(self,ball_mid,c,false,false)
self.x,self.y=_x,_y
    self.bound = false
    lasttask=task.New(self,function()
        do
            local _beg_ix=x local ix=_beg_ix local _end_ix=x*n local _w_ix=0 local _d_w_ix=1/(t-1)
            local _beg_iy=y local iy=_beg_iy local _end_iy=y*n local _w_iy=0 local _d_w_iy=1/(t-1)
            for _=1,t do
                _set_rel_pos(self,ix,iy,0,true)
                task._Wait(1)
                _w_ix=_w_ix+_d_w_ix ix=(_beg_ix-_end_ix)*(_w_ix-1)^2+_end_ix
                _w_iy=_w_iy+_d_w_iy iy=(_beg_iy-_end_iy)*(_w_iy-1)^2+_end_iy
            end
        end
        do
            for _=1,_infinite do
                _set_rel_pos(self,x*n,y*n,0,true)
                task._Wait(1)
            end
        end
    end)
end
_editor_class["144_void_non2_3"]=Class(_object)
_editor_class["144_void_non2_3"].init=function(self,_x,_y,w,c,r1,n2,t,n,a,aw)
    self.x,self.y=_x,_y
    self.img="leaf"
    self.layer=LAYER_ENEMY_BULLET
    self.group=GROUP_INDES
    self.hide=true
    self.bound=true
    self.navi=false
    self.hp=10
    self.maxhp=10
    self.colli=true
    self._servants={}
    self._blend,self._a,self._r,self._g,self._b='',255,255,255,255
    self.omiga = w
    do
        local __terminated = false
        local __terminateCount = 0
        local _0 = 3
        local _1 = a
        task.New(self, function()
            local self = task.GetSelf()
            task.Wait(0)
            local i = 0
            local offset = 0
            local curr, ibeg, ky, kx
            local prev = 3
            local target = offset
            curr = 3
            ibeg = i
            target = 0 + offset
            kx = target - ibeg
            ky = curr - prev
            while i < target do
                _0 = prev + ky * (i - ibeg) / kx
                i = i + 1
                task.Wait()
            end
            _0 = curr
            prev = curr
            curr = 2.2
            ibeg = i
            target = 150 + offset
            kx = target - ibeg
            ky = curr - prev
            while i < target do
                _0 = prev + ky * (i - ibeg) / kx
                i = i + 1
                task.Wait()
            end
            _0 = curr
            prev = curr
            offset = target
            __terminateCount = __terminateCount + 1
        end)
        task.New(self, function()
            local self = task.GetSelf()
            task.Wait(0)
            local i = 0
            local offset = 0
            local curr, ibeg, ky, kx
            local prev = a
            local target = offset
            curr = a
            ibeg = i
            target = 0 + offset
            kx = target - ibeg
            ky = curr - prev
            while i < target do
                _1 = prev + ky * (i - ibeg) / kx
                i = i + 1
                task.Wait()
            end
            _1 = curr
            prev = curr
            curr = a+aw
            ibeg = i
            target = 150 + offset
            kx = target - ibeg
            ky = curr - prev
            while i < target do
                _1 = prev + ky * (i - ibeg) / kx
                i = i + 1
                task.Wait()
            end
            _1 = curr
            prev = curr
            offset = target
            __terminateCount = __terminateCount + 1
        end)
        task.New(self, function()
            local self = task.GetSelf()
            for _ = 1, _infinite do
                SetV2(self, _0, _1, false, false)
                if __terminated or __terminateCount >= 2 then break end
                task.Wait()
            end
        end)
    end
    lasttask=task.New(self,function()
        do
            local iy=-r1 local _n_iy=(-r1)+(r1)
            local s=-1 local _n_s=(-1)+(1)
            for _=1,2 do
                do
                    local _beg_ix=-r1*s local ix=_beg_ix local _end_ix=r1*s local _d_ix=(_end_ix-_beg_ix)/(n)
                    for _=1,n do
                        last=New(_editor_class["144_void_non1_2"],self.x+ix,self.y+iy,ix, iy, n2, t, c)
                        _connect(self,last,0,true)
                        ix=ix+_d_ix
                    end
                end
                iy=-(iy)+_n_iy
                s=-(s)+_n_s
            end
        end
        do
            local ix=-r1 local _n_ix=(-r1)+(r1)
            local s=1 local _n_s=(1)+(-1)
            for _=1,2 do
                do
                    local _beg_iy=-r1*s local iy=_beg_iy local _end_iy=r1*s local _d_iy=(_end_iy-_beg_iy)/(n)
                    for _=1,n do
                        last=New(_editor_class["144_void_non1_2"],self.x+ix,self.y+iy,ix, iy, n2, t, c)
                        _connect(self,last,0,true)
                        iy=iy+_d_iy
                    end
                end
                ix=-(ix)+_n_ix
                s=-(s)+_n_s
            end
        end
    end)
end
_editor_class["144_void_lev_1"]=Class(bullet)
_editor_class["144_void_lev_1"].init=function(self,_x,_y,vy,a,w,h)
bullet.init(self,ellipse,COLOR_DEEP_GRAY,false,true)
self.x,self.y=_x,_y
    self.navi = true
    self.bound = false
    local r0,g0,b0 = VOID_HSV(h,0.75,0.75)
    _object.set_color(self,"add+alpha",255,r0,g0,b0)
    lasttask=task.New(self,function()
        do
            local _h_ix=(a-(-a))/2 local _t_ix=(a+(-a))/2 local ix=_h_ix*sin(0)+_t_ix local _w_ix=0 local _d_w_ix=w
            local iy=250 local _d_iy=(vy)
            for _=1,_infinite do
                self.x, self.y = ix, iy
                task._Wait(1)
                _w_ix=_w_ix+_d_w_ix ix=_h_ix*sin(_w_ix)+_t_ix
                iy=iy+_d_iy
            end
        end
    end)
end
_editor_class["144_void_lev_1"].frame=function(self)
    self.class.base.frame(self)
    if self.y < -255 then
        _del(self,false)
    else
    end
end
_editor_class["144_void_lev_2"]=Class(bullet)
_editor_class["144_void_lev_2"].init=function(self,_x,_y)
bullet.init(self,ball_light,COLOR_BLUE,true,false)
self.x,self.y=_x,_y
    self.class = self.logclass
    self.layer = LAYER_ENEMY_BULLET - self.imgclass.size * 0.001 + self._index * 0.00001
    self.a,self.b = self.a*2, self.b*2
    lasttask=task.New(self,_editor_tasks["void_scale"](0, 0, 2, 2, 4, 60))
    self.omiga = 0.5
    lasttask=task.New(self,function()
        for _=1,_infinite do
            _set_rel_pos(self,0,0,self.rot,false)
            task._Wait(1)
        end
    end)
end
_editor_class["void_bg"]=Class(_spellcard_background)
_editor_class["void_bg"].init=function(self)
    _spellcard_background.init(self)
    _spellcard_background.AddLayer(self,"image:void_bg_pole2",false,0,0,0,0,0,0,"",1,1,
        function(self)
            self.task={}
            self.r, self.g, self.b = 31,29,42
        end,
        function(self)
            task.Do(self)
            self.y = -55+15*sin(self.timer/3)
        end,
        function(self)
        end
    )
    _spellcard_background.AddLayer(self,"image:void_bg_sun",false,0,150,0,0,0,0,"",0.4,0.4,
        function(self)
            self.task={}
        end,
        function(self)
            task.Do(self)
        end,
        function(self)
        end
    )
    _spellcard_background.AddLayer(self,"img_void",false,0,0,0,0,0,0,"",1,1,
        function(self)
            self.task={}
            --[[ 纹理名称（注：LoadImage节点格式化后的图像资源名称存在同名纹理，可直接使用）]]
                self.tex = "image:void_bg_wind"
            
            --[[ 兼容 LuaSTG Sub 新版本]]
                -- LuaSTG Sub 在 0.18.11-beta 修改了 lstg.SetTextureSamplerState 的写法，不再支持老写法
                -- 说实话 lstg.SetTextureSamplerState 在 LuaSTG Ex Plus 后期版本才开始出现
                -- 当时还不是公开 API，且是实验性的 API，还没稳定下来，修的还是全局状态非常危险
                -- 被改掉真的是太好了，我直接开香槟，好似
                
                ---@param major number
                ---@param minor number
                ---@param patch number
                ---@return number
                local function make_version(major, minor, patch)
                    return (major * 1000 * 1000) + (minor * 1000) + (patch)
                end
                
                ---@return boolean
                local function is_LuaSTG_Sub()
                    if lstg.GetVersionName then
                        if string.find(lstg.GetVersionName(), "LuaSTG Sub") then
                            return true
                        end
                    end
                    return false
                end
                
                ---@return boolean
                local function is_API_lstg_SetTextureSamplerState_new_behavior()
                    if is_LuaSTG_Sub() then
                        local major, minor, patch = lstg.GetVersionNumber()
                        if make_version(major, minor, patch) >= make_version(0, 18, 11) then
                            return true
                        end
                    end
                    return false
                end
                
                if is_API_lstg_SetTextureSamplerState_new_behavior() then
                    self.is_API_lstg_SetTextureSamplerState_old_behavior = false
                    lstg.SetTextureSamplerState(self.tex, "linear+wrap")
                else
                    self.is_API_lstg_SetTextureSamplerState_old_behavior = true
                end
            
            --[[ 中心点坐标]]
                self.x = 0
                self.y = 150
            
            --[[ 图层角度与自旋速度]]
                self.angle = 90
                self.omega = 0
            
            --[[ 计时器初始值]]
                self.timer = 0
            
            --[[ 扩散速度（负数为缩回）]]
                self.speed = 0.6
            
            --[[ 渲染范围（radiusMax为上限，radiusMin为下限，请保证radiusMax大于等于radiusMin）]]
                self.radiusMin = 0
                self.radiusMax = 1800
            
            --[[ 每一层的厚度与图像数（即每一层是几次重复拼接出来的）]]
                self.radius = 512
                self.duplicate = 1
            
            --[[ 分割数（整体为n边形，越大性能消耗越高，但效果越好）]]
                self.n = 256
            
            --[[ 分割模式（1为纵向分割，2为水平分割）]]
                self.mode = 2
            
            --[[ 图层颜色]]
                self.color = Color(255, 255, 255, 255)
            
            --[[ 图层混合模式]]
                self.blend = ""
            
        end,
        function(self)
            task.Do(self)
            self.angle = self.angle + self.omega
        end,
        function(self)
            --[[ 兼容 LuaSTG Ex Plus 后期版本以及 LuaSTG Sub 老版本]]
                if self.is_API_lstg_SetTextureSamplerState_old_behavior then
                    SetTextureSamplerState("address", "wrap")
                end
            
            --[[ 主要渲染代码]]
                local w, h = GetTextureSize(self.tex)
                local a, ta = self.angle, 0
                local da = 360 / self.n
                if self.mode == 1 then
                    local tda = w * self.duplicate / self.n
                    local t = -self.radiusMin / self.radius * h + self.timer * self.speed
                    local tv = -(self.radiusMax - self.radiusMin) / self.radius * h
                    for _ = 1, self.n do
                        RenderTexture(self.tex, self.blend, { self.x + self.radiusMin * cos(a), self.y + self.radiusMin * sin(a), 0.5, ta, t, self.color },
                                { self.x + self.radiusMin * cos(a + da), self.y + self.radiusMin * sin(a + da), 0.5, ta + tda, t, self.color },
                                { self.x + self.radiusMax * cos(a + da), self.y + self.radiusMax * sin(a + da), 0.5, ta + tda, t + tv, self.color },
                                { self.x + self.radiusMax * cos(a), self.y + self.radiusMax * sin(a), 0.5, ta, t + tv, self.color })
                        a = a + da
                        ta = ta + tda
                    end
                else
                    local tda = -h * self.duplicate / self.n
                    local t = -self.radiusMin / self.radius * w + self.timer * self.speed
                    local tv = -(self.radiusMax - self.radiusMin) / self.radius * w
                    for _ = 1, self.n do
                        RenderTexture(self.tex, self.blend, { self.x + self.radiusMin * cos(a), self.y + self.radiusMin * sin(a), 0.5, t, ta, self.color },
                                { self.x + self.radiusMin * cos(a + da), self.y + self.radiusMin * sin(a + da), 0.5, t, ta + tda, self.color },
                                { self.x + self.radiusMax * cos(a + da), self.y + self.radiusMax * sin(a + da), 0.5, t + tv, ta + tda, self.color },
                                { self.x + self.radiusMax * cos(a), self.y + self.radiusMax * sin(a), 0.5, t + tv, ta, self.color })
                        a = a + da
                        ta = ta + tda
                    end
                end
            
            --[[ 兼容 LuaSTG Ex Plus 后期版本以及 LuaSTG Sub 老版本]]
                if self.is_API_lstg_SetTextureSamplerState_old_behavior then
                    SetTextureSamplerState("address", "clamp")
                end
            
        end
    )
    _spellcard_background.AddLayer(self,"image:void_bg_pole1",false,0,0,0,0,0,0,"",1,1,
        function(self)
            self.task={}
            self.r, self.g, self.b = 20, 12, 36
        end,
        function(self)
            task.Do(self)
            self.y = -50+10*sin(self.timer/4)
        end,
        function(self)
        end
    )
    _spellcard_background.AddLayer(self,"image:void_bg_pole1",false,0,0,180,0,0,0,"",1,1,
        function(self)
            self.task={}
            self.r, self.g, self.b = 20, 12, 36
        end,
        function(self)
            task.Do(self)
            self.y = 170+10*sin(self.timer/4)
        end,
        function(self)
        end
    )
    _spellcard_background.AddLayer(self,"image:void_bg_0",false,0,0,0,0,0,0,"",1,1,
        function(self)
            self.task={}
            self.r, self.g, self.b = 82, 55, 150
        end,
        function(self)
            task.Do(self)
        end,
        function(self)
        end
    )
end
_editor_class["void_boss"]=Class(boss)
_editor_class["void_boss"].cards={}
_editor_class["void_boss"].name="\\/0!|)"
_editor_class["void_boss"].bgm="bgm:void_stg_bgm6"
_editor_class["void_boss"]._bg=gensokyosora_background
_editor_class["void_boss"].difficulty="All"
_editor_class["void_boss"].init=function(self,cards)
boss.init(self,0,384,_editor_class["void_boss"].name,cards,New(_editor_class["void_bg"]),_editor_class["void_boss"].difficulty)
    boss.show_aura(self,false)
    self._wisys = BossWalkImageSystem(self)
    self._wisys:SetImage("void_resource/void_walkimg.png",4,12,{7,9,9,12},{6,6,6},9,12,12)
    self._wisys:SetFloat(function(ani) 
            return 0, 3 * sin(ani * 4) 
    end)
    self.no_killeff = true
end
_tmp_sc=boss.dialog.New(true)
function _tmp_sc:init()
    lstg.player.dialog=false
    _dialog_can_skip=true
    self.dialog_displayer=New(dialog_displayer)
    lasttask=task.New(self,function()
        task._Wait(45)
    end)
end
table.insert(_editor_class["void_boss"].cards,_tmp_sc)
--[[ 1]]

_tmp_sc=boss.card.New("",2,5,30,750,{0,0,0},false)
function _tmp_sc:before()
    task.MoveTo(0,100,45,MOVE_DECEL)
    self.colli = true
    New(void_charge, self,"","",200,75)
    ui.lstg_weekly.SetFlag(true, false, false)
    ui.lstg_weekly.SetEditor("杠零")
end
function _tmp_sc:init()
    lasttask=task.New(self,function()
        task._Wait(60)
        local s0 = ran:Sign()
        do
            local s=s0 local _n_s=(s0)+(-s0)
            for _=1,_infinite do
                PlaySound("boon01",0.1,self.x/256,false)
                do
                    local c=COLOR_BLUE local _n_c=(COLOR_BLUE)+(COLOR_CYAN)
                    local s2=s local _n_s2=(s)+(-s)
                    for _=1,30 do
                        PlaySound("tan02",0.1,self.x/256,false)
                        last=New(_editor_class["144_void_non1_1"],-200+ran:Int(0,5)*80+ran:Float(0,80),ran:Float(120,160),ran:Float(0.1, 0.3)*s2, c, (80+40*s2)*ran:Float(0.98,1.02), ran:Float(0.7,0.9), (300+240*s2)*ran:Float(0.99,1.01), ran:Int(3,5))
                        task._Wait(15)
                        c=-(c)+_n_c
                        s2=-(s2)+_n_s2
                    end
                end
                task.MoveToPlayer(30,-32,32,120,144,16,32,8,16,MOVE_DECEL,MOVE_X_TOWARDS_PLAYER)
                s=-(s)+_n_s
            end
        end
    end)
end
function _tmp_sc:beforedel()
end
function _tmp_sc:del()
end
function _tmp_sc:after()
    player.collect_line = player.collect_line - 450
    if self.is_final then
        self.colli = false
        task.MoveTo(-220, 200,90,MOVE_ACCEL)
        player.collect_line = player.collect_line + 450
        _del(self,true)
    else
        task._Wait(60)
        player.collect_line = player.collect_line + 450
    end
end
_tmp_sc.perform=false
table.insert(_editor_class["void_boss"].cards,_tmp_sc)

--[[ 2]]

_tmp_sc=boss.card.New("海妖「北海巨舰的战歌」",5,10,45,700,{0,0,66},false)
function _tmp_sc:before()
    task.MoveTo(0,120,45,MOVE_DECEL)
    self.colli = true
    New(void_charge, self,"","",200,75)
    task._Wait(60)
    self._bosssys:setHPBar(0)
    ui.lstg_weekly.SetFlag(false, true, false)
    ui.lstg_weekly.SetEditor("杠零")
end
function _tmp_sc:init()
    lasttask=task.New(self,function()
        last=New(_editor_class["void_sc0"],0,0)
        task._Wait(120)
        task._Wait(1)
        PlaySound("ch02",0.1,self.x/256,false)
        boss.cast(self,90)
        New(void_charge, self)
        task._Wait(59)
        local s0 = ran:Sign()
        local x0 = {-60,200}
        local y0 = {250,-230}
        local a0 = {200,-20}
        task.MoveTo(-130*s0,ran:Float(120,140),60,MOVE_DECEL)
        do
            local s=s0 local _n_s=(s0)+(-s0)
            local ia=a0[1.5-0.5*s0] local _n_ia=(a0[1.5-0.5*s0])+(a0[1.5+0.5*s0])
            for _=1,_infinite do
                PlaySound("boon01",0.1,self.x/256,false)
                lasttask=task.New(self,function()
                    do
                        local ia0=ran:Float(0, 360) local _d_ia0=(GOLD/8*s)
                        for _=1,15 do
                            do
                                local _beg_ia2=ia0 local ia2=_beg_ia2 local _end_ia2=ia0+360 local _d_ia2=(_end_ia2-_beg_ia2)/(8)
                                for _=1,8 do
                                    do
                                        local ia2 = ia2
                                        do
                                            last=New(_straight,ball_huge,COLOR_BLUE,self.x,self.y,0,0,false,3*s,false,true,0,false,0,0,0,false)
                                            do
                                                local self = last
                                                _set_g(self,0.03)
                                                local vx0,vy0 = VOID_ELLI(6,3,ia2,ia,0,0)
                                                self.vx,self.vy=vx0,vy0
                                            end
                                        end
                                    end
                                    ia2=ia2+_d_ia2
                                end
                            end
                            task._Wait(12)
                            ia0=ia0+_d_ia0
                        end
                    end
                end)
                do
                    local n=ran:Int(1,4) local _d_n=(1)
                    local _beg_ix=x0[1]*s local ix=_beg_ix local _end_ix=x0[2]*s local _d_ix=(_end_ix-_beg_ix)/(30-1)
                    local _beg_iy=y0[1] local iy=_beg_iy local _end_iy=y0[2] local _d_iy=(_end_iy-_beg_iy)/(30-1)
                    local _h_il=(250-(150))/2 local _t_il=(250+(150))/2 local il=_h_il*sin(90)+_t_il local _w_il=90 local _d_w_il=1*360/(30-1)
                    for _=1,30 do
                        last=New(_editor_class["144_void_north_1"],ix,iy,ia, il, n%4)
                        task._Wait(6)
                        n=n+_d_n
                        ix=ix+_d_ix
                        iy=iy+_d_iy
                        _w_il=_w_il+_d_w_il il=_h_il*sin(_w_il)+_t_il
                    end
                end
                task._Wait(180)
                task._Wait(1)
                PlaySound("ch02",0.1,self.x/256,false)
                boss.cast(self,90)
                New(void_charge, self)
                task._Wait(59)
                lasttask=task.New(self,function()
                    task.MoveTo(-130*s,ran:Float(120,140),120,MOVE_DECEL)
                end)
                s=-(s)+_n_s
                ia=-(ia)+_n_ia
            end
        end
    end)
end
function _tmp_sc:beforedel()
end
function _tmp_sc:del()
end
function _tmp_sc:after()
    player.collect_line = player.collect_line - 450
    if self.is_final then
        self.colli = false
        task.MoveTo(-220, 200,90,MOVE_ACCEL)
        player.collect_line = player.collect_line + 450
        _del(self,true)
    else
        self.colli = false
        task._Wait(60)
        player.collect_line = player.collect_line + 450
        self.colli = true
    end
end
_tmp_sc.perform=false
table.insert(_editor_class["void_boss"].cards,_tmp_sc)
table.insert(_sc_table,{"void_boss","海妖「北海巨舰的战歌」",_tmp_sc,#_editor_class["void_boss"].cards,false})
--[[ 1]]

_tmp_sc=boss.card.New("",2,5,30,900,{0,0,0},false)
function _tmp_sc:before()
    task.MoveTo(0,100,45,MOVE_DECEL)
    self.colli = true
    New(void_charge, self,"","",200,75)
    ui.lstg_weekly.SetFlag(true, false, false)
    ui.lstg_weekly.SetEditor("杠零")
end
function _tmp_sc:init()
    lasttask=task.New(self,function()
        task._Wait(60)
        local s0 = ran:Sign()
        PlaySound("boon01",0.1,self.x/256,false)
        do
            local iw=-0.12 local _n_iw=(-0.12)+(0.12)
            local iaw=0.35 local _n_iaw=(0.35)+(-0.35)
            local ir=135 local _n_ir=(135)+(300)
            local ir2=60 local _n_ir2=(60)+(133)
            for _=1,2 do
                do
                    local _beg_ia=0 local ia=_beg_ia local _end_ia=360 local _d_ia=(_end_ia-_beg_ia)/(5)
                    for _=1,5 do
                        last=New(_editor_class["144_void_non2_1"],self.x,self.y,iw, COLOR_DEEP_BLUE, ir2/3, 3, 300, 6, ia, ir, iaw)
                        ia=ia+_d_ia
                    end
                end
                iw=-(iw)+_n_iw
                iaw=-(iaw)+_n_iaw
                ir=-(ir)+_n_ir
                ir2=-(ir2)+_n_ir2
            end
        end
        do
            local s=s0 local _n_s=(s0)+(-s0)
            local ia0=ran:Float(0, 360) local _d_ia0=(GOLD/10)
            for _=1,_infinite do
                do
                    local _beg_ia=ia0 local ia=_beg_ia local _end_ia=ia0+360 local _d_ia=(_end_ia-_beg_ia)/(10)
                    for _=1,10 do
                        last=New(_editor_class["144_void_non2_3"],self.x,self.y,s, COLOR_DEEP_GRAY, 30, 0.25, 100, 1, ia, 100)
                        ia=ia+_d_ia
                    end
                end
                task._Wait(20)
                s=-(s)+_n_s
                ia0=ia0+_d_ia0
            end
        end
    end)
end
function _tmp_sc:beforedel()
end
function _tmp_sc:del()
end
function _tmp_sc:after()
    player.collect_line = player.collect_line - 450
    if self.is_final then
        self.colli = false
        task.MoveTo(-220, 200,90,MOVE_ACCEL)
        player.collect_line = player.collect_line + 450
        _del(self,true)
    else
        task._Wait(60)
        player.collect_line = player.collect_line + 450
    end
end
_tmp_sc.perform=false
table.insert(_editor_class["void_boss"].cards,_tmp_sc)

--[[ 3]]

_tmp_sc=boss.card.New("再临「利维坦航线」",20,20,20,600,{0,0,66},false)
function _tmp_sc:before()
    task.MoveTo(0,120,45,MOVE_DECEL)
    self.colli = true
    New(void_charge, self,"","",200,75)
    last=New(_editor_class["144_void_lev_2"],self.x,self.y)
    _connect(self,last,0,true)
    do
        local __terminated = false
        local __terminateCount = 0
        local _0 = 255
        local _1 = 255
        local _2 = 255
        local _3 = 255
        task.New(self, function()
            local self = task.GetSelf()
            task.Wait(0)
            local i = 0
            local offset = 0
            local curr, ibeg, ky, kx
            local prev = 255
            local target = offset
            curr = 255
            ibeg = i
            target = 0 + offset
            kx = target - ibeg
            ky = curr - prev
            while i < target do
                _0 = prev + ky * (i - ibeg) / kx
                i = i + 1
                task.Wait()
            end
            _0 = curr
            prev = curr
            curr = 0
            ibeg = i
            target = 30 + offset
            kx = target - ibeg
            ky = curr - prev
            while i < target do
                _0 = prev + ky * (i - ibeg) / kx
                i = i + 1
                task.Wait()
            end
            _0 = curr
            prev = curr
            offset = target
            __terminateCount = __terminateCount + 1
        end)
        task.New(self, function()
            local self = task.GetSelf()
            task.Wait(0)
            local i = 0
            local offset = 0
            local curr, ibeg, ky, kx
            local prev = 255
            local target = offset
            curr = 255
            ibeg = i
            target = 0 + offset
            kx = target - ibeg
            ky = curr - prev
            while i < target do
                _1 = prev + ky * (i - ibeg) / kx
                i = i + 1
                task.Wait()
            end
            _1 = curr
            prev = curr
            offset = target
            __terminateCount = __terminateCount + 1
        end)
        task.New(self, function()
            local self = task.GetSelf()
            task.Wait(0)
            local i = 0
            local offset = 0
            local curr, ibeg, ky, kx
            local prev = 255
            local target = offset
            curr = 255
            ibeg = i
            target = 0 + offset
            kx = target - ibeg
            ky = curr - prev
            while i < target do
                _2 = prev + ky * (i - ibeg) / kx
                i = i + 1
                task.Wait()
            end
            _2 = curr
            prev = curr
            offset = target
            __terminateCount = __terminateCount + 1
        end)
        task.New(self, function()
            local self = task.GetSelf()
            task.Wait(0)
            local i = 0
            local offset = 0
            local curr, ibeg, ky, kx
            local prev = 255
            local target = offset
            curr = 255
            ibeg = i
            target = 0 + offset
            kx = target - ibeg
            ky = curr - prev
            while i < target do
                _3 = prev + ky * (i - ibeg) / kx
                i = i + 1
                task.Wait()
            end
            _3 = curr
            prev = curr
            offset = target
            __terminateCount = __terminateCount + 1
        end)
        task.New(self, function()
            local self = task.GetSelf()
            for _ = 1, _infinite do
                _object.set_color(self, "", _0, _1, _2, _3)
                if __terminated or __terminateCount >= 4 then break end
                task.Wait()
            end
        end)
    end
    lasttask=task.New(self,_editor_tasks["void_scale"](1, 1, 0, 0, 4, 60))
    task._Wait(60)
    self._bosssys:setHPBar(0)
    ui.lstg_weekly.SetFlag(false, false, true)
    ui.lstg_weekly.SetEditor("杠零")
end
function _tmp_sc:init()
    lasttask=task.New(self,function()
        last=New(_editor_class["void_sc0"],0,0)
        task._Wait(120)
        task._Wait(1)
        PlaySound("ch02",0.1,self.x/256,false)
        boss.cast(self,90)
        New(void_charge, self)
        task._Wait(59)
        local s0 = ran:Sign()
        local v0 = {2,2,4,8}
        PlaySound("boon01",0.1,self.x/256,false)
        lasttask=task.New(self,function()
            local x1,y1,x2,y2,dx,dy
            x1, y1 = self.x, self.y
            x2, y2 = player.x, player.y
            for _=1,_infinite do
                task._Wait(1)
                dx,dy = (x2-x1)/100,(y2-y1)/100
                self.x, self.y = self.x+dx, self.y+dy
                x1, y1 = self.x, self.y
                x2, y2 = player.x, player.y
            end
        end)
        do
            local s=s0 local _n_s=(s0)+(-s0)
            local n=2 local _n_n=(2)+(3)
            local n2=3 local _n_n2=(3)+(2)
            local _h_h=(240-(180))/2 local _t_h=(240+(180))/2 local h=_h_h*sin(-90)+_t_h local _w_h=-90 local _d_w_h=3*4/3
            local _h_am=(224-(0))/2 local _t_am=(224+(0))/2 local am=_h_am*sin(90)+_t_am local _w_am=90 local _d_w_am=7*4/3
            for _=1,_infinite do
                last=New(_editor_class["144_void_lev_1"],0,254,-2/v0[n], am, s*0.75, h)
                task._Wait(4)
                last=New(_editor_class["144_void_lev_1"],0,254,-2/v0[n2], am, s*0.75, h)
                task._Wait(4)
                s=-(s)+_n_s
                n=-(n)+_n_n
                n2=-(n2)+_n_n2
                _w_h=_w_h+_d_w_h h=_h_h*sin(_w_h)+_t_h
                _w_am=_w_am+_d_w_am am=_h_am*sin(_w_am)+_t_am
            end
        end
    end)
end
function _tmp_sc:beforedel()
end
function _tmp_sc:del()
end
function _tmp_sc:after()
end
_tmp_sc.perform=false
table.insert(_editor_class["void_boss"].cards,_tmp_sc)
table.insert(_sc_table,{"void_boss","再临「利维坦航线」",_tmp_sc,#_editor_class["void_boss"].cards,false})
stage.group.AddStage(__WEEK_ID,'void@'..__WEEK_ID,{lifeleft=7,power=400,faith=50000,bomb=3},true)
stage.group.DefStageFunc('void@'..__WEEK_ID,'init',function(self)
    _init_item(self)
    difficulty=self.group.difficulty
    New(mask_fader,'open')
    if jstg then jstg.CreatePlayers() else New(_G[lstg.var.player_name]) end
    lasttask=task.New(self,function()
        LoadMusic('spellcard','THlib\\music\\spellcard.ogg',75,0xc36e80/44100/4)
        New(gensokyosora_background)
        task._Wait(45)
        LoadMusicRecord("bgm:void_stg_bgm6")
        _play_music("bgm:void_stg_bgm6")
        local _boss_wait=true
        local _ref=New(_editor_class["void_boss"],_editor_class["void_boss"].cards)
        last=_ref
        if _boss_wait then while IsValid(_ref) do task.Wait() end end
        task._Wait(120)
    end)
    ui.lstg_weekly.stage_init(self)
    task.New(self,function()
        while coroutine.status(self.task[1])~='dead' do task.Wait() end
        stage.group.FinishReplay()
        New(mask_fader,'close')
        task.New(self,function()
            local _,bgm=EnumRes('bgm')
            for i=1,30 do
                for _,v in pairs(bgm) do
                    if GetMusicState(v)=='playing' then
                        SetBGMVolume(v,1-i/30)
                    end
                end
                task.Wait()
            end
        end)
        task.Wait(30)
        stage.group.FinishStage()
    end)
end)
