-- Generated by LuaSTG Editor Sharp
-- Mod name: 
_author = "LuaSTG User"
_mod_version = 4096
_allow_practice = true
_allow_sc_practice =true
MusicRecord('bgm:'..'Maths_PeopleAfar','Maths_PeopleAfar.ogg',4113028/44100,(4113028-450130)/44100)
_LoadImageFromFile('image:'..'Maths_wall','Maths_wall.png',true,0,0,false,0)
_editor_class["maths"]=Class(_spellcard_background)
_editor_class["maths"].init=function(self)
    _spellcard_background.init(self)
    _spellcard_background.AddLayer(self,"image:Maths_wall",true,0,0,0,0,0.5,0,"",1,1,
        function(self)
            self.task={}
        end,
        function(self)
            task.Do(self)
        end,
        function(self)
        end
    )
end
_editor_class["Maths_Nonsp_Servant"]=Class(bullet)
_editor_class["Maths_Nonsp_Servant"].init=function(self,_x,_y,a)
bullet.init(self,ball_small,COLOR_GOLDEN_YELLOW,false,true)
self.x,self.y=_x,_y
    lasttask=task.New(self,function()
        do
            local _beg_r=15 local r=_beg_r local _end_r=90 local _w_r=0 local _d_w_r=1/(180-1)
            local fa=a local _d_fa=(1)
            for _=1,180 do
                _set_rel_pos(self,r*cos(fa),r*sin(fa),fa+105,false)
                task._Wait(1)
                _w_r=_w_r+_d_w_r r=(_beg_r-_end_r)*(_w_r-1)^2+_end_r
                fa=fa+_d_fa
            end
        end
        do
            local fa=a+180 local _d_fa=(1)
            for _=1,_infinite do
                _set_rel_pos(self,90*cos(fa),90*sin(fa),fa+105,false)
                task._Wait(1)
                fa=fa+_d_fa
            end
        end
    end)
end
_editor_class["Maths_Nonsp_Master"]=Class(_object)
_editor_class["Maths_Nonsp_Master"].init=function(self,_x,_y,a)
    self.x,self.y=_x,_y
    self.img="img_void"
    self.layer=LAYER_ENEMY_BULLET
    self.group=GROUP_GHOST
    self.hide=false
    self.bound=false
    self.navi=false
    self.hp=10
    self.maxhp=10
    self.colli=true
    self._servants={}
    self._blend,self._a,self._r,self._g,self._b='',255,255,255,255
    SetV2(self,1,a,true,false)
    do local f,_d_f=(ran:Int(0,360)),(30) for _=1,12 do
        do local t,_d_t=(f),(1.5) for _=1,6 do
            last=New(_editor_class["Maths_Nonsp_Servant"],self.x+15*cos(t),self.y+15*sin(t),t)
            _connect(self,last,0,true)
        t=t+_d_t end end
    f=f+_d_f end end
end
_editor_class["Maths_Nonsp_Master"].frame=function(self)
    self.class.base.frame(self)
    if self.y > 336 then
        _del(self,true)
    end
    if self.y < -336 then
        _del(self,true)
    end
    if self.x > 192+112 then
        _del(self,true)
    end
    if self.x < -192-112 then
        _del(self,true)
    end
end
_editor_class["Maths_sp1_sword"]=Class(laser_bent)
_editor_class["Maths_sp1_sword"].init=function(self,_x,_y,a,p,lsc,vsc)
    laser_bent.init(self,COLOR_DEEP_PURPLE,_x,_y,32,8,4,0)
    self.navi=true
    lasttask=task.New(self,function()
        if p==1 then
            do
                local _beg_ra=a+60 local ra=_beg_ra local _end_ra=a+300 local _w_ra=0 local _d_w_ra=1/(90-1)
                for _=1,90 do
                    local x=(lsc*cos(ra))
                    local y=(vsc*sin(ra))
                    self.x=_boss.x+x*cos(a)-y*sin(a)
                    self.y=_boss.y+x*sin(a)+y*cos(a)
                    task._Wait(1)
                    _w_ra=_w_ra+_d_w_ra ra=(_beg_ra-_end_ra)*(_w_ra-1)^2+_end_ra
                end
            end
        else
            do
                local _beg_ra=a-60 local ra=_beg_ra local _end_ra=a-300 local _w_ra=0 local _d_w_ra=1/(90-1)
                for _=1,90 do
                    local x=(lsc*cos(ra))
                    local y=(vsc*sin(ra))
                    self.x=_boss.x+x*cos(a)-y*sin(a)
                    self.y=_boss.y+x*sin(a)+y*cos(a)
                    task._Wait(1)
                    _w_ra=_w_ra+_d_w_ra if _w_ra<0.5 then ra=2*(_end_ra-_beg_ra)*_w_ra^2+_beg_ra else ra=(_end_ra-_beg_ra)*(-2*_w_ra^2+4*_w_ra-1)+_beg_ra end
                end
            end
        end
        _del(self,true)
    end)
    lasttask=task.New(self,function()
        task._Wait(4)
        do local t,_d_t=(120),(-8) for _=1,_infinite do
            local fa=(self.rot-90)
            do local ft,_d_ft=(t),(-1) for _=1,4 do
                last=New(_straight,grain_b,COLOR_PURPLE,self.x,self.y,0,fa,false,0,true,true,ft,false,1/60,fa,2,false)
                task._Wait(1)
            ft=ft+_d_ft end end
            local fa=(self.rot-90)
            do local ft,_d_ft=(t-4),(-1) for _=1,4 do
                last=New(_straight,grain_b,COLOR_PURPLE,self.x,self.y,0,fa,false,0,true,true,ft,false,1/120,fa,2,false)
                task._Wait(1)
            ft=ft+_d_ft end end
        t=t+_d_t end end
    end)
end
_editor_class["Maths_sp1_gun"]=Class(bullet)
_editor_class["Maths_sp1_gun"].init=function(self,_x,_y)
bullet.init(self,ball_huge_dark,COLOR_GRAY,true,true)
self.x,self.y=_x,_y
    _object.set_color(self,"mul+add",255,255,255,255)
    self.vscale=0.25
    self.b=0.25*self.b
    self.class=self.logclass
    SetV2(self,8,Angle(self,_boss),true,false)
    lasttask=task.New(self,function()
        task._Wait(35)
        local s_tab={grain_a,ball_small,mildew}
        PlaySound("tan02",0.1,self.x/256,false)
        do local v,_d_v=(2.5),(-1/30) for _=1,60 do
            last=New(_straight,s_tab[ran:Int(1,3)],COLOR_GRAY,self.x,self.y,v,self.rot+ran:Int(160,200),false,0,true,true,0,false,0,0,0,false)
        v=v+_d_v end end
    end)
end
_editor_class["Maths_sp1_gun"].frame=function(self)
    self.class.base.frame(self)
    if Dist(self,_boss)<6 then
        do local v,_d_v=(1.5),(-1/100) for _=1,100 do
            last=New(_straight,kite,COLOR_RED,self.x,self.y,v,ran:Int(0,360),false,0,true,true,0,false,1/100,270,2,false)
            last.navi=true
        v=v+_d_v end end
        PlaySound("enep02",0.1,self.x/256,false)
        _boss.hp=_boss.hp-600
        _del(self,true)
    end
end
_editor_class["Maths"]=Class(boss)
_editor_class["Maths"].cards={}
_editor_class["Maths"].name="整理立绘ing"
_editor_class["Maths"].bgm="bgm:Maths_PeopleAfar"
_editor_class["Maths"]._bg=le03_5_background
_editor_class["Maths"].difficulty="All"
_editor_class["Maths"].init=function(self,cards)
boss.init(self,240,384,_editor_class["Maths"].name,cards,New(_editor_class["maths"]),_editor_class["Maths"].difficulty)
end
--[[ 1
]]
_tmp_sc=boss.card.New("",2,5,60,1000,{0,0,0},false)
function _tmp_sc:before()
    ui.lstg_weekly.SetFlag(true, false, false)
    ui.lstg_weekly.SetEditor("Maths")
end
function _tmp_sc:init()
    lasttask=task.New(self,function()
        task.MoveTo(0,120,60,MOVE_NORMAL)
        do local a,_d_a=(ran:Int(0,360)),(GOLD/4) for _=1,_infinite do
            task._Wait(30)
            last=New(_editor_class["Maths_Nonsp_Master"],self.x,self.y,a)
            PlaySound("option",0.1,self.x/256,false)
            task._Wait(15)
            last=New(_editor_class["Maths_Nonsp_Master"],self.x,self.y,a+180)
            PlaySound("option",0.1,self.x/256,false)
        a=a+_d_a end end
    end)
end
function _tmp_sc:beforedel()
end
function _tmp_sc:del()
end
function _tmp_sc:after()
end
_tmp_sc.perform=false
table.insert(_editor_class["Maths"].cards,_tmp_sc)

--[[ 2
]]
_tmp_sc=boss.card.New("机翻剧「我就是问题所在」",2,5,60,1400,{0,0,0},false)
function _tmp_sc:before()
    ui.lstg_weekly.SetFlag(false, true, false)
    ui.lstg_weekly.SetEditor("Maths")
end
function _tmp_sc:init()
    lasttask=task.New(self,function()
        task.MoveTo(0,120,60,MOVE_NORMAL)
        do local r,_d_r=(ran:Int(0,360)),(GOLD) for _=1,_infinite do
            do local r,_d_r,a,_d_a=(96),(24),(r),(20) for _=1,6 do
                last=New(_editor_class["Maths_sp1_sword"],self.x,self.y,a, 1, r, r/3)
                PlaySound("slash",0.1,self.x/256,false)
                task._Wait(15)
            r=r+_d_r a=a+_d_a end end
            task._Wait(30)
            local y=(ran:Int(-120,120))
            New(boss_cast_ef,y,-224,255,255,255,255,60)
            task._Wait(60)
            last=New(_editor_class["Maths_sp1_gun"],y,-256)
            PlaySound("tan00",0.1,self.x/256,false)
            task._Wait(30)
            task.MoveToPlayer(30,-96,96,112,144,16,32,2,4,MOVE_DECEL,MOVE_X_TOWARDS_PLAYER)
        r=r+_d_r end end
    end)
end
function _tmp_sc:beforedel()
end
function _tmp_sc:del()
end
function _tmp_sc:after()
end
_tmp_sc.perform=false
table.insert(_editor_class["Maths"].cards,_tmp_sc)
table.insert(_sc_table,{"Maths","机翻剧「我就是问题所在」",_tmp_sc,#_editor_class["Maths"].cards,false})
stage.group.AddStage(__WEEK_ID,'Maths@'..__WEEK_ID,{lifeleft=7,power=400,faith=50000,bomb=3},true)
stage.group.DefStageFunc('Maths@'..__WEEK_ID,'init',function(self)
    _init_item(self)
    difficulty=self.group.difficulty
    New(mask_fader,'open')
    if jstg then jstg.CreatePlayers() else New(_G[lstg.var.player_name]) end
    lasttask=task.New(self,function()
        LoadMusic('spellcard','THlib\\music\\spellcard.ogg',75,0xc36e80/44100/4)
        New(le03_5_background)
        task._Wait(60)
        LoadMusicRecord("bgm:Maths_PeopleAfar")
        _play_music("bgm:Maths_PeopleAfar")
        local _boss_wait=true
        local _ref=New(_editor_class["Maths"],_editor_class["Maths"].cards)
        last=_ref
        if _boss_wait then while IsValid(_ref) do task.Wait() end end
        task._Wait(180)
    end)
    ui.lstg_weekly.stage_init(self)
    task.New(self,function()
        while coroutine.status(self.task[1])~='dead' do task.Wait() end
        stage.group.FinishReplay()
        New(mask_fader,'close')
        task.New(self,function()
            local _,bgm=EnumRes('bgm')
            for i=1,30 do
                for _,v in pairs(bgm) do
                    if GetMusicState(v)=='playing' then
                        SetBGMVolume(v,1-i/30)
                    end
                end
                task.Wait()
            end
        end)
        task.Wait(30)
        stage.group.FinishStage()
    end)
end)
