-- Generated by LuaSTG Editor Sharp
-- Mod name: 
_author = "LuaSTG User"
_mod_version = 4096
_allow_practice = true
_allow_sc_practice =true
-- archive space: liu_10_mc/img/background/
-- archive space: liu_10_mc/img/bullet/
-- archive space: liu_10_mc/img/card/
-- archive space: liu_10_mc/img/face/
_LoadImageFromFile('image:'..'liu_10_mc_face06ct','liu_10_mc/img/face/liu_10_mc_face06ct.png',true,0,0,false,0)
-- archive space: liu_10_mc/img/stgenm/
-- archive space: liu_10_mc/script/
-- archive space: liu_10_mc/sound/bgm/
MusicRecord('bgm:'..'liu_10_mc_th12_13','liu_10_mc/sound/bgm/liu_10_mc_th12_13.ogg',0x26A9BF8/44100/4,0x23E0504/44100/4)
-- archive space: liu_10_mc/sound/se/
LoadSound('se:'..'liu_10_mc_se_ufo','liu_10_mc/sound/se/liu_10_mc_se_ufo.wav')
LoadSound('se:'..'liu_10_mc_se_ufoalert','liu_10_mc/sound/se/liu_10_mc_se_ufoalert.wav')
local liu_10_mc = {}
liu_10_mc.bullet = require("liu_10_mc.script.liu_10_mc_bullet")
liu_10_mc.effect = require("liu_10_mc.script.liu_10_mc_effect")
liu_10_mc.world = require("liu_10_mc.script.liu_10_mc_world")
liu_10_mc.stgenm = require("liu_10_mc.script.liu_10_mc_stgenm")
liu_10_mc.wisys = require("liu_10_mc.script.liu_10_mc_WalkImageSys")
local calc = require("liu_10_mc.script.liu_10_mc_math")
local func = calc.lerp
-----------------------------------------------------------------
lstg.DoFile("liu_10_mc/script/liu_10_mc_distortion.lua")
lstg.DoFile("liu_10_mc/script/liu_10_mc_screen.lua")
_editor_class["liu_10_mc_sc_ring"]=Class(_object)
_editor_class["liu_10_mc_sc_ring"].init=function(self,_x,_y,b)
    self.x,self.y=_x,_y
    self.img="img_void"
    self.layer=LAYER_BG + 2.5
    self.group=GROUP_GHOST
    self.hide=false
    self.bound=false
    self.navi=false
    self.hp=10
    self.maxhp=10
    self.colli=true
    self._servants={}
    self._blend,self._a,self._r,self._g,self._b='',255,255,255,255
    self.boss = b
end
_editor_class["liu_10_mc_sc_ring"].frame=function(self)
    local b = self.boss
    if IsValid(b) then
    else
        _del(self,false)
    end
end
_editor_class["liu_10_mc_sc_ring"].render=function(self)
    local b = self.boss
    SetViewMode"world"
    if IsValid(b) then
        local extend_rate = 1 + 8 / 60
        local alpha = min(b.sc_ring_alpha or 144, 144)
        local exr1 = -0.5
        local bold = 1
        local main_radius = 160
        local timer, rov, cut, flag = b.timer, 4, 48, 1
        local pause = ext.pause_menu
        if pause and pause.IsKilled and pause:IsKilled() then
        	pause = false
        end
        local ringx = b._sc_ring_x or b.x
        local ringy = b._sc_ring_y or b.y
        if not pause then
        	local minspeed = b._sc_ring_minspeed or 0.5
        	local ratespeed = b._sc_ring_ratespeed or 0.08
        	local speed = Dist(ringx, ringy, b.x, b.y)
        	local angle = Angle(ringx, ringy, b.x, b.y)
        	speed = min(speed, max(speed * ratespeed, minspeed))
        	ringx = ringx + speed * cos(angle)
        	ringy = ringy + speed * sin(angle)
        end
        b._sc_ring_x = ringx
        b._sc_ring_y = ringy
        if not b.__is_waiting and b.__draw_sc_ring then
        	for i = 1, 16 do
        		SetImageState('bossring1' .. i, 'mul+add', Color(alpha, 255, 255, 255))
        	end
        	if timer < 90 then
        		if b.fxr and b.fxg and b.fxb then
        			local of = 1 - timer / 180
        			for i = 1, 16 do
        				SetImageState('bossring2' .. i, 'mul+add',
        					Color(1.9 * alpha, b.fxr * of, b.fxg * of, b.fxb * of))
                    end
        		else
        			for i = 1, 16 do
        				SetImageState('bossring2' .. i, 'mul+add',
        					Color(alpha, 255, 255, 255))
        			end
        		end
        		misc.RenderRing('bossring1', ringx, ringy,
        			timer * (main_radius / 90) + main_radius * 1.5 * sin(timer * 2) + 14 + exr1 + bold,
        			timer * (main_radius / 90) + main_radius * 1.5 * sin(timer * 2) - 2 + exr1,
        			-b.ani * rov, cut, 16)
        		misc.RenderRing('bossring2', ringx, ringy,
        			90 + ((main_radius - 90) / 90) * timer + 4,
        			-main_radius + (1 - cos(timer) ^ 2) * (main_radius * 2 - 12) - bold,
        			b.ani * rov, cut, 16)--white
        	else
        		if b.fxr and b.fxg and b.fxb then
        			for i = 1, 16 do
        				SetImageState('bossring2' .. i, 'mul+add',
        					Color(1.9 * alpha, b.fxr / 2, b.fxg / 2, b.fxb / 2))
        			end
        		else
        			for i = 1, 16 do
        				SetImageState('bossring2' .. i, 'mul+add',
        					Color(alpha, 255, 255, 255))
        			end
        		end
        		local t = b.t3 * extend_rate --多给点收缩时间,符卡环最终半径不要为0
        		misc.RenderRing('bossring1', ringx, ringy,
        			(t - timer * 1.08) / (t - 90) * main_radius + 14 + exr1 + bold,
        			(t - timer * 1.08) / (t - 90) * main_radius - 2 + exr1,
        			-b.ani * rov, cut, 16)
        		misc.RenderRing('bossring2', ringx, ringy,
        			(t - timer) / (t - 90) * main_radius + 4,
        			(t - timer) / (t - 90) * main_radius - 12 - bold,
        			b.ani * rov, cut, 16)--white
        	end
        end
    else
    end
end
_editor_class["liu_10_mc_scpic"]=Class(_object)
_editor_class["liu_10_mc_scpic"].init=function(self,_x,_y)
    self.x,self.y=_x,_y
    self.img="image:liu_10_mc_face06ct"
    self.layer=LAYER_ENEMY-5
    self.group=GROUP_GHOST
    self.hide=false
    self.bound=false
    self.navi=false
    self.hp=10
    self.maxhp=10
    self.colli=true
    self._servants={}
    self._blend,self._a,self._r,self._g,self._b='',255,255,255,255
    self.x, self.y = -384, 32
    _object.set_color(self,"",255,0,0,0)
    lasttask=task.New(self,function()
        do
            local _beg_c=0 local c=_beg_c local _end_c=255 local _d_c=(_end_c-_beg_c)/(30)
            for _=1,30 do
                task._Wait(1)
                _object.set_color(self,"",255,c,c,c)
                c=c+_d_c
            end
        end
        _object.set_color(self,"",255,255,255,255)
        task._Wait(90)
        do
            local _beg_c=255 local c=_beg_c local _end_c=0 local _d_c=(_end_c-_beg_c)/(30)
            for _=1,30 do
                task._Wait(1)
                _object.set_color(self,"",255,c,c,c)
                c=c+_d_c
            end
        end
        _object.set_color(self,"",255,0,0,0)
        _del(self,false)
    end)
    lasttask=task.New(self,function()
        task.MoveTo(0, 32,30,MOVE_NORMAL)
        task.MoveTo(32, 32,90,MOVE_NORMAL)
        task.MoveTo(416, 32,30,MOVE_NORMAL)
    end)
end
_editor_tasks["liu_10_mc_movePosTime"]=function(time,mode,x,y)
    return function()
        local self=task.GetSelf()
        local _x,_y = self.x,self.y
        local d = sign(x - _x)
        self.lr = d
        for i = 1,time do
        	self.x = func(_x,x,min(i/time,1),mode)
        	self.y = func(_y,y,min(i/time,1),mode)
        	task._Wait(1)
        end
        self.x,self.y = x,y
    end
end
_editor_tasks["liu_10_mc_moveRand"]=function(time,mode,spd)
    return function()
        local self=task.GetSelf()
        local tmp = 0
        local _spd,_a = spd,math.deg(ran:Float(-PI,PI)) * -1
        if self.moveLimit then
        	local x, y = self.x, self.y
        	local p = self.moveLimit
        	for i = 1,time do
        		_spd = func(spd,0,min(i/time,1),mode)
        		x = x + _spd * cos(_a)
        		y = y + _spd * sin(_a)
        	end
        	for _ = 1, 34 do
        		_a = math.deg(ran:Float(-PI,PI)) * -1
        		x, y = 0, 0
        		for i = 1,time do
        			_spd = func(spd,0,min(i/time,1),mode)
        			x = x + _spd * cos(_a)
        			y = y + _spd * sin(_a)
        		end
        		if (x >= p[1] and x <= p[2] and y >= p[3] and y <= p[4]) then break end
        	end
        	self.x = min(max(self.x + spd * cos(_a), p[1]), p[2])
        	self.y = min(max(self.y + spd * sin(_a), p[3]), p[4])
        	for i = 1,time do
        		_spd = func(spd,0,min(i/time,1),mode)
        		task._Wait(1)
        		self.x = min(max(self.x + _spd * cos(_a), p[1]), p[2])
        		self.y = min(max(self.y + _spd * sin(_a), p[3]), p[4])
        	end
        end
    end
end
local function liu_10_mc_SetWalkIamgeState(obj, index, no_change)
    local state = obj._wisys.state_list
    obj._wisys.act_state = state[min(max(index, 1), #state)]
    obj._wisys.no_change = no_change or false
end
local function liu_10_mc_moveLimit(self,x,y,w,h)
    local _w,_h = w/2,h/2
    self.moveLimit = {x-_w,x+_w,y-_h,y+_h}
end
local function liu_10_mc_getColor(num)
    return Color(0xFF000000 + num):ARGB()
end
_editor_tasks["liu_10_mc_BossEyes"]=function()
    return function()
        local self=task.GetSelf()
        for _=1,_infinite do
            local x=(self.x - 114)
            local y=(self.y - 54)
            local a=(Angle(x, y, player))
            self.eyes[3].rx, self.eyes[3].ry = 6 * cos(a), 6 * sin(a)
            x, y = self.x + 114, self.y - 54
            a = Angle(x, y, player)
            self.eyes[4].rx, self.eyes[4].ry = 6 * cos(a), 6 * sin(a)
            x, y = self.x - 64, self.y + 80
            a = Angle(x, y, player)
            self.eyes[5].rx, self.eyes[5].ry = 6 * cos(a), 6 * sin(a)
            x, y = self.x + 64, self.y + 80
            a = Angle(x, y, player)
            self.eyes[6].rx, self.eyes[6].ry = 6 * cos(a), 6 * sin(a)
            task._Wait(1)
        end
    end
end
_editor_tasks["liu_10_mc_BossEyes2"]=function()
    return function()
        local self=task.GetSelf()
        local a1=(-90)
        local a2=(-90)
        local a3=(-90)
        local a4=(-90)
        local rx=(6 * cos(a1))
        local ry=(6 * sin(a1))
        do local i,_d_i=(3),(1) for _=1,4 do
            self.eyes[i].rx, self.eyes[i].ry = rx, ry
        i=i+_d_i end end
        task._Wait(100)
        local i=(0)
        local n=(7)
        for _=1,_infinite do
            rx, ry = 6 * cos(a1), 6 * sin(a1)
            self.eyes[3].rx, self.eyes[3].ry = rx, ry
            if (i % n) == 0 then
                lasttask=task.New(self,_editor_tasks["liu_10_mc_BossCard2_at1"](a1, self.x - 114, self.y - 54))
            else
            end
            a1 = a1 + (-1.8)
            rx, ry = 6 * cos(a2), 6 * sin(a2)
            self.eyes[4].rx, self.eyes[4].ry = rx, ry
            if (i % n) == 0 then
                lasttask=task.New(self,_editor_tasks["liu_10_mc_BossCard2_at1"](a2, self.x + 114, self.y - 54))
            else
            end
            a2 = a2 - (-1.8)
            rx, ry = 6 * cos(a3), 6 * sin(a3)
            self.eyes[5].rx, self.eyes[5].ry = rx, ry
            if (i % n) == 0 then
                lasttask=task.New(self,_editor_tasks["liu_10_mc_BossCard2_at1"](a3, self.x - 64, self.y + 80))
            else
            end
            a3 = a3 + (-1.8)
            rx, ry = 6 * cos(a4), 6 * sin(a4)
            self.eyes[6].rx, self.eyes[6].ry = rx, ry
            if (i % n) == 0 then
                lasttask=task.New(self,_editor_tasks["liu_10_mc_BossCard2_at1"](a4, self.x + 64, self.y + 80))
            else
            end
            a4 = a4 - (-1.8)
            task._Wait(1)
            i = i + 1
        end
    end
end
local function liu_10_mc_HPWait(self, hp, time)
    for _=1,time do
        if self.hp <= hp then break end
        task._Wait(1)
    end
end
_editor_tasks["liu_10_mc_Boss1_at1"]=function()
    return function()
        local self=task.GetSelf()
        local a=(ran:Float(-180, 180))
        local a2=(0)
        for _=1,3 do
            local aa=(a)
            liu_10_mc.bullet.ShotBulletMode(3, 0, _editor_class["liu_10_mc_Boss1 Bullet01"], self.x, self.y + 32, 0, 0, 0, 0, 0, 14, 1, 4.4, 1.5, aa, 0)
            aa = aa + (-2.25)
            liu_10_mc.bullet.ShotBulletMode(3, 0, _editor_class["liu_10_mc_Boss1 Bullet01"], self.x, self.y + 32, 0, 0, 0, 0, 0, 14, 1, 4.4, 1.5, aa, 0)
            aa = aa + (-2.25)
            liu_10_mc.bullet.ShotBulletMode(3, 0, _editor_class["liu_10_mc_Boss1 Bullet01"], self.x, self.y + 32, 0, 0, 0, 0, 0, 14, 1, 4.4, 1.5, aa, 0)
            aa = aa + (-2.25)
            liu_10_mc.bullet.ShotBulletMode(3, 1, _editor_class["liu_10_mc_Boss1 Bullet02"], self.x, self.y + 32, 0, 0, 0, 0, 0, 14, 1, 4.4, 1.5, aa, 0)
            aa = aa + (-3.4615)
            a2 = aa
            liu_10_mc.bullet.ShotBulletMode(3, 2, _editor_class["liu_10_mc_Boss1 Bullet03"], self.x, self.y + 32, 0, 0, 0, 0, 0, 14, 1, 4.4, 1.5, aa, 0)
            aa = aa + (-3.4615)
            liu_10_mc.bullet.ShotBulletMode(3, 3, _editor_class["liu_10_mc_Boss1 Bullet04"], self.x, self.y + 32, 0, 0, 0, 0, 0, 14, 1, 4.4, 1.5, aa, 0)
            aa = aa + (-3.4615)
            
            task._Wait(11)
            aa = a2
            liu_10_mc.bullet.ShotBulletMode(3, 0, _editor_class["liu_10_mc_Boss1 Bullet01"], self.x, self.y + 32, 0, 0, 0, 0, 0, 14, 1, 4.4, 1.5, aa, 0)
            aa = aa - (-2.25)
            liu_10_mc.bullet.ShotBulletMode(3, 0, _editor_class["liu_10_mc_Boss1 Bullet01"], self.x, self.y + 32, 0, 0, 0, 0, 0, 14, 1, 4.4, 1.5, aa, 0)
            aa = aa - (-2.25)
            liu_10_mc.bullet.ShotBulletMode(3, 0, _editor_class["liu_10_mc_Boss1 Bullet01"], self.x, self.y + 32, 0, 0, 0, 0, 0, 14, 1, 4.4, 1.5, aa, 0)
            aa = aa - (-2.25)
            liu_10_mc.bullet.ShotBulletMode(3, 1, _editor_class["liu_10_mc_Boss1 Bullet02"], self.x, self.y + 32, 0, 0, 0, 0, 0, 14, 1, 4.4, 1.5, aa, 0)
            aa = aa - (-3.4615)
            liu_10_mc.bullet.ShotBulletMode(3, 2, _editor_class["liu_10_mc_Boss1 Bullet03"], self.x, self.y + 32, 0, 0, 0, 0, 0, 14, 1, 4.4, 1.5, aa, 0)
            aa = aa - (-3.4615)
            liu_10_mc.bullet.ShotBulletMode(3, 3, _editor_class["liu_10_mc_Boss1 Bullet04"], self.x, self.y + 32, 0, 0, 0, 0, 0, 14, 1, 4.4, 1.5, aa, 0)
            aa = aa - (-3.4615)
            task._Wait(11)
            a = a - (-9)
            a2 = a2 + (-9)
        end
    end
end
_editor_tasks["liu_10_mc_Boss1_at1b"]=function()
    return function()
        local self=task.GetSelf()
        local a=(ran:Float(-180, 180))
        local a2=(0)
        for _=1,3 do
            local aa=(a)
            liu_10_mc.bullet.ShotBulletMode(3, 0, _editor_class["liu_10_mc_Boss1 Bullet01"], self.x, self.y + 32, 0, 0, 0, 0, 0, 14, 1, 4.4, 1.5, aa, 0)
            aa = aa - (-2.25)
            liu_10_mc.bullet.ShotBulletMode(3, 0, _editor_class["liu_10_mc_Boss1 Bullet01"], self.x, self.y + 32, 0, 0, 0, 0, 0, 14, 1, 4.4, 1.5, aa, 0)
            aa = aa - (-2.25)
            liu_10_mc.bullet.ShotBulletMode(3, 0, _editor_class["liu_10_mc_Boss1 Bullet01"], self.x, self.y + 32, 0, 0, 0, 0, 0, 14, 1, 4.4, 1.5, aa, 0)
            aa = aa - (-2.25)
            liu_10_mc.bullet.ShotBulletMode(3, 1, _editor_class["liu_10_mc_Boss1 Bullet02"], self.x, self.y + 32, 0, 0, 0, 0, 0, 14, 1, 4.4, 1.5, aa, 0)
            aa = aa - (-3.4615)
            a2 = aa
            liu_10_mc.bullet.ShotBulletMode(3, 2, _editor_class["liu_10_mc_Boss1 Bullet03"], self.x, self.y + 32, 0, 0, 0, 0, 0, 14, 1, 4.4, 1.5, aa, 0)
            aa = aa - (-3.4615)
            liu_10_mc.bullet.ShotBulletMode(3, 3, _editor_class["liu_10_mc_Boss1 Bullet04"], self.x, self.y + 32, 0, 0, 0, 0, 0, 14, 1, 4.4, 1.5, aa, 0)
            aa = aa - (-3.4615)
            task._Wait(11)
            aa = a2
            liu_10_mc.bullet.ShotBulletMode(3, 0, _editor_class["liu_10_mc_Boss1 Bullet01"], self.x, self.y + 32, 0, 0, 0, 0, 0, 14, 1, 4.4, 1.5, aa, 0)
            aa = aa + (-2.25)
            liu_10_mc.bullet.ShotBulletMode(3, 0, _editor_class["liu_10_mc_Boss1 Bullet01"], self.x, self.y + 32, 0, 0, 0, 0, 0, 14, 1, 4.4, 1.5, aa, 0)
            aa = aa + (-2.25)
            liu_10_mc.bullet.ShotBulletMode(3, 0, _editor_class["liu_10_mc_Boss1 Bullet01"], self.x, self.y + 32, 0, 0, 0, 0, 0, 14, 1, 4.4, 1.5, aa, 0)
            aa = aa + (-2.25)
            liu_10_mc.bullet.ShotBulletMode(3, 1, _editor_class["liu_10_mc_Boss1 Bullet02"], self.x, self.y + 32, 0, 0, 0, 0, 0, 14, 1, 4.4, 1.5, aa, 0)
            aa = aa + (-3.4615)
            liu_10_mc.bullet.ShotBulletMode(3, 2, _editor_class["liu_10_mc_Boss1 Bullet03"], self.x, self.y + 32, 0, 0, 0, 0, 0, 14, 1, 4.4, 1.5, aa, 0)
            aa = aa + (-3.4615)
            liu_10_mc.bullet.ShotBulletMode(3, 3, _editor_class["liu_10_mc_Boss1 Bullet04"], self.x, self.y + 32, 0, 0, 0, 0, 0, 14, 1, 4.4, 1.5, aa, 0)
            aa = aa + (-3.4615)
            task._Wait(11)
            a = a + (-9)
            a2 = a2 - (-9)
        end
    end
end
_editor_class["liu_10_mc_Boss1 Bullet01"]=Class(bullet)
_editor_class["liu_10_mc_Boss1 Bullet01"].init=function(self,_x,_y)
bullet.init(self,liu_10_mc.bullet.bullet_class,COLOR_RED,true,true)
self.x,self.y=_x,_y
    PlaySound("tan00",0.3,self.x/256,false)
    liu_10_mc.bullet.BulletClassInit(self, 0, 6)
    liu_10_mc.bullet.SetBulletPreimg(self, 1, true)
end
_editor_class["liu_10_mc_Boss1 Bullet02"]=Class(bullet)
_editor_class["liu_10_mc_Boss1 Bullet02"].init=function(self,_x,_y)
bullet.init(self,liu_10_mc.bullet.bullet_class,COLOR_RED,true,true)
self.x,self.y=_x,_y
    PlaySound("tan00",0.3,self.x/256,false)
    liu_10_mc.bullet.BulletClassInit(self, 3, 6)
    liu_10_mc.bullet.SetBulletPreimg(self, 1, true)
end
_editor_class["liu_10_mc_Boss1 Bullet03"]=Class(bullet)
_editor_class["liu_10_mc_Boss1 Bullet03"].init=function(self,_x,_y)
bullet.init(self,liu_10_mc.bullet.bullet_class,COLOR_RED,true,true)
self.x,self.y=_x,_y
    PlaySound("tan00",0.3,self.x/256,false)
    liu_10_mc.bullet.BulletClassInit(self, 17, 3)
    liu_10_mc.bullet.SetBulletPreimg(self, 1, true)
end
_editor_class["liu_10_mc_Boss1 Bullet04"]=Class(bullet)
_editor_class["liu_10_mc_Boss1 Bullet04"].init=function(self,_x,_y)
bullet.init(self,liu_10_mc.bullet.bullet_class,COLOR_RED,true,true)
self.x,self.y=_x,_y
    PlaySound("tan00",0.3,self.x/256,false)
    _object.set_color(self,"mul+add",255,255,255,255)
    self.omiga = -45
    liu_10_mc.bullet.BulletClassInit(self, 26, 1)
    liu_10_mc.bullet.SetBulletPreimg(self, 1, true)
end
_editor_tasks["liu_10_mc_BossCard1_at1"]=function()
    return function()
        local self=task.GetSelf()
        local a=(-180 + (ran:Float(-180, 180) / 8))
        local r=(80)
        for _=1,80 do
            liu_10_mc.bullet.ShotBulletMode(3, 0, _editor_class["liu_10_mc_BossCard1 Bullet01"], self.x, self.y, 0, 0, r, 0, 0, 1, 4, 2.5, 1, a, 10.588235)
            r = r - 1
            a = a - (-9)
            task._Wait(2)
        end
        for _=1,40 do
            liu_10_mc.bullet.ShotBulletMode(3, 0, _editor_class["liu_10_mc_BossCard1 Bullet01"], self.x, self.y, 0, 0, r, 0, 0, 1, 4, 2.5, 1, a, 10.588235)
            r = r - 1
            a = a - (-9)
            task._Wait(1)
        end
    end
end
_editor_tasks["liu_10_mc_BossCard1_at1h"]=function()
    return function()
        local self=task.GetSelf()
        local a=(-180 + (ran:Float(-180, 180) / 8))
        local r=(80)
        for _=1,80 do
            liu_10_mc.bullet.ShotBulletMode(3, 0, _editor_class["liu_10_mc_BossCard1 Bullet01"], self.x, self.y, 0, 0, r, 0, 0, 1, 4, 2.5, 1, a, 0.45)
            r = r - 1
            a = a + (-9)
            task._Wait(2)
        end
        for _=1,40 do
            liu_10_mc.bullet.ShotBulletMode(3, 0, _editor_class["liu_10_mc_BossCard1 Bullet01"], self.x, self.y, 0, 0, r, 0, 0, 1, 4, 2.5, 1, a, 0.45)
            r = r - 1
            a = a + (-9)
            task._Wait(1)
        end
    end
end
_editor_tasks["liu_10_mc_BossCard1_at2"]=function()
    return function()
        local self=task.GetSelf()
        local a=(90 + (ran:Float(-180, 180) / 8))
        local r=(80)
        for _=1,40 do
            liu_10_mc.bullet.ShotBulletMode(3, 1, _editor_class["liu_10_mc_BossCard1 Bullet02"], self.x, self.y, 0, 0, r, 0, 0, 1, 4, 1.6, 0.5, a, 8.1818178)
            r = r - 1
            a = a - (-9)
            task._Wait(2)
        end
        for _=1,40 do
            liu_10_mc.bullet.ShotBulletMode(3, 1, _editor_class["liu_10_mc_BossCard1 Bullet02"], self.x, self.y, 0, 0, r, 0, 0, 1, 4, 1.6, 0.5, a, 7.5)
            r = r - 1
            a = a + (-9)
            task._Wait(1)
        end
    end
end
_editor_tasks["liu_10_mc_BossCard1_at2h"]=function()
    return function()
        local self=task.GetSelf()
        local a=(90 + (ran:Float(-180, 180) / 8))
        local r=(80)
        for _=1,40 do
            liu_10_mc.bullet.ShotBulletMode(3, 1, _editor_class["liu_10_mc_BossCard1 Bullet02"], self.x, self.y, 0, 0, r, 0, 0, 1, 4, 1.6, 0.5, a, 8.1818178)
            r = r - 1
            a = a + (-9)
            task._Wait(2)
        end
        for _=1,40 do
            liu_10_mc.bullet.ShotBulletMode(3, 1, _editor_class["liu_10_mc_BossCard1 Bullet02"], self.x, self.y, 0, 0, r, 0, 0, 1, 4, 1.6, 0.5, a, 7.5)
            r = r - 1
            a = a - (-9)
            task._Wait(1)
        end
    end
end
_editor_class["liu_10_mc_BossCard1 Bullet01"]=Class(bullet)
_editor_class["liu_10_mc_BossCard1 Bullet01"].init=function(self,_x,_y)
bullet.init(self,liu_10_mc.bullet.bullet_class,COLOR_RED,true,true)
self.x,self.y=_x,_y
    PlaySound("tan00",0.3,self.x/256,false)
    _object.set_color(self,"mul+add",255,255,255,255)
    liu_10_mc.bullet.BulletClassInit(self, 29, 0)
    liu_10_mc.bullet.SetBulletPreimg(self, 1, true)
    lasttask=task.New(self,function()
        PlaySound("kira00",0.3,self.x/256,false)
        do
            local vv=self._speed local _d_vv=(0.016666668)
            for _=1,60 do
                task._Wait(1)
                SetV2(self,vv,self._angle,true,false)
                vv=vv+_d_vv
            end
        end
    end)
end
_editor_class["liu_10_mc_BossCard1 Bullet02"]=Class(bullet)
_editor_class["liu_10_mc_BossCard1 Bullet02"].init=function(self,_x,_y)
bullet.init(self,liu_10_mc.bullet.bullet_class,COLOR_RED,true,true)
self.x,self.y=_x,_y
    PlaySound("tan00",0.3,self.x/256,false)
    liu_10_mc.bullet.BulletClassInit(self, 28, 4)
    liu_10_mc.bullet.SetBulletPreimg(self, 1, true)
end
_editor_tasks["liu_10_mc_Boss2_at1"]=function()
    return function()
        local self=task.GetSelf()
        local x=(self.x - 114)
        local y=(self.y - 54)
        local a=(Angle(x, y, player))
        last=New(_editor_class["liu_10_mc_Boss2_Laser01"],self.x - 114, self.y -54,a)
        _connect(self,last,0,true)
        x, y = self.x + 114, self.y - 54
        a = Angle(x, y, player)
        last=New(_editor_class["liu_10_mc_Boss2_Laser01"],self.x + 114, self.y -54,a)
        _connect(self,last,0,true)
        x, y = self.x - 64, self.y + 80
        a = Angle(x, y, player)
        last=New(_editor_class["liu_10_mc_Boss2_Laser01"],self.x - 64, self.y + 80,a)
        _connect(self,last,0,true)
        x, y = self.x + 64, self.y + 80
        a = Angle(x, y, player)
        last=New(_editor_class["liu_10_mc_Boss2_Laser01"],self.x + 64, self.y + 80,a)
        _connect(self,last,0,true)
    end
end
_editor_tasks["liu_10_mc_Boss2_at1h"]=function(a)
    return function()
        local self=task.GetSelf()
        local x=(self.x - 114)
        local y=(self.y - 54)
        local aa=(Angle(x, y, player) + (a * ran:Float(-1, 1)))
        last=New(_editor_class["liu_10_mc_Boss2_Laser01"],self.x - 114, self.y -54,aa)
        _connect(self,last,0,true)
        x, y = self.x + 114, self.y - 54
        aa = Angle(x, y, player) + (a * ran:Float(-1, 1))
        last=New(_editor_class["liu_10_mc_Boss2_Laser01"],self.x + 114, self.y -54,aa)
        _connect(self,last,0,true)
        x, y = self.x - 64, self.y + 80
        aa = Angle(x, y, player) + (a * ran:Float(-1, 1))
        last=New(_editor_class["liu_10_mc_Boss2_Laser01"],self.x - 64, self.y + 80,aa)
        _connect(self,last,0,true)
        x, y = self.x + 64, self.y + 80
        aa = Angle(x, y, player) + (a * ran:Float(-1, 1))
        last=New(_editor_class["liu_10_mc_Boss2_Laser01"],self.x + 64, self.y + 80,aa)
        _connect(self,last,0,true)
    end
end
_editor_tasks["liu_10_mc_Boss2_at2"]=function()
    return function()
        local self=task.GetSelf()
        for _=1,_infinite do
            local a=(ran:Float(-180, 180) /  5)
            local a2=(-180 / 11)
            liu_10_mc.bullet.ShotBulletMode(0, 0, _editor_class["liu_10_mc_Boss2 Bullet01"], self.x, self.y, 0, 0, 0, 0, 0, 12, 1, 5, 3.5, a, a2, {Angle(self, player)})
            task._Wait(17)
        end
    end
end
_editor_class["liu_10_mc_Boss2_Laser01"]=Class(_object)
_editor_class["liu_10_mc_Boss2_Laser01"].init=function(self,_x,_y,a)
    self.x,self.y=_x,_y
    self.img="img_void"
    self.layer=LAYER_ENEMY_BULLET-5
    self.group=GROUP_GHOST
    self.hide=false
    self.bound=true
    self.navi=false
    self.hp=10
    self.maxhp=10
    self.colli=true
    self._servants={}
    self._blend,self._a,self._r,self._g,self._b='',255,255,255,255
    PlaySound("lazer00",0.3,self.x/256,false)
    _object.set_color(self,"mul+add",255,255,255,255)
    self.laser = liu_10_mc.bullet.Laser(self, 7, 2, 0, 512, 0, 16, 60, 16, 60, 15, 2, true)
    SetV2(self,8,a,true,false)
end
_editor_class["liu_10_mc_Boss2_Laser01"].frame=function(self)
    self.class.base.frame(self)
    self.laser:frame()
end
_editor_class["liu_10_mc_Boss2_Laser01"].render=function(self)
    self.class.base.render(self)
    self.laser:render()
end
_editor_class["liu_10_mc_Boss2_Laser01"].del=function(self)
    self.laser:del()
end
_editor_class["liu_10_mc_Boss2_Laser01"].kill=function(self)
    self.laser:kill()
end
_editor_class["liu_10_mc_Boss2 Bullet01"]=Class(bullet)
_editor_class["liu_10_mc_Boss2 Bullet01"].init=function(self,_x,_y,a)
bullet.init(self,liu_10_mc.bullet.bullet_class,COLOR_RED,true,true)
self.x,self.y=_x,_y
    PlaySound("tan00",0.3,self.x/256,false)
    _object.set_color(self,"mul+add",255,255,255,255)
    liu_10_mc.bullet.BulletClassInit(self, 29, 0)
    liu_10_mc.bullet.SetBulletPreimg(self, 1, true)
    lasttask=task.New(self,function()
        do
            local _beg_vv=self._speed local vv=_beg_vv local _end_vv=0 local _d_vv=(_end_vv-_beg_vv)/(60)
            for _=1,60 do
                task._Wait(1)
                SetV2(self,vv,self._angle,true,false)
                vv=vv+_d_vv
            end
        end
        PlaySound("kira00",0.3,self.x/256,false)
        SetV2(self,3,a,true,false)
    end)
end
_editor_tasks["liu_10_mc_BossCard2_at1"]=function(a, x, y)
    return function()
        local self=task.GetSelf()
        liu_10_mc.bullet.ShotBulletMode(1, 0, _editor_class["liu_10_mc_BossCard2 Bullet01"], x, y, 0, 0, 16, 0, 0, 1, 3, 2.8, 1, a, 16.363635)
    end
end
_editor_tasks["liu_10_mc_BossCard2_at2"]=function()
    return function()
        local self=task.GetSelf()
        local a=(Angle(self, player))
        for _=1,16 do
            last=New(_editor_class["liu_10_mc_BossCard2_Laser01"],self.x,self.y,a)
            _connect(self,last,0,true)
            a = a + (-22.5)
        end
    end
end
_editor_class["liu_10_mc_BossCard2 Bullet01"]=Class(bullet)
_editor_class["liu_10_mc_BossCard2 Bullet01"].init=function(self,_x,_y)
bullet.init(self,liu_10_mc.bullet.bullet_class,COLOR_RED,true,true)
self.x,self.y=_x,_y
    PlaySound("tan00",0.3,self.x/256,false)
    liu_10_mc.bullet.BulletClassInit(self, 21, 3)
    liu_10_mc.bullet.SetBulletPreimg(self, 1, true)
end
_editor_class["liu_10_mc_BossCard2_Laser01"]=Class(_object)
_editor_class["liu_10_mc_BossCard2_Laser01"].init=function(self,_x,_y,a)
    self.x,self.y=_x,_y
    self.img="img_void"
    self.layer=LAYER_ENEMY_BULLET-5
    self.group=GROUP_GHOST
    self.hide=false
    self.bound=true
    self.navi=false
    self.hp=10
    self.maxhp=10
    self.colli=true
    self._servants={}
    self._blend,self._a,self._r,self._g,self._b='',255,255,255,255
    PlaySound("lazer00",0.3,self.x/256,false)
    _object.set_color(self,"mul+add",255,255,255,255)
    self.laser = liu_10_mc.bullet.Laser(self, 7, 4, 0, 512, 0, 16, 60, 16, 30, 15, 4, true)
    SetV2(self,8,a,true,false)
end
_editor_class["liu_10_mc_BossCard2_Laser01"].frame=function(self)
    self.class.base.frame(self)
    self.laser:frame()
end
_editor_class["liu_10_mc_BossCard2_Laser01"].render=function(self)
    self.class.base.render(self)
    self.laser:render()
end
_editor_class["liu_10_mc_BossCard2_Laser01"].del=function(self)
    self.laser:del()
end
_editor_class["liu_10_mc_BossCard2_Laser01"].kill=function(self)
    self.laser:kill()
end
_editor_tasks["liu_10_mc_Boss3_at1"]=function()
    return function()
        local self=task.GetSelf()
        local a=(-90)
        for _=1,60 do
            local x=(32 * cos(a + (-90)))
            local y=(32 * sin(a + (-90)))
            liu_10_mc.bullet.ShotBulletMode(1, 0, _editor_class["liu_10_mc_Boss3 Bullet01"], self.x, self.y, x, y, 0, 0, 0, 1, 5, 3, 2.7, a, a)
            a = a + (-11.25)
            task._Wait(1)
        end
    end
end
_editor_tasks["liu_10_mc_Boss3_at1e1"]=function()
    return function()
        local self=task.GetSelf()
        local a=(90 + (ran:Float(-180, 180) / 16))
        for _=1,60 do
            local x=(16 * cos(a + (-90)))
            local y=(16 * sin(a + (-90)))
            liu_10_mc.bullet.ShotBulletMode(1, 0, _editor_class["liu_10_mc_Boss3 Bullet02"], self.x - 114, self.y - 54, x, y, 0, 0, 0, 1, 5, 1, 0.7, a, a, {13})
            a = a + (-11.25)
            task._Wait(1)
        end
    end
end
_editor_tasks["liu_10_mc_Boss3_at1e2"]=function()
    return function()
        local self=task.GetSelf()
        local a=(90 + (ran:Float(-180, 180) / 16))
        for _=1,60 do
            local x=(16 * cos(a + (-90)))
            local y=(16 * sin(a + (-90)))
            liu_10_mc.bullet.ShotBulletMode(1, 0, _editor_class["liu_10_mc_Boss3 Bullet02"], self.x + 114, self.y - 54, x, y, 0, 0, 0, 1, 5, 1, 0.7, a, a, {13})
            a = a - (-11.25)
            task._Wait(1)
        end
    end
end
_editor_tasks["liu_10_mc_Boss3_at1e3"]=function()
    return function()
        local self=task.GetSelf()
        local a=(0 + (ran:Float(-180, 180) / 16))
        for _=1,60 do
            local x=(16 * cos(a + (-90)))
            local y=(16 * sin(a + (-90)))
            liu_10_mc.bullet.ShotBulletMode(1, 0, _editor_class["liu_10_mc_Boss3 Bullet02"], self.x - 64, self.y + 80, x, y, 0, 0, 0, 1, 5, 1, 0.7, a, a, {2})
            a = a - (-11.25)
            task._Wait(1)
        end
    end
end
_editor_tasks["liu_10_mc_Boss3_at1e4"]=function()
    return function()
        local self=task.GetSelf()
        local a=(-180 + (ran:Float(-180, 180) / 16))
        for _=1,60 do
            local x=(16 * cos(a + (-90)))
            local y=(16 * sin(a + (-90)))
            liu_10_mc.bullet.ShotBulletMode(1, 0, _editor_class["liu_10_mc_Boss3 Bullet02"], self.x + 64, self.y + 80, x, y, 0, 0, 0, 1, 5, 1, 0.7, a, a, {2})
            a = a + (-11.25)
            task._Wait(1)
        end
    end
end
_editor_class["liu_10_mc_Boss3 Bullet01"]=Class(bullet)
_editor_class["liu_10_mc_Boss3 Bullet01"].init=function(self,_x,_y)
bullet.init(self,liu_10_mc.bullet.bullet_class,COLOR_RED,true,true)
self.x,self.y=_x,_y
    local count=(0)
    self.bound = false
    for _,unit in ObjList(GROUP_ENEMY_BULLET) do
        count = count + 1
        if count >= 2000 then
            _del(self,false)
        else
        end
    end
    PlaySound("tan00",0.3,self.x/256,false)
    liu_10_mc.bullet.BulletClassInit(self, 7, 4)
    liu_10_mc.bullet.SetBulletPreimg(self, 1, true)
    lasttask=task.New(self,function()
        task._Wait(100)
        self.bound = true
    end)
end
_editor_class["liu_10_mc_Boss3 Bullet02"]=Class(bullet)
_editor_class["liu_10_mc_Boss3 Bullet02"].init=function(self,_x,_y,co)
bullet.init(self,liu_10_mc.bullet.bullet_class,COLOR_RED,true,true)
self.x,self.y=_x,_y
    self.bound = false
    local count=(0)
    for _,unit in ObjList(GROUP_ENEMY_BULLET) do
        count = count + 1
        if count >= 2000 then
            _del(self,false)
        else
        end
    end
    PlaySound("tan00",0.3,self.x/256,false)
    liu_10_mc.bullet.BulletClassInit(self, 7, co)
    liu_10_mc.bullet.SetBulletPreimg(self, 1, true)
    lasttask=task.New(self,function()
        task._Wait(100)
        self.bound = true
    end)
    lasttask=task.New(self,function()
        PlaySound("kira00",0.3,self.x/256,false)
        do
            local vv=self._speed local _d_vv=(0.033333335)
            for _=1,60 do
                task._Wait(1)
                SetV2(self,vv,self._angle,true,false)
                vv=vv+_d_vv
            end
        end
    end)
end
_editor_tasks["liu_10_mc_BossCard3_at"]=function()
    return function()
        local self=task.GetSelf()
        local t=(100)
        task._Wait(300)
        for _=1,_infinite do
            last=New(_editor_class["liu_10_mc_BossCard3 Bullet01"],self.x - 114,self.y - 54)
            last=New(_editor_class["liu_10_mc_BossCard3 Bullet01"],self.x + 114,self.y - 54)
            last=New(_editor_class["liu_10_mc_BossCard3 Bullet01"],self.x - 64,self.y + 80)
            last=New(_editor_class["liu_10_mc_BossCard3 Bullet01"],self.x + 64,self.y + 80)
            task._Wait(t)
            if t >= 60 then
                t = t - 5
            else
            end
        end
    end
end
_editor_tasks["liu_10_mc_BossCard3_at2"]=function()
    return function()
        local self=task.GetSelf()
        local x=(240)
        local y=(448)
        for _=1,_infinite do
            local dy=(-32)
            for _=1,4 do
                y = (ran:Float(0, 1) * 64) + dy
                last=New(_editor_class["liu_10_mc_BossCard3 Laser01"],x,224 - y,-135)
                _connect(self,last,0,true)
                task._Wait(10)
                dy = dy + 64
                dy = dy + 64
            end
            dy = (-32) + 64
            for _=1,4 do
                y = (ran:Float(0, 1) * 64) + dy
                last=New(_editor_class["liu_10_mc_BossCard3 Laser01"],x,224 - y,-135)
                _connect(self,last,0,true)
                task._Wait(10)
                dy = dy + 64
                dy = dy + 64
            end
        end
    end
end
_editor_tasks["liu_10_mc_BossCard3_at2b"]=function()
    return function()
        local self=task.GetSelf()
        local x=(-240)
        task._Wait(40)
        for _=1,_infinite do
            local dy=(0)
            for _=1,4 do
                local y = (ran:Float(0, 1) * 64) + dy
                last=New(_editor_class["liu_10_mc_BossCard3 Laser01"],x,224 - y,45)
                _connect(self,last,0,true)
                task._Wait(10)
                dy = dy + 64
                dy = dy + 64
            end
            dy = (-32) + 64
            for _=1,4 do
                local y = (ran:Float(0, 1) * 64) + dy
                last=New(_editor_class["liu_10_mc_BossCard3 Laser01"],x,224 - y,45)
                _connect(self,last,0,true)
                task._Wait(10)
                dy = dy + 64
                dy = dy + 64
            end
        end
    end
end
_editor_class["liu_10_mc_BossCard3 Bullet01"]=Class(bullet)
_editor_class["liu_10_mc_BossCard3 Bullet01"].init=function(self,_x,_y)
bullet.init(self,liu_10_mc.bullet.bullet_class,COLOR_RED,true,true)
self.x,self.y=_x,_y
    PlaySound("tan00",0.3,self.x/256,false)
    liu_10_mc.bullet.BulletClassInit(self, 15, 6)
    liu_10_mc.bullet.SetBulletPreimg(self, 1, true)
    self.omiga = -6
    SetV2(self,2.5,Angle(self, player),true,false)
end
_editor_class["liu_10_mc_BossCard3 Laser01"]=Class(_object)
_editor_class["liu_10_mc_BossCard3 Laser01"].init=function(self,_x,_y,a)
    self.x,self.y=_x,_y
    self.img="img_void"
    self.layer=LAYER_ENEMY_BULLET-5
    self.group=GROUP_GHOST
    self.hide=false
    self.bound=true
    self.navi=false
    self.hp=10
    self.maxhp=10
    self.colli=true
    self._servants={}
    self._blend,self._a,self._r,self._g,self._b='',255,255,255,255
    PlaySound("lazer00",0.3,self.x/256,false)
    _object.set_color(self,"mul+add",255,255,255,255)
    self.laser = liu_10_mc.bullet.Laser(self, -1, 13, -1, 32, 0, 16, -1, -1, -1, -1, 13, true)
    self.laser.bound = false
    SetV2(self,4,a,true,false)
    lasttask=task.New(self,function()
        task._Wait(120)
        self.laser.bound = true
    end)
    lasttask=task.New(self,function()
        do
            local aa=self._angle local _d_aa=(-0.9)
            for _=1,_infinite do
                task._Wait(1)
                SetV2(self,self._speed,aa,true,false)
                aa=aa+_d_aa
            end
        end
    end)
end
_editor_class["liu_10_mc_BossCard3 Laser01"].frame=function(self)
    self.class.base.frame(self)
    self.laser:frame()
end
_editor_class["liu_10_mc_BossCard3 Laser01"].render=function(self)
    self.class.base.render(self)
    self.laser:render()
end
_editor_class["liu_10_mc_BossCard3 Laser01"].del=function(self)
    self.laser:del()
end
_editor_class["liu_10_mc_BossCard3 Laser01"].kill=function(self)
    self.laser:kill()
end
_editor_tasks["liu_10_mc_Boss4_at1e1"]=function()
    return function()
        local self=task.GetSelf()
        local a=((Angle(self, player) + (-180)) + (ran:Float(-180, 180) / 16))
        local i=(0)
        for _=1,32 do
            local x=(16 * cos(a + (-90)))
            local y=(16 * sin(a + (-90)))
            if (i%2) == 0 then
                liu_10_mc.bullet.ShotBulletMode(1, 0, _editor_class["liu_10_mc_Boss4 Bullet01"], self.x - 114, self.y - 54, x, y, 0, 0, 0, 1, 3, 1.2, 1, a, a, {13})
            else
            end
            i = i + 1
            a = a + (-11.25)
            task._Wait(1)
        end
        liu_10_mc.bullet.ShotBulletMode(0, 1, _editor_class["liu_10_mc_Boss4 Bullet02"], self.x - 114, self.y - 54, 0, 0, 0, 0, 0, 1, 7, 5, 1.2, 0, 0, {1})
    end
end
_editor_tasks["liu_10_mc_Boss4_at1e2"]=function()
    return function()
        local self=task.GetSelf()
        local a=((Angle(self, player) + (-180)) + (ran:Float(-180, 180) / 16))
        local i=(0)
        for _=1,32 do
            local x=(16 * cos(a + (-90)))
            local y=(16 * sin(a + (-90)))
            if (i%2) == 0 then
                liu_10_mc.bullet.ShotBulletMode(1, 0, _editor_class["liu_10_mc_Boss4 Bullet01"], self.x + 114, self.y - 54, x, y, 0, 0, 0, 1, 3, 1.2, 1, a, a, {13})
            else
            end
            i = i + 1
            a = a - (-11.25)
            task._Wait(1)
        end
        liu_10_mc.bullet.ShotBulletMode(0, 1, _editor_class["liu_10_mc_Boss4 Bullet02"], self.x + 114, self.y - 54, 0, 0, 0, 0, 0, 1, 7, 5, 1.2, 0, 0, {1})
    end
end
_editor_tasks["liu_10_mc_Boss4_at1e3"]=function()
    return function()
        local self=task.GetSelf()
        local a=((Angle(self, player) - (-90)) + (ran:Float(-180, 180) / 16))
        local i=(0)
        for _=1,32 do
            local x=(16 * cos(a + (-90)))
            local y=(16 * sin(a + (-90)))
            if (i%2) == 0 then
                liu_10_mc.bullet.ShotBulletMode(1, 0, _editor_class["liu_10_mc_Boss4 Bullet01"], self.x - 64, self.y + 80, x, y, 0, 0, 0, 1, 3, 1.2, 1, a, a, {2})
            else
            end
            i = i + 1
            a = a - (-11.25)
            task._Wait(1)
        end
        liu_10_mc.bullet.ShotBulletMode(0, 1, _editor_class["liu_10_mc_Boss4 Bullet02"], self.x - 64, self.y + 80, 0, 0, 0, 0, 0, 1, 7, 5, 1.2, 0, 0, {1})
    end
end
_editor_tasks["liu_10_mc_Boss4_at1e4"]=function()
    return function()
        local self=task.GetSelf()
        local a=((Angle(self, player) - (-90)) + (ran:Float(-180, 180) / 16))
        local i=(0)
        for _=1,32 do
            local x=(16 * cos(a + (-90)))
            local y=(16 * sin(a + (-90)))
            if (i%2) == 0 then
                liu_10_mc.bullet.ShotBulletMode(1, 0, _editor_class["liu_10_mc_Boss4 Bullet01"], self.x + 64, self.y + 80, x, y, 0, 0, 0, 1, 3, 1.2, 1, a, a, {2})
            else
            end
            i = i + 1
            a = a + (-11.25)
            task._Wait(1)
        end
        liu_10_mc.bullet.ShotBulletMode(0, 1, _editor_class["liu_10_mc_Boss4 Bullet02"], self.x + 64, self.y + 80, 0, 0, 0, 0, 0, 1, 7, 5, 1.2, 0, 0, {1})
    end
end
_editor_class["liu_10_mc_Boss4 Bullet01"]=Class(bullet)
_editor_class["liu_10_mc_Boss4 Bullet01"].init=function(self,_x,_y,co)
bullet.init(self,liu_10_mc.bullet.bullet_class,COLOR_RED,true,true)
self.x,self.y=_x,_y
    self.bound = false
    local count=(0)
    for _,unit in ObjList(GROUP_ENEMY_BULLET) do
        count = count + 1
        if count >= 2000 then
            _del(self,false)
        else
        end
    end
    PlaySound("tan00",0.3,self.x/256,false)
    liu_10_mc.bullet.BulletClassInit(self, 7, co)
    liu_10_mc.bullet.SetBulletPreimg(self, 1, true)
    lasttask=task.New(self,function()
        task._Wait(100)
        self.bound = true
    end)
    lasttask=task.New(self,function()
        PlaySound("kira00",0.3,self.x/256,false)
        do
            local vv=self._speed local _d_vv=(0.033333335)
            for _=1,60 do
                task._Wait(1)
                SetV2(self,vv,self._angle,true,false)
                vv=vv+_d_vv
            end
        end
    end)
end
_editor_class["liu_10_mc_Boss4 Bullet02"]=Class(bullet)
_editor_class["liu_10_mc_Boss4 Bullet02"].init=function(self,_x,_y,co)
bullet.init(self,liu_10_mc.bullet.bullet_class,COLOR_RED,true,true)
self.x,self.y=_x,_y
    self.bound = false
    local count=(0)
    for _,unit in ObjList(GROUP_ENEMY_BULLET) do
        count = count + 1
        if count >= 2000 then
            _del(self,false)
        else
        end
    end
    PlaySound("tan00",0.3,self.x/256,false)
    liu_10_mc.bullet.BulletClassInit(self, 17, 1)
    liu_10_mc.bullet.SetBulletPreimg(self, 1, true)
    lasttask=task.New(self,function()
        task._Wait(100)
        self.bound = true
    end)
end
_editor_class["liu_10_mc_BossCard4 Laser01"]=Class(_object)
_editor_class["liu_10_mc_BossCard4 Laser01"].init=function(self,_x,_y,x, y, a)
    self.x,self.y=_x,_y
    self.img="img_void"
    self.layer=LAYER_ENEMY_BULLET-5
    self.group=GROUP_GHOST
    self.hide=false
    self.bound=true
    self.navi=false
    self.hp=10
    self.maxhp=10
    self.colli=true
    self._servants={}
    self._blend,self._a,self._r,self._g,self._b='',255,255,255,255
    last=New(_editor_class["liu_10_mc_BossCard4 Laser01bk"],self.x,self.y)
    _connect(self,last,0,true)
    liu_10_mc.stgenm.SetBossLaser(self, 1)
    self.rot = a
    self._dx, self._dy = x, y
    self.colli = false
    lasttask=task.New(self,function()
        task._Wait(120)
        self.colli = true
        task._Wait(60)
        self.delete = true
        task._Wait(30)
    end)
end
_editor_class["liu_10_mc_BossCard4 Laser01"].frame=function(self)
    self.class.base.frame(self)
    self.laser:frame()
    _set_rel_pos(self,self._dx, self._dy,self.rot,false)
end
_editor_class["liu_10_mc_BossCard4 Laser01"].render=function(self)
    self.class.base.render(self)
    self.laser:render()
end
_editor_class["liu_10_mc_BossCard4 Laser01bk"]=Class(_object)
_editor_class["liu_10_mc_BossCard4 Laser01bk"].init=function(self,_x,_y)
    self.x,self.y=_x,_y
    self.img="img_void"
    self.layer=LAYER_ENEMY_BULLET - 6
    self.group=GROUP_GHOST
    self.hide=false
    self.bound=true
    self.navi=false
    self.hp=10
    self.maxhp=10
    self.colli=true
    self._servants={}
    self._blend,self._a,self._r,self._g,self._b='',255,255,255,255
    liu_10_mc.stgenm.SetBossLaser(self, 2)
    self.colli = false
    lasttask=task.New(self,function()
        task._Wait(120)
        self.colli = true
        task._Wait(60)
        self.delete = true
        task._Wait(30)
    end)
end
_editor_class["liu_10_mc_BossCard4 Laser01bk"].frame=function(self)
    self.class.base.frame(self)
    self.laser:frame()
    _set_rel_pos(self,0,0,0,true)
end
_editor_class["liu_10_mc_BossCard4 Laser01bk"].render=function(self)
    self.class.base.render(self)
    self.laser:render()
end
_editor_class["liu_10_mc_BossCard4 Laser02"]=Class(_object)
_editor_class["liu_10_mc_BossCard4 Laser02"].init=function(self,_x,_y,x, y, a, da, i)
    self.x,self.y=_x,_y
    self.img="img_void"
    self.layer=LAYER_ENEMY_BULLET - 5
    self.group=GROUP_GHOST
    self.hide=false
    self.bound=true
    self.navi=false
    self.hp=10
    self.maxhp=10
    self.colli=true
    self._servants={}
    self._blend,self._a,self._r,self._g,self._b='',255,255,255,255
    last=New(_editor_class["liu_10_mc_BossCard4 Laser02bk"],self.x,self.y)
    _connect(self,last,0,true)
    liu_10_mc.stgenm.SetBossLaser(self, 1)
    self.rot = a
    self._dx, self._dy = x, y
    self.colli = false
    lasttask=task.New(self,function()
        for _=1,_infinite do
            if i == 0 then
                self.rot = self.rot - da
                if self.rot > -86.25 then
                    i = 1
                else
                end
            else
                self.rot = self.rot + da
                if self.rot < -93.75 then
                    i = 0
                else
                end
            end
            task._Wait(1)
        end
    end)
    lasttask=task.New(self,function()
        task._Wait(120)
        PlaySound("lazer00",0.3,self.x/256,false)
        self.colli = true
        for _=1,_infinite do
            if self.delete then break end
            task._Wait(1)
        end
        task._Wait(30)
        _del(self,false)
    end)
end
_editor_class["liu_10_mc_BossCard4 Laser02"].frame=function(self)
    self.class.base.frame(self)
    self.laser:frame()
    _set_rel_pos(self,self._dx, self._dy,self.rot,false)
end
_editor_class["liu_10_mc_BossCard4 Laser02"].render=function(self)
    self.class.base.render(self)
    self.laser:render()
end
_editor_class["liu_10_mc_BossCard4 Laser02"].del=function(self)
    if not(self.delete) then
        PreserveObject(self)
        self.delete = true
    else
    end
end
_editor_class["liu_10_mc_BossCard4 Laser02"].kill=function(self)
    if not(self.delete) then
        PreserveObject(self)
        self.delete = true
    else
    end
end
_editor_class["liu_10_mc_BossCard4 Laser02bk"]=Class(_object)
_editor_class["liu_10_mc_BossCard4 Laser02bk"].init=function(self,_x,_y)
    self.x,self.y=_x,_y
    self.img="img_void"
    self.layer=LAYER_ENEMY_BULLET - 6
    self.group=GROUP_GHOST
    self.hide=false
    self.bound=true
    self.navi=false
    self.hp=10
    self.maxhp=10
    self.colli=true
    self._servants={}
    self._blend,self._a,self._r,self._g,self._b='',255,255,255,255
    liu_10_mc.stgenm.SetBossLaser(self, 2)
    self.colli = false
    lasttask=task.New(self,function()
        task._Wait(120)
        PlaySound("lazer00",0.3,self.x/256,false)
        self.colli = true
        for _=1,_infinite do
            if self.delete then break end
            task._Wait(1)
        end
        task._Wait(30)
        _del(self,false)
    end)
end
_editor_class["liu_10_mc_BossCard4 Laser02bk"].frame=function(self)
    self.class.base.frame(self)
    self.laser:frame()
    _set_rel_pos(self,0,0,0,true)
end
_editor_class["liu_10_mc_BossCard4 Laser02bk"].render=function(self)
    self.class.base.render(self)
    self.laser:render()
end
_editor_tasks["liu_10_mc_BossCard4_at"]=function()
    return function()
        local self=task.GetSelf()
        local a1=(-90)
        local a2=(-90)
        local da=(360)
        for _=1,50 do
            liu_10_mc.bullet.ShotBulletMode(1, 0, _editor_class["liu_10_mc_BossCard4 Bullet01"], self.x - 114, self.y - 54, 0, 0, 0, 0, 0, 2, 1, 6.5, 1, a1, da)
            liu_10_mc.bullet.ShotBulletMode(1, 0, _editor_class["liu_10_mc_BossCard4 Bullet01"], self.x - 64, self.y + 80, 0, 0, 0, 0, 0, 2, 1, 6.5, 1, a1, da)
            liu_10_mc.bullet.ShotBulletMode(1, 0, _editor_class["liu_10_mc_BossCard4 Bullet01"], self.x + 114, self.y - 54, 0, 0, 0, 0, 0, 2, 1, 6.5, 1, a2, da)
            liu_10_mc.bullet.ShotBulletMode(1, 0, _editor_class["liu_10_mc_BossCard4 Bullet01"], self.x + 64, self.y + 80, 0, 0, 0, 0, 0, 2, 1, 6.5, 1, a2, da)
            da = da - 4.8
            task._Wait(3)
        end
        local i=(0)
        da = -0.6
        for _=1,_infinite do
            liu_10_mc.bullet.ShotBulletMode(1, 0, _editor_class["liu_10_mc_BossCard4 Bullet01"], self.x - 114, self.y - 54, 0, 0, 0, 0, 0, 3, 1, 6.5, 1, a1, 60)
            liu_10_mc.bullet.ShotBulletMode(1, 0, _editor_class["liu_10_mc_BossCard4 Bullet01"], self.x + 64, self.y + 80, 0, 0, 0, 0, 0, 3, 1, 6.5, 1, a1, 60)
            liu_10_mc.bullet.ShotBulletMode(1, 0, _editor_class["liu_10_mc_BossCard4 Bullet01"], self.x + 114, self.y - 54, 0, 0, 0, 0, 0, 3, 1, 6.5, 1, a2, 60)
            liu_10_mc.bullet.ShotBulletMode(1, 0, _editor_class["liu_10_mc_BossCard4 Bullet01"], self.x - 64, self.y + 80, 0, 0, 0, 0, 0, 3, 1, 6.5, 1, a2, 60)
            if i == 0 then
                a1 = a1 - da
                a2 = a2 + da
                if a1 > -70 then
                    i = 1
                else
                end
            else
                a1 = a1 + da
                a2 = a2 - da
                if a1 < -96.42 then
                    i = 0
                else
                end
            end
            task._Wait(3)
        end
    end
end
_editor_tasks["liu_10_mc_BossCard4_at2"]=function()
    return function()
        local self=task.GetSelf()
        liu_10_mc_HPWait(self, 3000 / 1.5, 2400)
        task._Wait(120)
        PlaySound("explode",0.3,self.x/256,false)
        for _=1,_infinite do
            local a=(-180)
            for _=1,8 do
                liu_10_mc.bullet.ShotBulletMode(1, 0, _editor_class["liu_10_mc_BossCard4 Bullet02"], self.x, self.y, 0, 0, 0, 0, 0, 1, 1, 2.5, 1, a, 0, {ran:Float(-180, 180) / 16, ran:Float(0, 1) * 1})
                a = a + (-25.7142885)
                task._Wait(5)
            end
            if player.y <= self.y then
                task._Wait(120)
            else
            end
            a = 0
            for _=1,8 do
                liu_10_mc.bullet.ShotBulletMode(1, 0, _editor_class["liu_10_mc_BossCard4 Bullet02"], self.x, self.y, 0, 0, 0, 0, 0, 1, 1, 2.5, 1, a, 0, {ran:Float(-180, 180) / 16, ran:Float(0, 1) * 1})
                a = a - (-25.7142885)
                task._Wait(5)
            end
            if player.y <= self.y then
                task._Wait(120)
            else
            end
        end
    end
end
_editor_tasks["liu_10_mc_BossCard4_at3"]=function()
    return function()
        local self=task.GetSelf()
        liu_10_mc_HPWait(self, 4000 / 1.5, 2400)
        PlaySound("explode",0.3,self.x/256,false)
        for _=1,_infinite do
            liu_10_mc.bullet.ShotBulletMode(0, 1, _editor_class["liu_10_mc_BossCard4 Bullet03"], self.x, self.y, 0, 0, 0, 0, 0, 3, 1, 3, 1, 0, 45)
            task._Wait(60)
        end
    end
end
_editor_tasks["liu_10_mc_BossCard4_at4"]=function()
    return function()
        local self=task.GetSelf()
        liu_10_mc_HPWait(self, 2000 / 1.5, 2400)
        PlaySound("explode",0.3,self.x/256,false)
        PlaySound("boon01",0.3,self.x/256,false)
        local a=(-90)
        local da=(-0.06669)
        last=New(_editor_class["liu_10_mc_BossCard4 Laser02"],self.x,self.y,-114, -54, a, da, 0)
        _connect(self,last,0,true)
        last=New(_editor_class["liu_10_mc_BossCard4 Laser02"],self.x,self.y,114, -54, a, da, 1)
        _connect(self,last,0,true)
        last=New(_editor_class["liu_10_mc_BossCard4 Laser02"],self.x,self.y,-64, 80, a, da, 1)
        _connect(self,last,0,true)
        last=New(_editor_class["liu_10_mc_BossCard4 Laser02"],self.x,self.y,64, 80, a, da, 0)
        _connect(self,last,0,true)
    end
end
_editor_tasks["liu_10_mc_BossCard4_at5"]=function()
    return function()
        local self=task.GetSelf()
        liu_10_mc_HPWait(self, 1000 / 1.5, 2400)
        PlaySound("explode",0.3,self.x/256,false)
        local a=(90)
        local i=(0)
        for _=1,_infinite do
            if i == 0 then
                a = a + (-9)
                if a  <= -90 then
                    i = 1
                else
                end
            else
                a = a - (-9)
                if a >= 90 then
                    i = 0
                else
                end
            end
            liu_10_mc.bullet.ShotBulletMode(0, 0, _editor_class["liu_10_mc_BossCard4 Bullet04"], self.x, self.y, 0, 0, 0, 0, 0, 1, 1, 2.5, 1, a, 0)
            task._Wait(2)
        end
    end
end
_editor_tasks["liu_10_mc_BossCard4_at6"]=function()
    return function()
        local self=task.GetSelf()
        liu_10_mc_HPWait(self, -1, 3000)
        PlaySound("explode",0.3,self.x/256,false)
        for _=1,_infinite do
            liu_10_mc.bullet.ShotBulletMode(2, 0, _editor_class["liu_10_mc_BossCard4 Bullet05"], self.x, self.y, 0, 0, 0, 0, 0, 16, 1, 3, 1, ran:Float(-180, 180), 0)
            task._Wait(20)
        end
    end
end
_editor_tasks["liu_10_mc_BossCard4_at7"]=function()
    return function()
        local self=task.GetSelf()
        liu_10_mc_HPWait(self, -1, 200)
        for _=1,_infinite do
            local x=(ran:Float(0, 1) * 128 + 64)
            local v=((x / 64) + (ran:Float(0, 1) * 0.5))
            liu_10_mc.bullet.ShotBulletMode(1, 0, _editor_class["liu_10_mc_BossCard4 Bullet06"], x, 224 - (ran:Float(0, 1) * 192), 0, 0, 0, 0, 0, 1, 1, v, 0, -90, 0)
            task._Wait(10)
            x = ran:Float(0, 1) * 128 + 64
            v = (x / 64) + (ran:Float(0, 1) * 0.5)
            x = x * -1
            liu_10_mc.bullet.ShotBulletMode(1, 0, _editor_class["liu_10_mc_BossCard4 Bullet06"], x, 224 - (ran:Float(0, 1) * 192), 0, 0, 0, 0, 0, 1, 1, v, 0, -90, 0)
            task._Wait(10)
        end
    end
end
_editor_class["liu_10_mc_BossCard4 Bullet01"]=Class(bullet)
_editor_class["liu_10_mc_BossCard4 Bullet01"].init=function(self,_x,_y)
bullet.init(self,liu_10_mc.bullet.bullet_class,COLOR_RED,true,true)
self.x,self.y=_x,_y
    PlaySound("tan00",0.3,self.x/256,false)
    liu_10_mc.bullet.BulletClassInit(self, 11, 6)
    liu_10_mc.bullet.SetBulletPreimg(self, 1, true)
end
_editor_class["liu_10_mc_BossCard4 Bullet02"]=Class(bullet)
_editor_class["liu_10_mc_BossCard4 Bullet02"].init=function(self,_x,_y,a, v)
bullet.init(self,liu_10_mc.bullet.bullet_class,COLOR_RED,true,true)
self.x,self.y=_x,_y
    PlaySound("tan00",0.3,self.x/256,false)
    liu_10_mc.bullet.BulletClassInit(self, 17, 2)
    liu_10_mc.bullet.SetBulletPreimg(self, 1, true)
    lasttask=task.New(self,function()
        for _=1,_infinite do
            if self.x < -192 then
                self.x = -384 - self.x
                SetV2(self,self._speed,180 - self._angle,true,false)
                do break end
            else
            end
            if self.x > 192 then
                self.x = 384 - self.x
                SetV2(self,self._speed,180 - self._angle,true,false)
                do break end
            else
            end
            if self.y > 224 then
                self.y = 448 - self.y
                SetV2(self,self._speed,-self._angle,true,false)
                do break end
            else
            end
            task._Wait(1)
        end
        PlaySound("kira00",0.3,self.x/256,false)
        _object.set_color(self,"mul+add",255,255,255,255)
        do
            local _beg_vv=self._speed local vv=_beg_vv local _end_vv=0 local _d_vv=(_end_vv-_beg_vv)/(1)
            for _=1,1 do
                task._Wait(1)
                SetV2(self,vv,self._angle,true,false)
                vv=vv+_d_vv
            end
        end
        SetV2(self,v,Angle(self, player) + a,true,false)
        do
            local vv=self._speed local _d_vv=(0.05)
            for _=1,60 do
                task._Wait(1)
                SetV2(self,vv,self._angle,true,false)
                vv=vv+_d_vv
            end
        end
    end)
end
_editor_class["liu_10_mc_BossCard4 Bullet02"].frame=function(self)
    self.class.base.frame(self)
end
_editor_class["liu_10_mc_BossCard4 Bullet03"]=Class(bullet)
_editor_class["liu_10_mc_BossCard4 Bullet03"].init=function(self,_x,_y)
bullet.init(self,liu_10_mc.bullet.bullet_class,COLOR_RED,true,true)
self.x,self.y=_x,_y
    PlaySound("tan00",0.3,self.x/256,false)
    _object.set_color(self,"mul+add",255,255,255,255)
    liu_10_mc.bullet.BulletClassInit(self, 26, 0)
    liu_10_mc.bullet.SetBulletPreimg(self, 1, true)
    self.omiga = -45
end
_editor_class["liu_10_mc_BossCard4 Bullet03"].frame=function(self)
    self.class.base.frame(self)
end
_editor_class["liu_10_mc_BossCard4 Bullet04"]=Class(bullet)
_editor_class["liu_10_mc_BossCard4 Bullet04"].init=function(self,_x,_y)
bullet.init(self,liu_10_mc.bullet.bullet_class,COLOR_RED,true,true)
self.x,self.y=_x,_y
    PlaySound("tan00",0.3,self.x/256,false)
    _object.set_color(self,"mul+add",255,255,255,255)
    liu_10_mc.bullet.BulletClassInit(self, 17, 3)
    liu_10_mc.bullet.SetBulletPreimg(self, 1, true)
end
_editor_class["liu_10_mc_BossCard4 Bullet04"].frame=function(self)
    self.class.base.frame(self)
end
_editor_class["liu_10_mc_BossCard4 Bullet05"]=Class(bullet)
_editor_class["liu_10_mc_BossCard4 Bullet05"].init=function(self,_x,_y)
bullet.init(self,liu_10_mc.bullet.bullet_class,COLOR_RED,true,true)
self.x,self.y=_x,_y
    PlaySound("tan00",0.3,self.x/256,false)
    liu_10_mc.bullet.BulletClassInit(self, 3, 1)
    liu_10_mc.bullet.SetBulletPreimg(self, 1, true)
end
_editor_class["liu_10_mc_BossCard4 Bullet05"].frame=function(self)
    self.class.base.frame(self)
end
_editor_class["liu_10_mc_BossCard4 Bullet06"]=Class(bullet)
_editor_class["liu_10_mc_BossCard4 Bullet06"].init=function(self,_x,_y)
bullet.init(self,liu_10_mc.bullet.bullet_class,COLOR_RED,true,true)
self.x,self.y=_x,_y
    PlaySound("tan00",0.3,self.x/256,false)
    _object.set_color(self,"mul+add",255,255,255,255)
    liu_10_mc.bullet.BulletClassInit(self, 17, 1)
    liu_10_mc.bullet.SetBulletPreimg(self, 1, true)
end
_editor_class["liu_10_mc_BossCard4 Bullet06"].frame=function(self)
    self.class.base.frame(self)
end
_editor_tasks["liu_10_mc_BossCard5ShadowL"]=function()
    return function()
        local self=task.GetSelf()
        self.shadow = true
        for _=1,_infinite do
            liu_10_mc.stgenm.CreateBossShadow(self, 2)
            task._Wait(1)
            if not self.shadow then break end
        end
    end
end
_editor_tasks["liu_10_mc_BossCard5_at"]=function(x1, y1, x2, y2)
    return function()
        local self=task.GetSelf()
        y1 = 224 - y1
        local da=(0)
        local x=(x2 - x1)
        local y=(y2 - y1)
        local px=(player.x - x1)
        local py=(player.y - y1)
        local j=((x * py) - (y * px))
        if j > 0 then
            da = -12
        else
            da = 12
        end
        x = x / 60
        y = y / 60
        local a=(-90 + (ran:Float(-180, 180) / 16))
        for _=1,61 do
            liu_10_mc.bullet.ShotBulletMode(1, 0, _editor_class["liu_10_mc_BossCard5 Bullet01"], x1, y1, 0, 0, 0, 0, 0, 1, 1, 0, 1, a, 0, {a})
            x1 = x1 + x
            y1 = y1 + y
            a = a + da
        end
    end
end
_editor_class["liu_10_mc_BossCard5 Bullet01"]=Class(bullet)
_editor_class["liu_10_mc_BossCard5 Bullet01"].init=function(self,_x,_y,a)
bullet.init(self,liu_10_mc.bullet.bullet_class,COLOR_RED,true,true)
self.x,self.y=_x,_y
    PlaySound("tan00",0.3,self.x/256,false)
    _object.set_color(self,"mul+add",255,255,255,255)
    liu_10_mc.bullet.BulletClassInit(self, 3, 6)
    liu_10_mc.bullet.SetBulletPreimg(self, 1, true)
    lasttask=task.New(self,function()
        task._Wait(160)
        PlaySound("kira00",0.1,self.x/256,false)
        do
            local vv=self._speed local _d_vv=(0.023333333)
            for _=1,60 do
                task._Wait(1)
                SetV2(self,vv,a,true,false)
                vv=vv+_d_vv
            end
        end
    end)
end
_editor_class["liu_10_mc_BossCard5 Bullet01"].frame=function(self)
    self.class.base.frame(self)
end
_editor_tasks["liu_10_mc_BossCard6_at"]=function(x, y, da, way, i)
    return function()
        local self=task.GetSelf()
        local ra, rv
        if i ~= 0 then
            ra = Angle(x, y, player.x, player.y)
        else
            ra = -90
        end
        rv = 0.6
        local list = liu_10_mc.bullet.ShotBulletMode(3, 0, _editor_class["liu_10_mc_BossCard6 Bullet01"], x, y, 0, 0, 0, 0, 0, way, 1, 1.8, 1, ran:Float(-180, 180), 0, {self.co, da, rv, ra})
        last=New(_editor_class["liu_10_mc_BossCard6_atLine"],x, y,rv, ra, list)
        _connect(self,last,0,true)
    end
end
_editor_class["liu_10_mc_BossCard6 Bullet01"]=Class(bullet)
_editor_class["liu_10_mc_BossCard6 Bullet01"].init=function(self,_x,_y,co, da, v, a)
bullet.init(self,liu_10_mc.bullet.bullet_class,COLOR_RED,true,true)
self.x,self.y=_x,_y
    _object.set_color(self,"mul+add",255,255,255,255)
    liu_10_mc.bullet.BulletClassInit(self, 10, co)
    liu_10_mc.bullet.SetBulletPreimg(self, 1, false)
    self.group = GROUP_INDES
    self.bound = false
    lasttask=task.New(self,function()
        PlaySound("kira00",0.1,self.x/256,false)
        lasttask=task.New(self,function()
            do
                local vv=self._speed local _d_vv=(-0.008333334)
                local aa=self._angle local _d_aa=(da)
                for _=1,60 do
                    task._Wait(1)
                    SetV2(self,vv,aa,true,false)
                    vv=vv+_d_vv
                    aa=aa+_d_aa
                end
            end
            do
                local aa=self._angle local _d_aa=(da / 4.8)
                for _=1,_infinite do
                    task._Wait(1)
                    SetV2(self,self._speed,aa,true,false)
                    aa=aa+_d_aa
                end
            end
        end)
        lasttask=task.New(self,function()
            for _=1,_infinite do
                task._Wait(1)
                self.x = self.x + v * cos(a)
                self.y = self.y + v * sin(a)
            end
        end)
    end)
end
_editor_class["liu_10_mc_BossCard6 Bullet01"].frame=function(self)
    self.class.base.frame(self)
    if self.ani >= 300 then
        self.group = GROUP_ENEMY_BULLET
    else
    end
    if self.ani >= 1600 then
        self.bound = true
    else
    end
end
_editor_class["liu_10_mc_BossCard6_atLine"]=Class(_object)
_editor_class["liu_10_mc_BossCard6_atLine"].init=function(self,_x,_y,v, a, list)
    self.x,self.y=_x,_y
    self.img="img_void"
    self.layer=LAYER_PLAYER_BULLET-5
    self.group=GROUP_GHOST
    self.hide=false
    self.bound=false
    self.navi=false
    self.hp=10
    self.maxhp=10
    self.colli=true
    self._servants={}
    self._blend,self._a,self._r,self._g,self._b='',255,255,255,255
    self.list = list
    self.r, self.n = 0, 48
    self.co = {48, 48, 255}
    self.alpha = 0
    lasttask=task.New(self,function()
        SetV2(self,v,a,true,false)
    end)
end
_editor_class["liu_10_mc_BossCard6_atLine"].frame=function(self)
    self.class.base.frame(self)
    local list = self.list
    for i = 1, #list do
        if not IsValid(list[i]) then
            table.remove(list, i)
        else
        end
    end
    for i = 1, #list do
        if IsValid(list[i]) then
            self.r = Dist(self.x, self.y, list[i].x, list[i].y)
            do break end
        else
        end
    end
    if #list <= 0 then
        _del(self,false)
    else
    end
    self.alpha = 0 + 192 * min(self.timer / 60, 1)
end
_editor_class["liu_10_mc_BossCard6_atLine"].render=function(self)
    local x, y = self.x, self.y
    local r, n = (self.r + 0.5), self.n
    local r2 = max(self.r - 0.5, 0)
    local a, da = 0, 360 / n
    local c = Color(self.alpha, unpack(self.co))
    SetImageState("white", "mul+add", c)
    for i = 1, n do
    	Render4V("white",
    		x + r * cos(a), y + r * sin(a), 0.5,
    		x + r * cos(a + da), y + r * sin(a + da), 0.5,
    		x + r2 * cos(a + da), y + r2 * sin(a + da), 0.5,
    		x + r2 * cos(a), y + r2 * sin(a), 0.5)
    	a = a + da
    end
    SetImageState("white", "", Color(0xFFFFFFFF))
end
_editor_class["liu_10_mc_BossCard6_atLine"].kill=function(self)
    local w = lstg.world
    if BoxCheck(self, w.l, w.r, w.b, w.t) then
        PlaySound("enep00",0.1,self.x/256,false)
        liu_10_mc.effect.CreateEnmKillEffect(self, 1)
    else
    end
end
_editor_class["liu_10_mc_BossCard6_atLine"].del=function(self)
    local w = lstg.world
    if BoxCheck(self, w.l, w.r, w.b, w.t) then
        PlaySound("enep00",0.1,self.x/256,false)
        liu_10_mc.effect.CreateEnmKillEffect(self, 1)
    else
    end
end
_editor_class["liu_10_mc_boss"]=Class(boss)
_editor_class["liu_10_mc_boss"].cards={}
_editor_class["liu_10_mc_boss"].name="Hiziri Byakuren"
_editor_class["liu_10_mc_boss"].bgm="bgm:liu_10_mc_th12_13"
_editor_class["liu_10_mc_boss"]._bg=liu_10_mc.world
_editor_class["liu_10_mc_boss"].difficulty="All"
_editor_class["liu_10_mc_boss"].init=function(self,cards)
boss.init(self,240,384,_editor_class["liu_10_mc_boss"].name,cards,New(spellcard_background),_editor_class["liu_10_mc_boss"].difficulty)
    if ext.sc_pr then
        liu_10_mc.bullet.LoadTexResouces()
        liu_10_mc.bullet.LoadBulletResouces()
        liu_10_mc.effect.LoadTexResouces()
        liu_10_mc.stgenm.LoadTexResouces()
        liu_10_mc_screen()
        liu_10_mc_Distortion_CaptureAndDraw(LAYER_BG - 2, LAYER_BG + 4)
    else
    end
    liu_10_mc.stgenm.SetBossWalkImage(self)
    liu_10_mc.effect.boss_explode(self)
    self.aura_alpha = 0
    self.aura_scale = 0
    Del(self.bg)
    self.bg = New(liu_10_mc.stgenm.cardbg)
    boss.show_aura(self,false)
    self.__disallow_100sec = true
    self._bosssys.sc_ring = nil
    last=New(_editor_class["liu_10_mc_sc_ring"],self.x,self.y,self)
    liu_10_mc.wisys.SetHitBox(self._wisys, 64, 64)
    liu_10_mc_moveLimit(self, 0, 112, 280, 64)
    if ui.lstg_weekly then
        ui.lstg_weekly.SetFlag(false, false, false)
        ui.lstg_weekly.SetEditor("liu_10_mc")
    else
    end
end
_tmp_sc=boss.dialog.New(true)
function _tmp_sc:init()
    lstg.player.dialog=false
    _dialog_can_skip=true
    self.dialog_displayer=New(dialog_displayer)
    lasttask=task.New(self,function()
        lasttask=task.New(self,_editor_tasks["liu_10_mc_movePosTime"](60, 4, 0, 112))
        task._Wait(60)
        liu_10_mc.effect.SetEffMagicsquare(self)
        liu_10_mc.effect.SetEffAura(self)
        liu_10_mc_Distortion_Apply(self, 160, LAYER_BG + 4, liu_10_mc_getColor(16748543))
    end)
end
table.insert(_editor_class["liu_10_mc_boss"].cards,_tmp_sc)
_tmp_sc=boss.card.New("",2,2,2640 / 60,(13200 - 2200) / 8 / 1.5,{0,0,0},false)
function _tmp_sc:before()
end
function _tmp_sc:init()
    lasttask=task.New(self,function()
        liu_10_mc.effect.ChangeEff(self)
        task._Wait(10)
        for _=1,_infinite do
            liu_10_mc_SetWalkIamgeState(self, 6)
            PlaySound("ch02",0.3,self.x/256,false)
            task._Wait(60)
            lasttask=task.New(self,_editor_tasks["liu_10_mc_Boss1_at1"]())
            task._Wait(60)
            lasttask=task.New(self,_editor_tasks["liu_10_mc_moveRand"](60, 4, 3))
            task._Wait(70)
            liu_10_mc_SetWalkIamgeState(self, 6)
            PlaySound("ch02",0.3,self.x/256,false)
            task._Wait(60)
            lasttask=task.New(self,_editor_tasks["liu_10_mc_Boss1_at1b"]())
            task._Wait(60)
            lasttask=task.New(self,_editor_tasks["liu_10_mc_moveRand"](60, 4, 3))
            task._Wait(70)
        end
    end)
end
function _tmp_sc:beforedel()
end
function _tmp_sc:del()
end
function _tmp_sc:after()
end
_tmp_sc.perform=true
table.insert(_editor_class["liu_10_mc_boss"].cards,_tmp_sc)

_tmp_sc=boss.dialog.New(true)
function _tmp_sc:init()
    lstg.player.dialog=false
    _dialog_can_skip=true
    self.dialog_displayer=New(dialog_displayer)
    lasttask=task.New(self,function()
        if ext.sc_pr then
            lasttask=task.New(self,_editor_tasks["liu_10_mc_movePosTime"](60, 4, 0, 112))
            task._Wait(60)
            liu_10_mc.effect.SetEffMagicsquare(self)
            liu_10_mc.effect.SetEffAura(self)
            liu_10_mc_Distortion_Apply(self, 160, LAYER_BG + 4, liu_10_mc_getColor(16748543))
        else
        end
    end)
end
table.insert(_editor_class["liu_10_mc_boss"].cards,_tmp_sc)
_tmp_sc=boss.card.New("吉兆「极乐的紫色云路」",2,2,2100 / 60,2200 / 1.5,{0,0,0},false)
function _tmp_sc:before()
end
function _tmp_sc:init()
    lasttask=task.New(self,function()
        last=New(_editor_class["liu_10_mc_scpic"],self.x,self.y)
        lasttask=task.New(self,_editor_tasks["liu_10_mc_movePosTime"](64, 4, 0, 64))
        liu_10_mc_moveLimit(self, 0, 96, 200, 64)
        task._Wait(60)
        liu_10_mc.effect.ChangeEff(self)
        task._Wait(60)
        lasttask=task.New(self,_editor_tasks["liu_10_mc_movePosTime"](200, 4, 0, 96))
        for _=1,_infinite do
            lasttask=task.New(self,_editor_tasks["liu_10_mc_BossCard1_at1"]())
            lasttask=task.New(self,_editor_tasks["liu_10_mc_BossCard1_at2"]())
            lasttask=task.New(self,_editor_tasks["liu_10_mc_BossCard1_at1h"]())
            lasttask=task.New(self,_editor_tasks["liu_10_mc_BossCard1_at2h"]())
            task._Wait(230)
            lasttask=task.New(self,_editor_tasks["liu_10_mc_moveRand"](60, 4, 3))
            task._Wait(70)
        end
    end)
end
function _tmp_sc:beforedel()
end
function _tmp_sc:del()
end
function _tmp_sc:after()
end
_tmp_sc.perform=true
table.insert(_editor_class["liu_10_mc_boss"].cards,_tmp_sc)
table.insert(_sc_table,{"liu_10_mc_boss","吉兆「极乐的紫色云路」",_tmp_sc,#_editor_class["liu_10_mc_boss"].cards,true})
_tmp_sc=boss.dialog.New(true)
function _tmp_sc:init()
    lstg.player.dialog=false
    _dialog_can_skip=true
    self.dialog_displayer=New(dialog_displayer)
    lasttask=task.New(self,function()
        if ext.sc_pr then
            lasttask=task.New(self,_editor_tasks["liu_10_mc_movePosTime"](60, 4, 0, 112))
            task._Wait(60)
            liu_10_mc.effect.SetEffMagicsquare(self)
            liu_10_mc.effect.SetEffAura(self)
            liu_10_mc_Distortion_Apply(self, 160, LAYER_BG + 4, liu_10_mc_getColor(16748543))
        else
        end
    end)
end
table.insert(_editor_class["liu_10_mc_boss"].cards,_tmp_sc)
_tmp_sc=boss.card.New("",2,2,2640 / 60,(12400 - 2400) / 8 / 1.5,{0,0,0},false)
function _tmp_sc:before()
end
function _tmp_sc:init()
    lasttask=task.New(self,function()
        liu_10_mc_moveLimit(self, 0, 112, 280, 64)
        lasttask=task.New(self,_editor_tasks["liu_10_mc_movePosTime"](60, 0, 0, 96))
        task._Wait(90)
        liu_10_mc.effect.ChangeEff(self)
        PlaySound("ch02",0.3,self.x/256,false)
        task._Wait(90)
        PlaySound("boon01",0.3,self.x/256,false)
        liu_10_mc.stgenm.CreateBossEyes(self)
        lasttask=task.New(self,_editor_tasks["liu_10_mc_BossEyes"]())
        task._Wait(60)
        PlaySound("explode",0.3,self.x/256,false)
        lasttask=task.New(self,_editor_tasks["liu_10_mc_Boss2_at2"]())
        task._Wait(20)
        for _=1,_infinite do
            PlaySound("ch02",0.3,self.x/256,false)
            task._Wait(60)
            lasttask=task.New(self,_editor_tasks["liu_10_mc_Boss2_at1"]())
            task._Wait(20)
            lasttask=task.New(self,_editor_tasks["liu_10_mc_Boss2_at1h"](-5.625))
            task._Wait(20)
            lasttask=task.New(self,_editor_tasks["liu_10_mc_Boss2_at1h"](-5.625))
            task._Wait(20)
            lasttask=task.New(self,_editor_tasks["liu_10_mc_Boss2_at1h"](-7.5))
            task._Wait(20)
            lasttask=task.New(self,_editor_tasks["liu_10_mc_Boss2_at1h"](-7.5))
            task._Wait(60)
        end
    end)
end
function _tmp_sc:beforedel()
end
function _tmp_sc:del()
end
function _tmp_sc:after()
end
_tmp_sc.perform=true
table.insert(_editor_class["liu_10_mc_boss"].cards,_tmp_sc)

_tmp_sc=boss.dialog.New(true)
function _tmp_sc:init()
    lstg.player.dialog=false
    _dialog_can_skip=true
    self.dialog_displayer=New(dialog_displayer)
    lasttask=task.New(self,function()
        if ext.sc_pr then
            lasttask=task.New(self,_editor_tasks["liu_10_mc_movePosTime"](60, 4, 0, 112))
            task._Wait(60)
            liu_10_mc.effect.SetEffMagicsquare(self)
            liu_10_mc.effect.SetEffAura(self)
            liu_10_mc_Distortion_Apply(self, 160, LAYER_BG + 4, liu_10_mc_getColor(16748543))
            PlaySound("boon01",0.3,self.x/256,false)
            liu_10_mc.stgenm.CreateBossEyes(self)
        else
        end
    end)
end
table.insert(_editor_class["liu_10_mc_boss"].cards,_tmp_sc)
_tmp_sc=boss.card.New("魔法「Magic Butterfly」（魔法之蝶）",2,2,2700 / 60,2400 / 1.5,{0,0,0},false)
function _tmp_sc:before()
end
function _tmp_sc:init()
    lasttask=task.New(self,function()
        last=New(_editor_class["liu_10_mc_scpic"],self.x,self.y)
        lasttask=task.New(self,_editor_tasks["liu_10_mc_movePosTime"](60, 4, 0, 32))
        liu_10_mc.effect.ChangeEff(self)
        task._Wait(60)
        task._Wait(30)
        lasttask=task.New(self,_editor_tasks["liu_10_mc_BossEyes2"]())
        for _=1,_infinite do
            task._Wait(90)
            lasttask=task.New(self,_editor_tasks["liu_10_mc_BossCard2_at2"]())
        end
    end)
end
function _tmp_sc:beforedel()
end
function _tmp_sc:del()
end
function _tmp_sc:after()
end
_tmp_sc.perform=true
table.insert(_editor_class["liu_10_mc_boss"].cards,_tmp_sc)
table.insert(_sc_table,{"liu_10_mc_boss","魔法「Magic Butterfly」（魔法之蝶）",_tmp_sc,#_editor_class["liu_10_mc_boss"].cards,true})
_tmp_sc=boss.dialog.New(true)
function _tmp_sc:init()
    lstg.player.dialog=false
    _dialog_can_skip=true
    self.dialog_displayer=New(dialog_displayer)
    lasttask=task.New(self,function()
        if ext.sc_pr then
            lasttask=task.New(self,_editor_tasks["liu_10_mc_movePosTime"](60, 4, 0, 112))
            task._Wait(60)
            liu_10_mc.effect.SetEffMagicsquare(self)
            liu_10_mc.effect.SetEffAura(self)
            liu_10_mc_Distortion_Apply(self, 160, LAYER_BG + 4, liu_10_mc_getColor(16748543))
        else
            liu_10_mc.stgenm.DeleteBossEyes(self)
        end
    end)
end
table.insert(_editor_class["liu_10_mc_boss"].cards,_tmp_sc)
_tmp_sc=boss.card.New("",2,2,2700 / 60,(12500 - 2500) / 8 / 1.5,{0,0,0},false)
function _tmp_sc:before()
end
function _tmp_sc:init()
    lasttask=task.New(self,function()
        task._Wait(120)
        PlaySound("boon01",0.3,self.x/256,false)
        liu_10_mc.stgenm.CreateBossEyes(self)
        lasttask=task.New(self,_editor_tasks["liu_10_mc_BossEyes"]())
        lasttask=task.New(self,_editor_tasks["liu_10_mc_movePosTime"](60, 0, 0, 96))
        task._Wait(60)
        PlaySound("explode",0.3,self.x/256,false)
        liu_10_mc_moveLimit(self, 0, 128, 144, 48)
        liu_10_mc_SetWalkIamgeState(self, 6)
        liu_10_mc.effect.ChangeEff(self)
        PlaySound("ch02",0.3,self.x/256,false)
        task._Wait(60)
        for _=1,_infinite do
            task._Wait(20)
            lasttask=task.New(self,_editor_tasks["liu_10_mc_Boss3_at1"]())
            lasttask=task.New(self,_editor_tasks["liu_10_mc_Boss3_at1e1"]())
            lasttask=task.New(self,_editor_tasks["liu_10_mc_Boss3_at1e2"]())
            lasttask=task.New(self,_editor_tasks["liu_10_mc_Boss3_at1e3"]())
            lasttask=task.New(self,_editor_tasks["liu_10_mc_Boss3_at1e4"]())
            lasttask=task.New(self,_editor_tasks["liu_10_mc_moveRand"](60, 4, 0.5))
            task._Wait(80)
        end
    end)
end
function _tmp_sc:beforedel()
end
function _tmp_sc:del()
end
function _tmp_sc:after()
end
_tmp_sc.perform=true
table.insert(_editor_class["liu_10_mc_boss"].cards,_tmp_sc)

_tmp_sc=boss.dialog.New(true)
function _tmp_sc:init()
    lstg.player.dialog=false
    _dialog_can_skip=true
    self.dialog_displayer=New(dialog_displayer)
    lasttask=task.New(self,function()
        if ext.sc_pr then
            lasttask=task.New(self,_editor_tasks["liu_10_mc_movePosTime"](60, 4, 0, 112))
            task._Wait(60)
            liu_10_mc.effect.SetEffMagicsquare(self)
            liu_10_mc.effect.SetEffAura(self)
            liu_10_mc_Distortion_Apply(self, 160, LAYER_BG + 4, liu_10_mc_getColor(16748543))
            PlaySound("boon01",0.3,self.x/256,false)
            liu_10_mc.stgenm.CreateBossEyes(self)
        else
        end
    end)
end
table.insert(_editor_class["liu_10_mc_boss"].cards,_tmp_sc)
_tmp_sc=boss.card.New("光魔「魔法银河系」",2,2,3000 / 60,2500 / 1.5,{0,0,0},false)
function _tmp_sc:before()
end
function _tmp_sc:init()
    lasttask=task.New(self,_editor_tasks["liu_10_mc_BossEyes"]())
    lasttask=task.New(self,function()
        last=New(_editor_class["liu_10_mc_scpic"],self.x,self.y)
        lasttask=task.New(self,_editor_tasks["liu_10_mc_movePosTime"](60, 4, 0, 32))
        task._Wait(60)
        liu_10_mc.effect.ChangeEff(self)
        task._Wait(60)
        liu_10_mc_SetWalkIamgeState(self, 6)
        lasttask=task.New(self,_editor_tasks["liu_10_mc_BossCard3_at"]())
        lasttask=task.New(self,_editor_tasks["liu_10_mc_BossCard3_at2"]())
        lasttask=task.New(self,_editor_tasks["liu_10_mc_BossCard3_at2b"]())
    end)
end
function _tmp_sc:beforedel()
end
function _tmp_sc:del()
end
function _tmp_sc:after()
end
_tmp_sc.perform=true
table.insert(_editor_class["liu_10_mc_boss"].cards,_tmp_sc)
table.insert(_sc_table,{"liu_10_mc_boss","光魔「魔法银河系」",_tmp_sc,#_editor_class["liu_10_mc_boss"].cards,true})
_tmp_sc=boss.dialog.New(true)
function _tmp_sc:init()
    lstg.player.dialog=false
    _dialog_can_skip=true
    self.dialog_displayer=New(dialog_displayer)
    lasttask=task.New(self,function()
        if ext.sc_pr then
            lasttask=task.New(self,_editor_tasks["liu_10_mc_movePosTime"](60, 4, 0, 112))
            task._Wait(60)
            liu_10_mc.effect.SetEffMagicsquare(self)
            liu_10_mc.effect.SetEffAura(self)
            liu_10_mc_Distortion_Apply(self, 160, LAYER_BG + 4, liu_10_mc_getColor(16748543))
        else
            liu_10_mc.stgenm.DeleteBossEyes(self)
        end
    end)
end
table.insert(_editor_class["liu_10_mc_boss"].cards,_tmp_sc)
_tmp_sc=boss.card.New("",2,2,4200 / 60,(22000 - 5000) / 8 / 1.5,{0,0,0},false)
function _tmp_sc:before()
end
function _tmp_sc:init()
    lasttask=task.New(self,function()
        task._Wait(120)
        PlaySound("boon01",0.3,self.x/256,false)
        liu_10_mc.stgenm.CreateBossEyes(self)
        lasttask=task.New(self,_editor_tasks["liu_10_mc_BossEyes"]())
        lasttask=task.New(self,_editor_tasks["liu_10_mc_movePosTime"](60, 0, 0, 128))
        task._Wait(60)
        PlaySound("explode",0.3,self.x/256,false)
        liu_10_mc_moveLimit(self, 0, 128, 144, 48)
        liu_10_mc_SetWalkIamgeState(self, 6, true)
        liu_10_mc.effect.ChangeEff(self)
        PlaySound("ch02",0.3,self.x/256,false)
        task._Wait(60)
        self.cx, self.cy, self.ra, self.rda, self.r, self.dr = 0, 0, 90, 0, 128, 0
        lasttask=task.New(self,function()
            for _=1,_infinite do
                self.x = self.cx + self.r * cos(self.ra)
                self.y = self.cy + self.r * sin(self.ra)
                self.ra = self.ra + self.rda
                self.r = self.r + self.dr
                task._Wait(1)
            end
        end)
        for _=1,2 do
            lasttask=task.New(self,_editor_tasks["liu_10_mc_Boss4_at1e3"]())
            task._Wait(40)
            lasttask=task.New(self,_editor_tasks["liu_10_mc_Boss4_at1e2"]())
            task._Wait(40)
            lasttask=task.New(self,_editor_tasks["liu_10_mc_Boss4_at1e4"]())
            task._Wait(40)
            lasttask=task.New(self,_editor_tasks["liu_10_mc_Boss4_at1e1"]())
            task._Wait(40)
        end
        liu_10_mc_SetWalkIamgeState(self, 1)
        lasttask=task.New(self,function()
            do
                local _beg_da=self.rda local da=_beg_da local _end_da=-0.45 local _d_da=(_end_da-_beg_da)/(60)
                for _=1,60 do
                    task._Wait(1)
                    self.rda = da
                    da=da+_d_da
                end
            end
        end)
        for _=1,_infinite do
            lasttask=task.New(self,_editor_tasks["liu_10_mc_Boss4_at1e3"]())
            task._Wait(40)
            lasttask=task.New(self,_editor_tasks["liu_10_mc_Boss4_at1e2"]())
            task._Wait(40)
            lasttask=task.New(self,_editor_tasks["liu_10_mc_Boss4_at1e4"]())
            task._Wait(40)
            lasttask=task.New(self,_editor_tasks["liu_10_mc_Boss4_at1e1"]())
            task._Wait(40)
        end
    end)
end
function _tmp_sc:beforedel()
end
function _tmp_sc:del()
end
function _tmp_sc:after()
end
_tmp_sc.perform=true
table.insert(_editor_class["liu_10_mc_boss"].cards,_tmp_sc)

_tmp_sc=boss.dialog.New(true)
function _tmp_sc:init()
    lstg.player.dialog=false
    _dialog_can_skip=true
    self.dialog_displayer=New(dialog_displayer)
    lasttask=task.New(self,function()
        if ext.sc_pr then
            lasttask=task.New(self,_editor_tasks["liu_10_mc_movePosTime"](60, 4, 0, 112))
            task._Wait(60)
            liu_10_mc.effect.SetEffMagicsquare(self)
            liu_10_mc.effect.SetEffAura(self)
            liu_10_mc_Distortion_Apply(self, 160, LAYER_BG + 4, liu_10_mc_getColor(16748543))
            PlaySound("boon01",0.3,self.x/256,false)
            liu_10_mc.stgenm.CreateBossEyes(self)
        else
        end
    end)
end
table.insert(_editor_class["liu_10_mc_boss"].cards,_tmp_sc)
_tmp_sc=boss.card.New("大魔法「魔神复诵」",2,2,4200 / 60,5000 / 1.5,{0,0,0},false)
function _tmp_sc:before()
end
function _tmp_sc:init()
    lasttask=task.New(self,_editor_tasks["liu_10_mc_BossEyes"]())
    lasttask=task.New(self,function()
        last=New(_editor_class["liu_10_mc_scpic"],self.x,self.y)
        lasttask=task.New(self,_editor_tasks["liu_10_mc_movePosTime"](60, 4, 0, 0))
        task._Wait(60)
        liu_10_mc.effect.ChangeEff(self)
        task._Wait(60)
        liu_10_mc_SetWalkIamgeState(self, 6)
        misc.ShakeScreen(120,1)
        PlaySound("boon01",0.3,self.x/256,false)
        last=New(_editor_class["liu_10_mc_BossCard4 Laser01"],self.x,self.y,-114, -54, -90)
        _connect(self,last,0,true)
        last=New(_editor_class["liu_10_mc_BossCard4 Laser01"],self.x,self.y,114, -54, -90)
        _connect(self,last,0,true)
        last=New(_editor_class["liu_10_mc_BossCard4 Laser01"],self.x,self.y,-64, 80, -90)
        _connect(self,last,0,true)
        last=New(_editor_class["liu_10_mc_BossCard4 Laser01"],self.x,self.y,64, 80, -90)
        _connect(self,last,0,true)
        task._Wait(120)
        PlaySound("se:liu_10_mc_se_ufo",1,self.x/256,false)
        misc.ShakeScreen(60,4)
        lasttask=task.New(self,_editor_tasks["liu_10_mc_movePosTime"](60, 4, 0, 96))
        lasttask=task.New(self,_editor_tasks["liu_10_mc_BossCard4_at"]())
        lasttask=task.New(self,_editor_tasks["liu_10_mc_BossCard4_at2"]())
        lasttask=task.New(self,_editor_tasks["liu_10_mc_BossCard4_at3"]())
        lasttask=task.New(self,_editor_tasks["liu_10_mc_BossCard4_at4"]())
        lasttask=task.New(self,_editor_tasks["liu_10_mc_BossCard4_at5"]())
        lasttask=task.New(self,_editor_tasks["liu_10_mc_BossCard4_at6"]())
        lasttask=task.New(self,_editor_tasks["liu_10_mc_BossCard4_at7"]())
    end)
end
function _tmp_sc:beforedel()
end
function _tmp_sc:del()
end
function _tmp_sc:after()
end
_tmp_sc.perform=true
table.insert(_editor_class["liu_10_mc_boss"].cards,_tmp_sc)
table.insert(_sc_table,{"liu_10_mc_boss","大魔法「魔神复诵」",_tmp_sc,#_editor_class["liu_10_mc_boss"].cards,true})
_tmp_sc=boss.dialog.New(true)
function _tmp_sc:init()
    lstg.player.dialog=false
    _dialog_can_skip=true
    self.dialog_displayer=New(dialog_displayer)
    lasttask=task.New(self,function()
        if ext.sc_pr then
            lasttask=task.New(self,_editor_tasks["liu_10_mc_movePosTime"](60, 4, 0, 112))
            task._Wait(60)
            liu_10_mc.effect.SetEffMagicsquare(self)
            liu_10_mc.effect.SetEffAura(self)
            liu_10_mc_Distortion_Apply(self, 160, LAYER_BG + 4, liu_10_mc_getColor(16748543))
        else
            liu_10_mc.stgenm.DeleteBossEyes(self)
            lasttask=task.New(self,_editor_tasks["liu_10_mc_movePosTime"](60, 0, 0, 96))
            task._Wait(120)
        end
        liu_10_mc_moveLimit(self, 0, 112, 280, 64)
    end)
end
table.insert(_editor_class["liu_10_mc_boss"].cards,_tmp_sc)
_tmp_sc=boss.card.New("超人「圣白莲」",2,2,4800 / 60,1800 / 1.5,{0,0,0},false)
function _tmp_sc:before()
end
function _tmp_sc:init()
    lasttask=task.New(self,function()
        last=New(_editor_class["liu_10_mc_scpic"],self.x,self.y)
        lasttask=task.New(self,_editor_tasks["liu_10_mc_movePosTime"](120, 4, 160, 96))
        local x=(0)
        local y=(32)
        task._Wait(120)
        for _=1,_infinite do
            liu_10_mc.effect.ChangeEff(self)
            PlaySound("ch02",0.3,self.x/256,false)
            liu_10_mc_SetWalkIamgeState(self, 6)
            task._Wait(60)
            x, y = -160, 64
            local t=(26)
            for _=1,8 do
                lasttask=task.New(self,_editor_tasks["liu_10_mc_BossCard5ShadowL"]())
                PlaySound("boon00",0.3,self.x/256,false)
                local sx=(self.x)
                local sy=(self.y)
                lasttask=task.New(self,_editor_tasks["liu_10_mc_movePosTime"](t, 4, x, 224 - y))
                task._Wait(t)
                lasttask=task.New(self,_editor_tasks["liu_10_mc_BossCard5_at"](x, y, sx, sy))
                if t > 10 then
                    t = t - 10
                else
                end
                x, y = x * (-1), y + 32
                self.shadow = false
            end
            task._Wait(30)
            liu_10_mc.effect.ChangeEff(self)
            PlaySound("ch02",0.3,self.x/256,false)
            liu_10_mc_SetWalkIamgeState(self, 6)
            task._Wait(60)
            x, y = 128, 64
            local t=(26)
            for _=1,8 do
                lasttask=task.New(self,_editor_tasks["liu_10_mc_BossCard5ShadowL"]())
                PlaySound("boon00",0.3,self.x/256,false)
                local sx=(self.x)
                local sy=(self.y)
                lasttask=task.New(self,_editor_tasks["liu_10_mc_movePosTime"](t, 4, x, 224 - y))
                task._Wait(t)
                lasttask=task.New(self,_editor_tasks["liu_10_mc_BossCard5_at"](x, y, sx, sy))
                if t > 10 then
                    t = t - 10
                else
                end
                if y == 64 then
                    y = 320
                else
                    y = 64
                end
                x = x - 42
                self.shadow = false
            end
            task._Wait(30)
            liu_10_mc.effect.ChangeEff(self)
            PlaySound("ch02",0.3,self.x/256,false)
            liu_10_mc_SetWalkIamgeState(self, 6)
            task._Wait(60)
            x, y = 160, 288
            local t=(26)
            for _=1,8 do
                lasttask=task.New(self,_editor_tasks["liu_10_mc_BossCard5ShadowL"]())
                PlaySound("boon00",0.3,self.x/256,false)
                local sx=(self.x)
                local sy=(self.y)
                lasttask=task.New(self,_editor_tasks["liu_10_mc_movePosTime"](t, 4, x, 224 - y))
                task._Wait(t)
                lasttask=task.New(self,_editor_tasks["liu_10_mc_BossCard5_at"](x, y, sx, sy))
                if t > 10 then
                    t = t - 10
                else
                end
                x, y = x * (-1), y - 32
                self.shadow = false
            end
            task._Wait(30)
            liu_10_mc.effect.ChangeEff(self)
            PlaySound("ch02",0.3,self.x/256,false)
            liu_10_mc_SetWalkIamgeState(self, 6)
            task._Wait(60)
            x, y = -128, 320
            local t=(26)
            for _=1,8 do
                lasttask=task.New(self,_editor_tasks["liu_10_mc_BossCard5ShadowL"]())
                PlaySound("tan00",0.3,self.x/256,false)
                PlaySound("boon00",0.3,self.x/256,false)
                local sx=(self.x)
                local sy=(self.y)
                lasttask=task.New(self,_editor_tasks["liu_10_mc_movePosTime"](t, 4, x, 224 - y))
                task._Wait(t)
                lasttask=task.New(self,_editor_tasks["liu_10_mc_BossCard5_at"](x, y, sx, sy))
                if t > 10 then
                    t = t - 10
                else
                end
                if y == 64 then
                    y = 320
                else
                    y = 64
                end
                x = x + 42
                self.shadow = false
            end
            task._Wait(30)
        end
    end)
end
function _tmp_sc:beforedel()
end
function _tmp_sc:del()
end
function _tmp_sc:after()
end
_tmp_sc.perform=true
table.insert(_editor_class["liu_10_mc_boss"].cards,_tmp_sc)
table.insert(_sc_table,{"liu_10_mc_boss","超人「圣白莲」",_tmp_sc,#_editor_class["liu_10_mc_boss"].cards,true})
_tmp_sc=boss.dialog.New(true)
function _tmp_sc:init()
    lstg.player.dialog=false
    _dialog_can_skip=true
    self.dialog_displayer=New(dialog_displayer)
    lasttask=task.New(self,function()
        if ext.sc_pr then
            lasttask=task.New(self,_editor_tasks["liu_10_mc_movePosTime"](60, 4, 0, 112))
            task._Wait(60)
            liu_10_mc.effect.SetEffMagicsquare(self)
            liu_10_mc.effect.SetEffAura(self)
            liu_10_mc_Distortion_Apply(self, 160, LAYER_BG + 4, liu_10_mc_getColor(16748543))
        else
            liu_10_mc.stgenm.DeleteBossEyes(self)
            lasttask=task.New(self,_editor_tasks["liu_10_mc_movePosTime"](60, 0, 0, 96))
            task._Wait(120)
        end
        liu_10_mc_moveLimit(self, 0, 112, 280, 64)
    end)
end
table.insert(_editor_class["liu_10_mc_boss"].cards,_tmp_sc)
--[[ 1
]]
_tmp_sc=boss.card.New("飞钵「传说的飞空圆盘」",2,2,7200 / 60,7000 / 1.5,{0,0,0},true)
function _tmp_sc:before()
    ui.lstg_weekly.SetFlag(true, false, false)
    ui.lstg_weekly.SetEditor("liu_10_mc")
end
function _tmp_sc:init()
    lasttask=task.New(self,function()
        last=New(_editor_class["liu_10_mc_scpic"],self.x,self.y)
        lasttask=task.New(self,_editor_tasks["liu_10_mc_movePosTime"](60, 4, 0, 96))
        task._Wait(60)
        PlaySound("boon01",0.3,self.x/256,false)
        liu_10_mc.stgenm.CreateBossEyes(self)
        lasttask=task.New(self,_editor_tasks["liu_10_mc_BossEyes"]())
        task._Wait(60)
        PlaySound("explode",0.3,self.x/256,false)
        liu_10_mc.wisys.SetHitBox(self._wisys, 80, 80)
        local t = 300
        local way = 24
        local i = 0
        local max_t = 7200
        local j = 0
        local k = 0
        local m = 1
        self.co = 6
        for _=1,_infinite do
            max_t = max_t - t
            print(max_t)
            da = -1.8
            if j == 0 then
                lasttask=task.New(self,_editor_tasks["liu_10_mc_BossCard6_at"](self.x - 114, self.y - 54, 0 - da, way, k))
                lasttask=task.New(self,_editor_tasks["liu_10_mc_BossCard6_at"](self.x + 114, self.y - 54, da, way, k))
                lasttask=task.New(self,_editor_tasks["liu_10_mc_BossCard6_at"](self.x - 64, self.y + 80, da, way, k))
                lasttask=task.New(self,_editor_tasks["liu_10_mc_BossCard6_at"](self.x + 64, self.y + 80, 0 - da, way, k))
                j = 1
                k = 1 - k
            else
                lasttask=task.New(self,_editor_tasks["liu_10_mc_BossCard6_at"](self.x - 114, self.y - 54, da, way, k))
                lasttask=task.New(self,_editor_tasks["liu_10_mc_BossCard6_at"](self.x + 114, self.y - 54, 0 - da, way, k))
                lasttask=task.New(self,_editor_tasks["liu_10_mc_BossCard6_at"](self.x - 64, self.y + 80, 0 - da, way, k))
                lasttask=task.New(self,_editor_tasks["liu_10_mc_BossCard6_at"](self.x + 64, self.y + 80, da, way, k))
                j = 0
            end
            task._Wait(t)
            if i == 0 then
                if self.hp < 5000 / 1.5 then
                    t = 250
                    way = 24
                    PlaySound("explode",0.1,self.x/256,false)
                    i = 1
                    self.co = 8
                else
                end
            elseif i == 1 then
                if self.hp < 4000 / 1.5 then
                    t = 230
                    way = 26
                    PlaySound("explode",0.1,self.x/256,false)
                    i = 2
                    self.co = 13
                else
                end
            elseif i == 2 then
                if self.hp < 3000 / 1.5 then
                    t = 200
                    way = 28
                    PlaySound("explode",0.1,self.x/256,false)
                    i = 3
                    self.co = 4
                else
                end
            elseif i == 3 then
                if self.hp < 2000 / 1.5 then
                    t = 150
                    way = 30
                    PlaySound("explode",0.1,self.x/256,false)
                    i = 4
                    self.co = 2
                else
                end
            else
            end
            if i ~= 5 then
                if max_t < 2160 then
                    t = 150
                    way = 32
                    PlaySound("explode",0.1,self.x/256,false)
                    self.co = 2
                    i = 5
                else
                end
            else
            end
        end
    end)
end
function _tmp_sc:beforedel()
end
function _tmp_sc:del()
end
function _tmp_sc:after()
end
_tmp_sc.perform=true
table.insert(_editor_class["liu_10_mc_boss"].cards,_tmp_sc)
table.insert(_sc_table,{"liu_10_mc_boss","飞钵「传说的飞空圆盘」",_tmp_sc,#_editor_class["liu_10_mc_boss"].cards,true})
stage.group.AddStage(__WEEK_ID,'liu_10_mc@'..__WEEK_ID,{lifeleft=7,power=400,faith=50000,bomb=3},true)
stage.group.DefStageFunc('liu_10_mc@'..__WEEK_ID,'init',function(self)
    _init_item(self)
    difficulty=self.group.difficulty
    New(mask_fader,'open')
    if jstg then jstg.CreatePlayers() else New(_G[lstg.var.player_name]) end
    lasttask=task.New(self,function()
        liu_10_mc.bullet.LoadTexResouces()
        liu_10_mc.bullet.LoadBulletResouces()
        liu_10_mc.effect.LoadTexResouces()
        liu_10_mc.stgenm.LoadTexResouces()
        liu_10_mc_screen()
        liu_10_mc_Distortion_CaptureAndDraw(LAYER_BG - 2, LAYER_BG + 4)
        LoadMusicRecord("bgm:liu_10_mc_th12_13")
        _play_music("bgm:liu_10_mc_th12_13")
        New(liu_10_mc.world)
        task._Wait(60)
        local _boss_wait=true
        local _ref=New(_editor_class["liu_10_mc_boss"],_editor_class["liu_10_mc_boss"].cards)
        last=_ref
        if _boss_wait then while IsValid(_ref) do task.Wait() end end
        task._Wait(240)
    end)
    ui.lstg_weekly.stage_init(self)
    task.New(self,function()
        while coroutine.status(self.task[1])~='dead' do task.Wait() end
        stage.group.FinishReplay()
        New(mask_fader,'close')
        task.New(self,function()
            local _,bgm=EnumRes('bgm')
            for i=1,30 do
                for _,v in pairs(bgm) do
                    if GetMusicState(v)=='playing' then
                        SetBGMVolume(v,1-i/30)
                    end
                end
                task.Wait()
            end
        end)
        task.Wait(30)
        stage.group.FinishStage()
    end)
end)
