-- Generated by LuaSTG Editor Sharp
-- Mod name: 
_author = "LuaSTG User"
_mod_version = 4096
_allow_practice = true
_allow_sc_practice =true
MusicRecord('bgm:'..'koishi72_th12.8_08','koishi72_th12.8_08.ogg',0x160EA00/44100/4,0x1546700/44100/4)
_LoadImageFromFile('image:'..'koishi72_bossbg (1)','koishi72_bossbg (1).png',true,0,0,false,0)
_LoadImageFromFile('image:'..'koishi72_bossbg (2)','koishi72_bossbg (2).png',true,0,0,false,0)
_editor_class["koishi72_144th_bg"]=Class(_spellcard_background)
_editor_class["koishi72_144th_bg"].init=function(self)
    _spellcard_background.init(self)
    _spellcard_background.AddLayer(self,"image:koishi72_bossbg (2)",true,0,0,0,0,1,0,"mul+add",1,1,
        function(self)
            self.task={}
            self.a=120
        end,
        function(self)
            task.Do(self)
        end,
        function(self)
        end
    )
    _spellcard_background.AddLayer(self,"image:koishi72_bossbg (1)",false,0,0,0,0,0,0,"",2,2,
        function(self)
            self.task={}
        end,
        function(self)
            task.Do(self)
        end,
        function(self)
        end
    )
end
_editor_class["koishi72_144th_Gunlance_body"]=Class(bullet)
_editor_class["koishi72_144th_Gunlance_body"].init=function(self,_x,_y,X,Y,angle)
bullet.init(self,star_small,COLOR_RED,true,false)
self.x,self.y=_x,_y
    self.bound=false
    self.timer=11
    _object.set_color(self,"mul+add",255,255,255,255)
    lasttask=task.New(self,function()
        self.layer=-659
        for _=1,_infinite do
            _set_rel_pos(self,X,Y,angle,true)
            task._Wait(1)
        end
    end)
end
_editor_class["koishi72_144th_lianxian"]=Class(laser)
_editor_class["koishi72_144th_lianxian"].init=function(self,_x,_y,obj1,obj2)
    laser.init(self,COLOR_RED,_x,_y,0,0,0,0,12,4,0)
    
    self.bound=false
    self.layer=-660
    lasttask=task.New(self,function()
        laser._TurnOn(self,1,false,true)
    end)
    lasttask=task.New(self,function()
        for _=1,_infinite do
            task._Wait(1)
            if IsValid(obj1) and IsValid(obj2) then
                self.x=obj1.x
                self.y=obj1.y
                
                self.l2=Dist(obj1,obj2)+1
                self.rot=Angle(obj1,obj2)
            else
                _del(self,true)
            end
        end
    end)
end
_editor_class["koishi72_144th_handle"]=Class(laser)
_editor_class["koishi72_144th_handle"].init=function(self,_x,_y,X,Y)
    laser.init(self,COLOR_RED,_x,_y,0,0,60,0,8,5,0)
    
    self.bound=false
    self.layer=-660
    lasttask=task.New(self,function()
        laser._TurnOn(self,1,false,true)
    end)
    lasttask=task.New(self,function()
        for _=1,_infinite do
            _set_rel_pos(self,X,Y,0,true)
            task._Wait(1)
        end
    end)
end
_editor_class["koishi72_144th_knife"]=Class(laser)
_editor_class["koishi72_144th_knife"].init=function(self,_x,_y,X,Y)
    laser.init(self,COLOR_RED,_x,_y,0,20,32,48,10,0,0)
    laser.ChangeImage(self,2)
    self.bound=false
    self.layer=-660
    lasttask=task.New(self,function()
        laser._TurnOn(self,1,false,true)
    end)
    lasttask=task.New(self,function()
        for _=1,_infinite do
            _set_rel_pos(self,X,Y,0,true)
            task._Wait(1)
        end
    end)
end
_editor_class["koishi72_144th_Gunlance_point_mid"]=Class(_object)
_editor_class["koishi72_144th_Gunlance_point_mid"].init=function(self,_x,_y,X,Y,list)
    self.x,self.y=_x,_y
    self.img="img_void"
    self.layer=LAYER_ENEMY-5
    self.group=GROUP_GHOST
    self.hide=false
    self.bound=false
    self.navi=false
    self.hp=10
    self.maxhp=10
    self.colli=true
    self._servants={}
    self._blend,self._a,self._r,self._g,self._b='',255,255,255,255
    lasttask=task.New(self,function()
        last=New(_editor_class["koishi72_144th_Gunlance_point_up"],self.x+70,self.y,70, 0, list)
        _connect(self,last,0,true)
        last=New(_editor_class["koishi72_144th_lianxian"],self.x,self.y,self,last)
        _connect(self,last,0,true)
    end)
    lasttask=task.New(self,function()
        for _=1,60 do
            _set_rel_pos(self,X+8*cos(90),Y+6+8*sin(90),180,true)
            task._Wait(1)
        end
        PlaySound("ch02",1,self.x/256,false)
        do
            local _beg_t=90 local t=_beg_t  local _w_t=0 local _end_t=-90 local _d_w_t=90/(40-1)
            for _=1,40 do
                _set_rel_pos(self,X+8*cos(t),Y+6+8*sin(t),t+90,true)
                task._Wait(1)
                _w_t=_w_t+_d_w_t t=(_end_t-_beg_t)*sin(_w_t)+(_beg_t)
            end
        end
        for _=1,_infinite do
            for _=1,_infinite do
                _set_rel_pos(self,X,Y,0,true)
                if list.x==1 then
                    do break end
                else
                end
                task._Wait(1)
            end
            do
                local _beg_t=-90 local t=_beg_t  local _w_t=0 local _end_t=-110 local _d_w_t=90/(15-1)
                for _=1,15 do
                    _set_rel_pos(self,X+8*cos(t),Y+6+8*sin(t),t+90,true)
                    task._Wait(1)
                    _w_t=_w_t+_d_w_t t=(_end_t-_beg_t)*sin(_w_t)+(_beg_t)
                end
            end
            do
                local _beg_t=-110 local t=_beg_t  local _w_t=0 local _end_t=-90 local _d_w_t=90/(15-1)
                for _=1,15 do
                    _set_rel_pos(self,X+8*cos(t),Y+6+8*sin(t),t+90,true)
                    task._Wait(1)
                    _w_t=_w_t+_d_w_t t=(_end_t-_beg_t)*sin(_w_t)+(_beg_t)
                end
            end
            task._Wait(5)
        end
    end)
end
_editor_class["koishi72_144th_Gunlance_point_up"]=Class(_object)
_editor_class["koishi72_144th_Gunlance_point_up"].init=function(self,_x,_y,X,Y,list)
    self.x,self.y=_x,_y
    self.img="img_void"
    self.layer=LAYER_ENEMY-5
    self.group=GROUP_ENEMY_BULLET
    self.hide=false
    self.bound=false
    self.navi=false
    self.hp=10
    self.maxhp=10
    self.colli=true
    self._servants={}
    self._blend,self._a,self._r,self._g,self._b='',255,255,255,255
    lasttask=task.New(self,function()
        last=New(_editor_class["koishi72_144th_knife"],self.x-20,self.y+5,-20,5)
        _connect(self,last,0,true)
        last=New(_editor_class["koishi72_144th_Gunlance_body"],self.x-18,self.y+5,-18,5,0)
        _connect(self,last,0,true)
        last=New(_editor_class["koishi72_144th_Gunlance_body"],self.x+2,self.y,2,0,180)
        _connect(self,last,0,true)
    end)
    lasttask=task.New(self,function()
        for _=1,_infinite do
            _set_rel_pos(self,X,Y,0,true)
            task._Wait(1)
        end
    end)
    lasttask=task.New(self,function()
        for _=1,_infinite do
            for _=1,_infinite do
                task._Wait(5)
                if list.z==1 then
                    do break end
                else
                end
            end
            for _=1,6 do
                task._Wait(8)
                PlaySound("tan00",0.1,self.x/256,false)
                last=New(_editor_class["koishi72_144th_bomb_mid"],self.x,self.y)
            end
            task._Wait(60)
        end
    end)
    lasttask=task.New(self,function()
        for _=1,_infinite do
            task._Wait(120)
            for _=1,_infinite do
                task._Wait(5)
                if list.y==1 then
                    lstg.New(boss_cast_ef,0,0,100,255,0,0,40,1,ch00,self)
                    do break end
                else
                end
            end
            task._Wait(60)
            PlaySound("explode",2,self.x/256,false)
            misc.ShakeScreen(30,1)
            PlaySound("enep02",5,self.x/256,false)
            last=New(_editor_class["koishi72_144th_longhangpao"],self.x,self.y,0, self.rot)
            last=New(_editor_class["koishi72_144th_longhangpao"],self.x,self.y,180, self.rot)
        end
    end)
end
_editor_class["koishi72_144th_Gunlance_mid"]=Class(_object)
_editor_class["koishi72_144th_Gunlance_mid"].init=function(self,_x,_y,Rot,list)
    self.x,self.y=_x,_y
    self.img="img_void"
    self.layer=LAYER_ENEMY-5
    self.group=GROUP_ENEMY_BULLET
    self.hide=false
    self.bound=false
    self.navi=false
    self.hp=10
    self.maxhp=10
    self.colli=true
    self._servants={}
    self._blend,self._a,self._r,self._g,self._b='',255,255,255,255
    self.rot=-90
    lasttask=task.New(self,function()
        last=New(_editor_class["koishi72_144th_Gunlance_point_mid"],self.x,self.y,0, 0, list)
        _connect(self,last,0,true)
        last=New(_editor_class["koishi72_144th_handle"],self.x-75,self.y,-75,0)
        _connect(self,last,0,true)
    end)
    lasttask=task.New(self,function()
        do local XX,_d_XX=(-14),(7) for _=1,3 do
            do local YY,_d_YY=(-7),(7) for _=1,3 do
                last=New(_editor_class["koishi72_144th_Gunlance_body"],self.x+XX,self.y+YY,XX,YY,0)
                _connect(self,last,0,true)
            YY=YY+_d_YY end end
        XX=XX+_d_XX end end
    end)
    lasttask=task.New(self,function()
        do local XX,_d_XX,X0,_d_X0,num,_d_num=(-14-5),(-7),(-10),(-2.5),(5),(1) for _=1,3 do
            do local YY,_d_YY=(X0),(5) for _=1,num do
                last=New(_editor_class["koishi72_144th_Gunlance_body"],self.x+XX,self.y+YY,XX,YY,0)
                _connect(self,last,0,true)
            YY=YY+_d_YY end end
        XX=XX+_d_XX X0=X0+_d_X0 num=num+_d_num end end
    end)
    lasttask=task.New(self,function()
        task._Wait(60)
        do
            local _beg_Vel=2.5 local Vel=_beg_Vel  local _w_Vel=0 local _end_Vel=0 local _d_w_Vel=90/(60)
            local _beg_Ang=-90 local Ang=_beg_Ang  local _w_Ang=0 local _end_Ang=Rot+160 local _d_w_Ang=90/(60-1)
            for _=1,60 do
                self.y=self.y+1.2
                task._Wait(1)
                SetV2(self,Vel,Ang,true,false)
                _w_Vel=_w_Vel+_d_w_Vel Vel=(_end_Vel-_beg_Vel)*sin(_w_Vel)+(_beg_Vel)
                _w_Ang=_w_Ang+_d_w_Ang Ang=(_end_Ang-_beg_Ang)*sin(_w_Ang)+(_beg_Ang)
            end
        end
        for _=1,_infinite do
            local ROT0=(self.rot)
            local R=(Dist(_boss,self))
            local A=(Angle(_boss,self))
            PlaySound("slash",1.2,self.x/256,false)
            --[[ 全弹发射
            ]]
            lasttask=task.New(self,function()
                list.z=1
                task._Wait(10)
                list.z=0
            end)
            do
                local _beg_dang=0 local dang=_beg_dang  local _w_dang=-90 local _end_dang=-260 local _d_w_dang=180/(60)
                local _beg_dR=0 local dR=_beg_dR local _end_dR=30 local _d_dR=(_end_dR-_beg_dR)/(60)
                for _=1,60 do
                    task._Wait(1)
                    _set_rel_pos(self,(R+dR)*cos(A+dang),(R+dR)*sin(A+dang),ROT0+dang,false)
                    _w_dang=_w_dang+_d_w_dang dang=(_end_dang-_beg_dang)/2*sin(_w_dang)+((_end_dang+_beg_dang)/2)
                    dR=dR+_d_dR
                end
            end
            task._Wait(20)
            ROT0=self.rot
            A=Angle(_boss,player)
            lasttask=task.New(self,function()
                task._Wait(20)
                task.MoveTo(_boss.x+30*cos(A+30),_boss.y+50*sin(A+30)-5,40,MOVE_DECEL)
            end)
            do
                local _beg_Ang=self.rot local Ang=_beg_Ang  local _w_Ang=0 local _end_Ang=A local _d_w_Ang=90/(60-1)
                for _=1,60 do
                    self.rot=Ang
                    task._Wait(1)
                    _w_Ang=_w_Ang+_d_w_Ang Ang=(_end_Ang-_beg_Ang)*sin(_w_Ang)+(_beg_Ang)
                end
            end
            --[[ 炮击
            ]]
            list.y=1
            task._Wait(100)
            list.y=0
            local ROT0=(self.rot)
            local R=(Dist(_boss,self))
            local A=(Angle(_boss,self))
            do
                local _beg_dang=0 local dang=_beg_dang  local _w_dang=-90 local _end_dang=-230 local _d_w_dang=180/(60)
                local _beg_dan=(ROT0-360)%360 local dan=_beg_dan  local _w_dan=-90 local _end_dan=75 local _d_w_dan=180/(60-1)
                local _beg_dR=0 local dR=_beg_dR local _end_dR=15 local _d_dR=(_end_dR-_beg_dR)/(60)
                for _=1,60 do
                    task._Wait(1)
                    _set_rel_pos(self,(R+dR)*cos(A+dang),(R+dR)*sin(A+dang),dan,false)
                    _w_dang=_w_dang+_d_w_dang dang=(_end_dang-_beg_dang)/2*sin(_w_dang)+((_end_dang+_beg_dang)/2)
                    _w_dan=_w_dan+_d_w_dan dan=(_end_dan-_beg_dan)/2*sin(_w_dan)+((_end_dan+_beg_dan)/2)
                    dR=dR+_d_dR
                end
            end
            --[[ 换弹
            ]]
            lasttask=task.New(self,function()
                list.x=1
                task._Wait(20)
                PlaySound("ch01",2,self.x/256,false)
                task._Wait(12)
                list.x=0
            end)
            do
                local _h_YYY=(2.2-(-2.2))/2 local _t_YYY=(2.2+(-2.2))/2 local YYY=_h_YYY*sin(-90)+_t_YYY local _w_YYY=-90 local _d_w_YYY=1*360/(40-1)
                for _=1,40 do
                    self.y=self.y+YYY
                    task._Wait(1)
                    _w_YYY=_w_YYY+_d_w_YYY YYY=_h_YYY*sin(_w_YYY)+_t_YYY
                end
            end
            task._Wait(12)
            lasttask=task.New(self,function()
                list.p=1
                task._Wait(10)
                list.p=0
            end)
            local PX=(self.x-_boss.x)
            local PY=(self.y-_boss.y)
            for _=1,60 do
                task._Wait(1)
                _set_rel_pos(self,PX,PY,self.rot,false)
            end
        end
    end)
end
_editor_class["koishi72_The_mid"]=Class(_object)
_editor_class["koishi72_The_mid"].init=function(self,_x,_y)
    self.x,self.y=_x,_y
    self.img="leaf"
    self.layer=LAYER_ENEMY_BULLET
    self.group=GROUP_ENEMY_BULLET
    self.hide=false
    self.bound=true
    self.navi=false
    self.hp=10
    self.maxhp=10
    self.colli=true
    self._servants={}
    self._blend,self._a,self._r,self._g,self._b='',255,255,255,255
    self.n={}
    lasttask=task.New(self,function()
        self.rot=0
        do local num,_d_num,aaa,_d_aaa=(1),(1),(ran:Int(0,360)),(-18) for _=1,20 do
            last=New(_editor_class["koishi72_The_point"],self.x,self.y,aaa)
            self.n[num]=last
            _connect(self,last,0,true)
        num=num+_d_num aaa=aaa+_d_aaa end end
        do local i,_d_i=(1),(1) for _=1,20 do
            last=New(_editor_class["koishi72_The_connection"],self.x,self.y,self.n[i],self.n[i%20+1])
            _connect(self,last,0,true)
        i=i+_d_i end end
        task._Wait(50)
        _del(self,true)
    end)
end
_editor_class["koishi72_The_point"]=Class(_object)
_editor_class["koishi72_The_point"].init=function(self,_x,_y,Rot)
    self.x,self.y=_x,_y
    self.img="img_void"
    self.layer=LAYER_ENEMY_BULLET
    self.group=GROUP_GHOST
    self.hide=false
    self.bound=false
    self.navi=false
    self.hp=10
    self.maxhp=10
    self.colli=true
    self._servants={}
    self._blend,self._a,self._r,self._g,self._b='',255,255,255,255
    lasttask=task.New(self,function()
        do
            local _beg_radius=0 local radius=_beg_radius local _end_radius=80 local _w_radius=0  local _d_w_radius=1/(50)
            for _=1,50 do
                _set_rel_pos(self,radius*cos(Rot),radius*sin(Rot),self.rot,false)
                task._Wait(1)
                _w_radius=_w_radius+_d_w_radius radius=(_end_radius-_beg_radius)*_w_radius^2+_beg_radius
            end
        end
    end)
end
_editor_class["koishi72_The_connection"]=Class(laser)
_editor_class["koishi72_The_connection"].init=function(self,_x,_y,obj1,obj2)
    laser.init(self,COLOR_RED,_x,_y,0,0,0,0,8,0,0)
    
    self.bound=false
    lasttask=task.New(self,function()
        laser._TurnHalfOn(self,1,true)
    end)
    lasttask=task.New(self,function()
        for _=1,_infinite do
            task._Wait(1)
            if IsValid(obj1) and IsValid(obj2) then
                self.x=obj1.x
                self.y=obj1.y
                self.l2=Dist(obj1,obj2)+1
                self.rot=Angle(obj1,obj2)
            else
                _del(self,true)
            end
        end
    end)
end
_editor_class["koishi72_144th_bomb"]=Class(bullet)
_editor_class["koishi72_144th_bomb"].init=function(self,_x,_y,COLOR,Vel,Ang)
bullet.init(self,ball_mid_c,COLOR,true,true)
self.x,self.y=_x,_y
    lasttask=task.New(self,function()
        task._Wait(30)
        do
            local _beg_vic=0 local vic=_beg_vic  local _w_vic=0 local _end_vic=Vel local _d_w_vic=90/(60)
            for _=1,60 do
                SetV2(self,vic,Ang,true,false)
                task._Wait(1)
                _w_vic=_w_vic+_d_w_vic vic=(_end_vic-_beg_vic)*sin(_w_vic)+(_beg_vic)
            end
        end
    end)
end
_editor_class["koishi72_144th_bomb_mid"]=Class(_object)
_editor_class["koishi72_144th_bomb_mid"].init=function(self,_x,_y)
    self.x,self.y=_x,_y
    self.img="img_void"
    self.layer=LAYER_ENEMY_BULLET
    self.group=GROUP_ENEMY_BULLET
    self.hide=false
    self.bound=true
    self.navi=false
    self.hp=10
    self.maxhp=10
    self.colli=true
    self._servants={}
    self._blend,self._a,self._r,self._g,self._b='',255,255,255,255
    lasttask=task.New(self,function()
        do local NN,_d_NN,C,_d_C,R,_d_R,V,_d_V=(24),(-7),(12),(2),(65),(-20),(0.9),(0.6) for _=1,3 do
            do local ang,_d_ang=(ran:Int(0,360)),(360/NN) for _=1,NN do
                last=New(_editor_class["koishi72_144th_bomb"],self.x+R*cos(ang),self.y+R*sin(ang),C, V, ang+ran:Int(-36,36))
            ang=ang+_d_ang end end
        NN=NN+_d_NN C=C+_d_C R=R+_d_R V=V+_d_V end end
        task._Wait(30)
        PlaySound("tan02",0.1,self.x/256,false)
        _del(self,true)
    end)
end
_editor_class["koishi72_144th_longhangpao"]=Class(bullet)
_editor_class["koishi72_144th_longhangpao"].init=function(self,_x,_y,A,Ang)
bullet.init(self,arrow_mid,COLOR_RED,true,false)
self.x,self.y=_x,_y
    lasttask=task.New(self,function()
        do local Vic,_d_Vic=(1.6),(0.08) for _=1,_infinite do
            task._Wait(1)
            SetV2(self,Vic,Ang,true,false)
            if self.y<= -230 or self.x<=-190 or self.x>=190 then
                PlaySound("don00",3,self.x/256,false)
                SetV2(self,0,Ang,true,false)
                if A==180 then
                    misc.ShakeScreen(60,3)
                    lasttask=task.New(self,function()
                        task._Wait(180)
                        misc.ShakeScreen(60,3)
                        PlaySound("slash",3,self.x/256,false)
                        do local Num,_d_Num,Index,_d_Index,veltory0,_d_veltory0=(14),(6),(3),(-0.8),(3.5),(-0.7) for _=1,4 do
                            do local angle,_d_angle,AAA,_d_AAA=(ran:Int(0,360)),(360/Num),(ran:Sign()),(0) for _=1,Num do
                                last=New(_straight,star_big,COLOR_RED,self.x,self.y,0.3,angle,false,AAA*Index*2,true,true,0,false,0.012*Index,angle,veltory0,false)
                            angle=angle+_d_angle AAA=AAA+_d_AAA end end
                        Num=Num+_d_Num Index=Index+_d_Index veltory0=veltory0+_d_veltory0 end end
                    end)
                else
                end
                for _=1,40 do
                    task._Wait(5)
                    last=New(_straight,star_small,COLOR_RED,self.x,self.y,3+ran:Int(-5,5)*0.2,self.rot+180+ran:Int(-40,40)*0.5,false,ran:Sign()*1.8,true,true,0,false,0.04,270,0,false)
                    PlaySound("damage00",0.1,self.x/256,false)
                end
                SetV2(self,0.5,Ang,true,false)
                task._Wait(30)
                _del(self,true)
            else
            end
        Vic=Vic+_d_Vic end end
    end)
    lasttask=task.New(self,function()
        self.hscale=3
        _object.set_color(self,"mul+alpha",255,255,255,255)
        do
            local _h_HS=(2-(0))/2 local _t_HS=(2+(0))/2 local HS=_h_HS*sin(A)+_t_HS local _w_HS=A local _d_w_HS=24
            for _=1,_infinite do
                self.vscale=HS
                task._Wait(1)
                _w_HS=_w_HS+_d_w_HS HS=_h_HS*sin(_w_HS)+_t_HS
            end
        end
    end)
end
_editor_class["koishi72_144th_marisa"]=Class(boss)
_editor_class["koishi72_144th_marisa"].cards={}
_editor_class["koishi72_144th_marisa"].name="GUNLANCE"
_editor_class["koishi72_144th_marisa"].bgm="bgm:koishi72_th12.8_08"
_editor_class["koishi72_144th_marisa"]._bg=nil
_editor_class["koishi72_144th_marisa"].difficulty="All"
_editor_class["koishi72_144th_marisa"].init=function(self,cards)
boss.init(self,240,384,_editor_class["koishi72_144th_marisa"].name,cards,New(_editor_class["koishi72_144th_bg"]),_editor_class["koishi72_144th_marisa"].difficulty)
    self._wisys = BossWalkImageSystem(self)
    self._wisys:SetImage("koishi72_boss04.png",3,4,{4,4,4},{1,1},8,16,16)
    self._wisys:SetFloat(function(ani) 
           return 0, 3 * sin(ani * 3) +5
    end)
end
--[[ 2
]]
_tmp_sc=boss.card.New(" 火力「龙杭炮击」",2,10,72,600,{0,0,0},false)
function _tmp_sc:before()
    ui.lstg_weekly.SetFlag(false, true, false)
    ui.lstg_weekly.SetEditor("koishi72")
end
function _tmp_sc:init()
    local list={x=0,y=0,z=0,p=0}
    lasttask=task.New(self,function()
        task.MoveTo(0,120,60,MOVE_NORMAL)
        lstg.New(boss_cast_darkball,self.x,self.y,50,80,300,3,5,30,30,220,-2)
        task._Wait(80)
        last=New(_editor_class["koishi72_144th_Gunlance_mid"],self.x,self.y-40,Angle(self,player),list)
        _connect(self,last,0,true)
    end)
    lasttask=task.New(self,function()
        for _=1,_infinite do
            task._Wait(1)
            if list.p==1 then
                task.MoveToPlayer(40,-106,106,118,120,24,48,8,16,MOVE_NORMAL,MOVE_X_TOWARDS_PLAYER)
                task._Wait(30)
            else
            end
        end
    end)
end
function _tmp_sc:beforedel()
end
function _tmp_sc:del()
end
function _tmp_sc:after()
end
_tmp_sc.perform=false
table.insert(_editor_class["koishi72_144th_marisa"].cards,_tmp_sc)
table.insert(_sc_table,{"koishi72_144th_marisa"," 火力「龙杭炮击」",_tmp_sc,#_editor_class["koishi72_144th_marisa"].cards,false})
stage.group.AddStage(__WEEK_ID,'koishi72@'..__WEEK_ID,{lifeleft=7,power=400,faith=50000,bomb=3},true)
stage.group.DefStageFunc('koishi72@'..__WEEK_ID,'init',function(self)
    _init_item(self)
    difficulty=self.group.difficulty
    New(mask_fader,'open')
    if jstg then jstg.CreatePlayers() else New(_G[lstg.var.player_name]) end
    lasttask=task.New(self,function()
        LoadMusic('spellcard','THlib\\music\\spellcard.ogg',75,0xc36e80/44100/4)
        New(temple_background)
        task._Wait(60)
        LoadMusicRecord("bgm:koishi72_th12.8_08")
        _play_music("bgm:koishi72_th12.8_08")
        local _boss_wait=true
        local _ref=New(_editor_class["koishi72_144th_marisa"],_editor_class["koishi72_144th_marisa"].cards)
        last=_ref
        if _boss_wait then while IsValid(_ref) do task.Wait() end end
        --[[ Insert after this]]
        
        task._Wait(180)
    end)
    ui.lstg_weekly.stage_init(self)
    task.New(self,function()
        while coroutine.status(self.task[1])~='dead' do task.Wait() end
        stage.group.FinishReplay()
        New(mask_fader,'close')
        task.New(self,function()
            local _,bgm=EnumRes('bgm')
            for i=1,30 do
                for _,v in pairs(bgm) do
                    if GetMusicState(v)=='playing' then
                        SetBGMVolume(v,1-i/30)
                    end
                end
                task.Wait()
            end
        end)
        task.Wait(30)
        stage.group.FinishStage()
    end)
end)
