-- Generated by LuaSTG Editor Sharp
-- Mod name: 144th_weekend_T_Terrence
_author = "T_Terrence"
_mod_version = 4096
_allow_practice = true
_allow_sc_practice =true
MusicRecord('bgm:'..'T_Terrence_1013','T_Terrence_1013.wav',0x26A9BF8/44100/4,0x23E0504/44100/4)
_LoadImageFromFile('image:'..'T_Terrence_cdbg06b','T_Terrence_cdbg06b.png',true,0,0,false,0)
_LoadImageFromFile('image:'..'T_Terrence_cdbg06a','T_Terrence_cdbg06a.png',true,0,0,false,0)
_LoadImageFromFile('image:'..'T_Terrence_stage06e03','T_Terrence_stage06e03.png',true,0,0,false,0)
_LoadImageFromFile('image:'..'T_Terrence_stage06e03_2','T_Terrence_stage06e03_2.png',true,0,0,false,0)
_LoadImageGroupFromFile('image:'..'T_Terrence_stage06e03_3_','T_Terrence_stage06e03_3.png',true,1,2,0,0,false)
_LoadImageFromFile('image:'..'T_Terrence_stage06e03_4','T_Terrence_stage06e03_4.png',true,0,0,false,0)
_LoadImageGroupFromFile('image:'..'T_Terrence_stage06e01_','T_Terrence_stage06e01.png',true,4,4,0,0,false)
LoadSound('se:'..'T_Terrence_se_ufo','T_Terrence_se_ufo.wav')
local GROUP_BACK=8;
_editor_class["T_Terrence_Boss"]=Class(boss)
_editor_class["T_Terrence_Boss"].cards={}
_editor_class["T_Terrence_Boss"].name="Hijiri Byakuren"
_editor_class["T_Terrence_Boss"].bgm="bgm:T_Terrence_1013"
_editor_class["T_Terrence_Boss"]._bg=temple_background
_editor_class["T_Terrence_Boss"].difficulty="All"
_editor_class["T_Terrence_Boss"].init=function(self,cards)
boss.init(self,240,384,_editor_class["T_Terrence_Boss"].name,cards,New(_editor_class["T_Terrence_SpellBG"]),_editor_class["T_Terrence_Boss"].difficulty)
    self._wisys = BossWalkImageSystem(self)
    self._wisys:SetImage("T_Terrence_stage06e01.png",4,4,{4,4,4,4},{1,1,1},6,16,16)
    LoadMusicRecord("bgm:T_Terrence_1013")
    _play_music("bgm:T_Terrence_1013")
end
_tmp_sc=boss.card.New("",0,0,44,1000,{0,0,0},false)
function _tmp_sc:before()
end
function _tmp_sc:init()
    lasttask=task.New(self,function()
        local Ang=15;
        local k=1;
        task.MoveTo(0,120,60,MOVE_NORMAL)
        for _=1,_infinite do
            do local t,_d_t=(1),(1) for _=1,6 do
                do local ang,_d_ang=(Ang),(30) for _=1,12 do
                    PlaySound("tan00",0.1,self.x/256,false)
                    last=New(_straight,ball_big,COLOR_DEEP_BLUE,self.x,self.y+10,4,ang,false,0,true,true,0,false,0,0,0,false)
                    do local a,_d_a=(ang+k*(15/6)*2),((15/6)*k) for _=1,3 do
                        last=New(_straight,ball_small,COLOR_DEEP_BLUE,self.x,self.y+10,4,a,false,0,true,true,0,false,0,0,0,false)
                    a=a+_d_a end end
                    last=New(_straight,ball_huge,COLOR_DEEP_BLUE,self.x,self.y+10,4,ang-(15/6)*k,false,0,true,true,0,false,0,0,0,false)
                    last=New(_straight,ball_mid,COLOR_DEEP_BLUE,self.x,self.y+10,4,ang+(15/6)*k,false,0,true,true,0,false,0,0,0,false)
                ang=ang+_d_ang end end
                task._Wait(15)
                k=-k;
                if t%2==1 then
                    Ang=Ang+15;
                else
                end
            t=t+_d_t end end
            k=-k;
            task._Wait(60)
            task.MoveToPlayer(30,-96,96,112,144,16,32,8,16,MOVE_DECEL,MOVE_X_TOWARDS_PLAYER)
        end
    end)
end
function _tmp_sc:beforedel()
end
function _tmp_sc:del()
end
function _tmp_sc:after()
end
_tmp_sc.perform=false
table.insert(_editor_class["T_Terrence_Boss"].cards,_tmp_sc)

_tmp_sc=boss.card.New("魔法「紫云的前兆」",1,3,42,1200,{20,0,50},false)
function _tmp_sc:before()
end
function _tmp_sc:init()
    lasttask=task.New(self,function()
        task.MoveTo(0,80,60,MOVE_DECEL)
        task._Wait(60)
        for _=1,_infinite do
            lasttask=task.New(self,function()
                local initAng=ran:Float(0,360);
                local num=1;
                do
                    local _beg_Dis=40 local Dis=_beg_Dis local _end_Dis=0 local _d_Dis=(_end_Dis-_beg_Dis)/(72)
                    local _beg_ang=initAng local ang=_beg_ang local _end_ang=initAng+720 local _d_ang=(_end_ang-_beg_ang)/(72)
                    for _=1,72 do
                        do local s,_d_s,a,_d_a=(2.5),(0.5),(ang),(2) for _=1,min(num,4) do
                            last=New(_straight,water_drop,COLOR_PURPLE,self.x+Dis*cos(a),self.y+Dis*sin(a),s,a,false,0,true,true,0,false,0,0,0,false)
                            PlaySound("tan01",0.1,self.x/256,false)
                        s=s+_d_s a=a+_d_a end end
                        num=num+1
                        task._Wait(2)
                        Dis=Dis+_d_Dis
                        ang=ang+_d_ang
                    end
                end
                num=num-1;
                do
                    local _beg_Dis=0 local Dis=_beg_Dis local _end_Dis=40 local _d_Dis=(_end_Dis-_beg_Dis)/(72-1)
                    local _beg_ang=initAng local ang=_beg_ang local _end_ang=initAng+720 local _d_ang=(_end_ang-_beg_ang)/(72)
                    for _=1,72 do
                        do local s,_d_s,a,_d_a=(2.5),(0.5),(ang),(2) for _=1,min(4,num) do
                            last=New(_straight,water_drop,COLOR_PURPLE,self.x+Dis*cos(a),self.y+Dis*sin(a),s,a,false,0,true,true,0,false,0,0,0,false)
                            PlaySound("tan01",0.1,self.x/256,false)
                        s=s+_d_s a=a+_d_a end end
                        num=num-1;
                        task._Wait(1)
                        Dis=Dis+_d_Dis
                        ang=ang+_d_ang
                    end
                end
            end)
            lasttask=task.New(self,function()
                local initAng=ran:Float(0,360);
                local num=1;
                do
                    local _beg_Dis=40 local Dis=_beg_Dis local _end_Dis=20 local _d_Dis=(_end_Dis-_beg_Dis)/(36)
                    local _beg_ang=initAng local ang=_beg_ang local _end_ang=initAng+360 local _d_ang=(_end_ang-_beg_ang)/(36)
                    for _=1,36 do
                        do local s,_d_s,a,_d_a=(1),(0.25),(ang),(1) for _=1,min(num,4) do
                            last=New(_straight,kite,COLOR_PURPLE,self.x+Dis*cos(a),self.y+Dis*sin(a),s,a,false,0,true,true,0,false,0,0,0,false)
                            PlaySound("tan01",0.1,self.x/256,false)
                        s=s+_d_s a=a+_d_a end end
                        num=num+1
                        task._Wait(2)
                        Dis=Dis+_d_Dis
                        ang=ang+_d_ang
                    end
                end
                num=num-1
                do
                    local _beg_Dis=20 local Dis=_beg_Dis local _end_Dis=0 local _d_Dis=(_end_Dis-_beg_Dis)/(36-1)
                    local _beg_ang=initAng local ang=_beg_ang local _end_ang=initAng-360 local _d_ang=(_end_ang-_beg_ang)/(36-1)
                    for _=1,36 do
                        do local s,_d_s,a,_d_a=(1),(0.25),(ang),(1) for _=1,min(num,4) do
                            last=New(_straight,kite,COLOR_PURPLE,self.x+Dis*cos(a),self.y+Dis*sin(a),s,a,false,0,true,true,0,false,0,0,0,false)
                            PlaySound("tan01",0.1,self.x/256,false)
                        s=s+_d_s a=a+_d_a end end
                        num=num-1
                        task._Wait(2)
                        Dis=Dis+_d_Dis
                        ang=ang+_d_ang
                    end
                end
                num=num+1;
            end)
            task._Wait(240)
            task.MoveToPlayer(60,-96,96,70,90,16,32,8,16,MOVE_DECEL,MOVE_X_TOWARDS_PLAYER)
            task._Wait(60)
        end
    end)
end
function _tmp_sc:beforedel()
end
function _tmp_sc:del()
end
function _tmp_sc:after()
end
_tmp_sc.perform=false
table.insert(_editor_class["T_Terrence_Boss"].cards,_tmp_sc)
table.insert(_sc_table,{"T_Terrence_Boss","魔法「紫云的前兆」",_tmp_sc,#_editor_class["T_Terrence_Boss"].cards,false})
table.insert(_editor_class["T_Terrence_Boss"].cards,boss.move.New(0,80,60,MOVE_DECEL))
table.insert(_editor_class["T_Terrence_Boss"].cards,boss.move.New(0,80,60,MOVE_DECEL))
local px={75,-75,120,-120};
local py={90,90,-40,-40};
local function T_Terrence_Summon_Magic(self)
    last=New(_editor_class["T_Terrence_Back1"],self.x,self.y)
    _connect(self,last,0,false)
    task._Wait(60)
    last=New(_editor_class["T_Terrence_Back2"],self.x,self.y)
    _connect(self,last,0,false)
    task._Wait(60)
    last=New(_editor_class["T_Terrence_Flower"],self.x,self.y,-75,90,1,2)
    _connect(self,last,0,false)
    last=New(_editor_class["T_Terrence_Flower"],self.x,self.y,75,90,-1,2)
    _connect(self,last,0,false)
    last=New(_editor_class["T_Terrence_Flower"],self.x,self.y,-120,-40,1,1)
    _connect(self,last,0,false)
    last=New(_editor_class["T_Terrence_Flower"],self.x,self.y,120,-40,-1,1)
    _connect(self,last,0,false)
end
local function CountGroup(g)
    local c=0;
    for _,unit in ObjList(g) do
        c=c+1;
    end
    return c;
end
_tmp_sc=boss.card.New("",1,3,60,1000,{0,0,0},false)
function _tmp_sc:before()
    New(boss_cast_ef,self.x,self.y)
    task._Wait(120)
    T_Terrence_Summon_Magic(self);
end
function _tmp_sc:init()
    lasttask=task.New(self,function()
        task.MoveTo(0,80,60,MOVE_DECEL)
        lasttask=task.New(self,function()
            for _=1,_infinite do
                PlaySound("ch00",0.1,self.x/256,false)
                do local i,_d_i=(1),(1) for _=1,4 do
                    last=New(_editor_class["T_Terrence_2_non_Lazer"],self.x+px[i],self.y+py[i],Angle(self.x+px[i],self.y+py[i],player.x,player.y))
                i=i+_d_i end end
                task._Wait(240)
            end
        end)
        lasttask=task.New(self,function()
            for _=1,_infinite do
                local a=ran:Float(-30,30)+Angle(self,player);
                do
                    local _beg_ang=a-90 local ang=_beg_ang local _end_ang=a+90 local _d_ang=(_end_ang-_beg_ang)/(12-1)
                    for _=1,12 do
                        last=New(_editor_class["T_Terrence_2_non_Bullet"],self.x,self.y,ang)
                        ang=ang+_d_ang
                    end
                end
                PlaySound("tan01",0.1,self.x/256,false)
                task._Wait(15)
            end
        end)
        lasttask=task.New(self,function()
            do local t,_d_t=(1),(3) for _=1,_infinite do
                self.y=80-5*sin(t);
                task._Wait(1)
            t=t+_d_t end end
        end)
    end)
end
function _tmp_sc:beforedel()
end
function _tmp_sc:del()
end
function _tmp_sc:after()
end
_tmp_sc.perform=false
table.insert(_editor_class["T_Terrence_Boss"].cards,_tmp_sc)

_tmp_sc=boss.card.New("魔法「魔界蝶的妖香」",2,5,60,1400,{30,0,30},false)
function _tmp_sc:before()
    if CountGroup(GROUP_BACK)==0 then
        T_Terrence_Summon_Magic(self);
    else
    end
end
function _tmp_sc:init()
    lasttask=task.New(self,function()
        task.MoveTo(0,20,60,MOVE_DECEL)
        task._Wait(60)
        lasttask=task.New(self,function()
            for _=1,_infinite do
                do local ang,_d_ang=(Angle(self,player)),(360/16) for _=1,16 do
                    last=New(_editor_class["T_Terrence_2_non_Lazer"],self.x,self.y,ang)
                ang=ang+_d_ang end end
                task._Wait(120)
            end
        end)
        lasttask=task.New(self,function()
            do local ang,_d_ang=(0),(18) for _=1,_infinite do
                _create_bullet_group(butterfly,COLOR_BLUE,self.x+px[3],self.y+py[3],3,0,2,2.5,-90+ang,0,false,0,true,true,0,false,self)
                _create_bullet_group(butterfly,COLOR_BLUE,self.x+px[1],self.y+py[1],3,0,2,2.5,-90+ang/3,0,false,0,true,true,0,false,self)
                _create_bullet_group(butterfly,COLOR_BLUE,self.x+px[4],self.y+py[4],3,0,2,2.5,-90-ang,0,false,0,true,true,0,false,self)
                _create_bullet_group(butterfly,COLOR_BLUE,self.x+px[2],self.y+py[2],3,0,2,2.5,-90-ang/3,0,false,0,true,true,0,false,self)
                PlaySound("tan01",0.1,self.x/256,false)
                task._Wait(6)
            ang=ang+_d_ang end end
        end)
    end)
end
function _tmp_sc:beforedel()
    for _,unit in ObjList(GROUP_BACK) do
        _kill(unit,true)
    end
end
function _tmp_sc:del()
end
function _tmp_sc:after()
end
_tmp_sc.perform=false
table.insert(_editor_class["T_Terrence_Boss"].cards,_tmp_sc)
table.insert(_sc_table,{"T_Terrence_Boss","魔法「魔界蝶的妖香」",_tmp_sc,#_editor_class["T_Terrence_Boss"].cards,false})
table.insert(_editor_class["T_Terrence_Boss"].cards,boss.move.New(0,20,120,MOVE_DECEL))
_tmp_sc=boss.card.New("",1,3,70,1000,{0,0,0},false)
function _tmp_sc:before()
    lasttask=task.New(self,function()
        T_Terrence_Summon_Magic(self);
    end)
    task.MoveTo(0,100,120,MOVE_DECEL)
end
function _tmp_sc:init()
    lasttask=task.New(self,function()
        task.MoveTo(0,100,120,MOVE_DECEL)
        for _=1,_infinite do
            local col,k=0,1;
            do local i,_d_i=(1),(1) for _=1,4 do
                if i<=2 then
                    col=COLOR_RED;
                else
                    col=COLOR_YELLOW
                end
                local ang1=ran:Float(0,360);
                last=New(_editor_class["T_Terrence_3_non"],self.x+px[i],self.y+py[i],col, ang1, k)
                if i%2==1 then
                    k=-k;
                else
                end
            i=i+_d_i end end
            task._Wait(120)
            task.MoveToPlayer(60,-96,96,90,110,16,32,8,16,MOVE_DECEL,MOVE_X_TOWARDS_PLAYER)
            task._Wait(60)
        end
    end)
end
function _tmp_sc:beforedel()
end
function _tmp_sc:del()
end
function _tmp_sc:after()
end
_tmp_sc.perform=false
table.insert(_editor_class["T_Terrence_Boss"].cards,_tmp_sc)

_tmp_sc=boss.card.New("光魔「星之旋涡」",2,5,50,1600,{20,0,20},false)
function _tmp_sc:before()
    if CountGroup(GROUP_BACK)==0 then
        T_Terrence_Summon_Magic(self);
    else
    end
end
function _tmp_sc:init()
    lasttask=task.New(self,function()
        task.MoveTo(0,80,60,MOVE_DECEL)
        task._Wait(60)
        for _=1,_infinite do
            local p=ran:Int(1,4);
            local x,y,a=0,0,0;
            if p==1 then
                x,y,a=ran:Float(200,210),ran:Float(-224,224),-120;
            elseif p==2 then
                x,y,a=-ran:Float(200,210),ran:Float(-224,224),60;
            elseif p==3 then
                x,y,a=ran:Float(-192,192),ran:Float(230,240),-30;
            else
                x,y,a=ran:Float(-192,192),-ran:Float(230,240),-210;
            end
            last=New(_editor_class["T_Terrence_3_spell_curve"],x,y,a)
            task._Wait(10)
        end
    end)
    lasttask=task.New(self,function()
        task._Wait(480)
        for _=1,_infinite do
            do local i,_d_i=(1),(1) for _=1,4 do
                last=New(_straight,star_small,COLOR_BLUE,self.x+px[i],self.y+py[i],3,0,true,3,true,true,0,false,0,0,0,false)
            i=i+_d_i end end
            task._Wait(120)
        end
    end)
end
function _tmp_sc:beforedel()
end
function _tmp_sc:del()
end
function _tmp_sc:after()
    for _,unit in ObjList(GROUP_BACK) do
        _kill(unit,true)
    end
end
_tmp_sc.perform=false
table.insert(_editor_class["T_Terrence_Boss"].cards,_tmp_sc)
table.insert(_sc_table,{"T_Terrence_Boss","光魔「星之旋涡」",_tmp_sc,#_editor_class["T_Terrence_Boss"].cards,false})
_tmp_sc=boss.dialog.New(true)
function _tmp_sc:init()
    lstg.player.dialog=true
    _dialog_can_skip=true
    self.dialog_displayer=New(dialog_displayer)
    lasttask=task.New(self,function()
    end)
end
table.insert(_editor_class["T_Terrence_Boss"].cards,_tmp_sc)
_tmp_sc=boss.card.New("",1,3,65,1000,{0,0,0},false)
function _tmp_sc:before()
    self.group=GROUP_NONTJT;
    task.MoveTo(0,110,120,MOVE_DECEL)
    T_Terrence_Summon_Magic(self);
end
function _tmp_sc:init()
    lasttask=task.New(self,function()
        task.MoveTo(0,110,60,MOVE_DECEL)
        lasttask=task.New(self,function()
            local k=-1;
            do local t,_d_t=(1),(1) for _=1,_infinite do
                local i=t%4+1;
                local ang1=ran:Float(0,360);
                if i<=2 then
                    col=COLOR_RED;
                else
                    col=COLOR_YELLOW
                end
                do
                    local _beg_ang=0 local ang=_beg_ang local _end_ang=360*k local _d_ang=(_end_ang-_beg_ang)/(36)
                    for _=1,36 do
                        _create_bullet_group(grain_a,col,self.x+px[i]+10*cos(ang1+ang),self.y+py[i]+10*sin(ang1+ang),3,0,3,3.5,ang1+ang-90*k,0,false,0,true,true,0,false,self)
                        PlaySound("tan01",0.1,self.x/256,false)
                        task._Wait(1)
                        ang=ang+_d_ang
                    end
                end
                last=New(_straight,ball_big,COLOR_RED,self.x+px[i],self.y+py[i],3,0,true,0,true,true,0,false,0,0,0,false)
                if i%2==1 then
                    k=-k;
                else
                end
            t=t+_d_t end end
        end)
        task._Wait(300)
        lasttask=task.New(self,function()
            do local a,_d_a=(0),(0.5) for _=1,_infinite do
                self.x,self.y=110*sin(a),110*cos(a);
                task._Wait(1)
            a=a+_d_a end end
        end)
    end)
end
function _tmp_sc:beforedel()
end
function _tmp_sc:del()
end
function _tmp_sc:after()
end
_tmp_sc.perform=false
table.insert(_editor_class["T_Terrence_Boss"].cards,_tmp_sc)

_tmp_sc=boss.card.New("大魔法「魔神复诵」",5,10,70,3000,{50,0,50},false)
function _tmp_sc:before()
    if CountGroup(GROUP_BACK)==0 then
        T_Terrence_Summon_Magic(self);
    else
    end
    self.group=GROUP_NONTJT;
end
function _tmp_sc:init()
    lasttask=task.New(self,function()
        task.MoveTo(0,0,60,MOVE_DECEL)
        local laz={};
        do local i,_d_i=(1),(1) for _=1,4 do
            last=New(_editor_class["T_Terrence_4_Spell"],self.x,self.y,-90,self.x+px[i],self.y+py[i])
            _connect(self,last,0,true)
            laz[i]=last;
        i=i+_d_i end end
        task._Wait(60)
        lasttask=task.New(self,function()
            do local a,_d_a=(0),(4) for _=1,31 do
                do local i,_d_i=(1),(1) for _=1,4 do
                    last=New(_straight,arrow_big,COLOR_BLUE,self.x+px[i],self.y+py[i],5,90+a,false,0,true,true,0,false,0,0,0,false)
                    last=New(_straight,arrow_big,COLOR_BLUE,self.x+px[i],self.y+py[i],5,90-a,false,0,true,true,0,false,0,0,0,false)
                    PlaySound("tan02",0.1,self.x/256,false)
                i=i+_d_i end end
                task._Wait(4)
            a=a+_d_a end end
            local k=1;
            do local i,_d_i=(1),(1) for _=1,4 do
                last=New(_editor_class["T_Terrence_4_spell_1"],self.x+px[i],self.y+py[i],k)
                if i%2==1 then
                    k=-k;
                else
                end
            i=i+_d_i end end
        end)
        PlaySound("se:T_Terrence_se_ufo",100,self.x/256,true)
        task.MoveTo(0,110,60,MOVE_DECEL)
        do local i,_d_i=(1),(1) for _=1,4 do
            _del(laz[i],true)
        i=i+_d_i end end
        task._Wait(60)
        lasttask=task.New(self,function()
            for _=1,_infinite do
                last=New(_straight,ball_big,COLOR_RED,self.x+ran:Float(75,190),self.y+ran:Float(-10,110),ran:Float(2,4),-90,false,0,true,true,0,false,0,0,0,false)
                do
                    local self = last
                    _object.set_color(self,"mul+add",255,255,255,255)
                end
                last=New(_straight,ball_big,COLOR_RED,self.x-ran:Float(75,190),self.y+ran:Float(-10,110),ran:Float(2,4),-90,false,0,true,true,0,false,0,0,0,false)
                do
                    local self = last
                    _object.set_color(self,"mul+add",255,255,255,255)
                end
                task._Wait(15)
            end
        end)
        lasttask=task.New(self,function()
            for _=1,_infinite do
                last=New(_straight,ball_huge,COLOR_RED,self.x,self.y,2.5,0,true,2,true,true,0,false,0,0,0,false)
                task._Wait(120)
            end
        end)
        for _=1,_infinite do
            if self.hp<3000*0.75 then break end
            task._Wait(1)
        end
        PlaySound("explode",0.1,self.x/256,false)
        lasttask=task.New(self,function()
            local k=-1;
            for _=1,_infinite do
                do
                    local _beg_a=90+90*k local a=_beg_a local _end_a=90-90*k local _d_a=(_end_a-_beg_a)/(6-1)
                    for _=1,6 do
                        last=New(_editor_class["T_Terrence_4_spell_Bullet"],self.x,self.y,a)
                        task._Wait(5)
                        a=a+_d_a
                    end
                end
                task._Wait(120)
                k=-k;
            end
        end)
        for _=1,_infinite do
            if self.hp<3000*0.5 then break end
            task._Wait(1)
        end
        PlaySound("boon01",0.1,self.x/256,false)
        lasttask=task.New(self,function()
            local k=1;
            do local i,_d_i=(1),(1) for _=1,4 do
                last=New(_editor_class["T_Terrence_4_spell_Lazer2"],self.x+px[i],self.y+py[i],k)
                if i%2==1 then
                    k=-k;
                else
                end
            i=i+_d_i end end
        end)
        for _=1,_infinite do
            if self.hp<3000*0.25 then break end
            task._Wait(1)
        end
        PlaySound("explode",0.1,self.x/256,false)
        lasttask=task.New(self,function()
            for _=1,_infinite do
                do
                    local _beg_a=0 local a=_beg_a local _end_a=-180 local _d_a=(_end_a-_beg_a)/(9)
                    for _=1,9 do
                        last=New(_straight,ball_big,COLOR_BLUE,self.x,self.y,2.5,a,false,0,true,true,0,false,0,0,0,false)
                        do
                            local self = last
                            _object.set_color(self,"mul+add",255,255,255,255)
                        end
                        task._Wait(5)
                        a=a+_d_a
                    end
                end
                do
                    local _beg_a=-180 local a=_beg_a local _end_a=0 local _d_a=(_end_a-_beg_a)/(9)
                    for _=1,9 do
                        last=New(_straight,ball_big,COLOR_BLUE,self.x,self.y,2.5,a,false,0,true,true,0,false,0,0,0,false)
                        do
                            local self = last
                            _object.set_color(self,"mul+add",255,255,255,255)
                        end
                        task._Wait(5)
                        a=a+_d_a
                    end
                end
            end
        end)
    end)
end
function _tmp_sc:beforedel()
end
function _tmp_sc:del()
end
function _tmp_sc:after()
    for _,unit in ObjList(GROUP_BACK) do
        _kill(unit,true)
    end
end
_tmp_sc.perform=false
table.insert(_editor_class["T_Terrence_Boss"].cards,_tmp_sc)
table.insert(_sc_table,{"T_Terrence_Boss","大魔法「魔神复诵」",_tmp_sc,#_editor_class["T_Terrence_Boss"].cards,false})
_tmp_sc=boss.dialog.New(true)
function _tmp_sc:init()
    lstg.player.dialog=true
    _dialog_can_skip=true
    self.dialog_displayer=New(dialog_displayer)
    lasttask=task.New(self,function()
    end)
end
table.insert(_editor_class["T_Terrence_Boss"].cards,_tmp_sc)
_tmp_sc=boss.card.New("「圣尼公的气之魔法卷轴」",2,5,80,1200,{150,0,50},true)
function _tmp_sc:before()
    self.group=GROUP_NONTJT;
    task._Wait(120)
end
function _tmp_sc:init()
    lasttask=task.New(self,function()
        task.MoveTo(150,90,60,MOVE_DECEL)
        boss.cast(self,60)
        task._Wait(60)
        for _=1,_infinite do
            local k=-1
            do
                local _beg_y=170-250/8 local y=_beg_y local _end_y=-80 local _d_y=(_end_y-_beg_y)/(8-1)
                local _beg_w=90 local w=_beg_w local _end_w=10 local _d_w=(_end_w-_beg_w)/(8-1)
                for _=1,8 do
                    last=New(_editor_class["T_Terrence_Boss_Smear"],self.x,self.y)
                    _connect(self,last,0,true)
                    local sm=last;
                    local x1,y1=self.x,self.y;
                    task.MoveTo(k*150,y,w,MOVE_DECEL)
                    _del(sm,true)
                    local x2,y2=self.x,self.y;
                    last=New(_editor_class["T_Terrence_Line"],self.x,self.y,x1,y1,x2,y2)
                    PlaySound("tan00",0.1,self.x/256,false)
                    k=-k;
                    y=y+_d_y
                    w=w+_d_w
                end
            end
            task._Wait(120)
            New(boss_cast_ef,self.x,self.y)
            task._Wait(60)
            k=1;
            do
                local _beg_x=150-300/8 local x=_beg_x local _end_x=-150 local _d_x=(_end_x-_beg_x)/(8-1)
                local _beg_w=90 local w=_beg_w local _end_w=10 local _d_w=(_end_w-_beg_w)/(8-1)
                for _=1,8 do
                    last=New(_editor_class["T_Terrence_Boss_Smear"],self.x,self.y)
                    _connect(self,last,0,true)
                    local sm=last;
                    local x1,y1=self.x,self.y;
                    task.MoveTo(x,45+k*125,w,MOVE_DECEL)
                    _del(sm,true)
                    local x2,y2=self.x,self.y;
                    last=New(_editor_class["T_Terrence_Line"],self.x,self.y,x1,y1,x2,y2)
                    PlaySound("tan00",0.1,self.x/256,false)
                    k=-k;
                    x=x+_d_x
                    w=w+_d_w
                end
            end
            task._Wait(120)
            New(boss_cast_ef,self.x,self.y)
            task._Wait(60)
            k=1;
            do
                local _beg_y=-80+250/8 local y=_beg_y local _end_y=170 local _d_y=(_end_y-_beg_y)/(8-1)
                local _beg_w=90 local w=_beg_w local _end_w=10 local _d_w=(_end_w-_beg_w)/(8-1)
                for _=1,8 do
                    last=New(_editor_class["T_Terrence_Boss_Smear"],self.x,self.y)
                    _connect(self,last,0,true)
                    local sm=last;
                    local x1,y1=self.x,self.y;
                    task.MoveTo(k*150,y,w,MOVE_DECEL)
                    _del(sm,true)
                    local x2,y2=self.x,self.y;
                    last=New(_editor_class["T_Terrence_Line"],self.x,self.y,x1,y1,x2,y2)
                    PlaySound("tan00",0.1,self.x/256,false)
                    k=-k;
                    y=y+_d_y
                    w=w+_d_w
                end
            end
            task._Wait(120)
            New(boss_cast_ef,self.x,self.y)
            task._Wait(60)
            k=-1;
            do
                local _beg_x=-150+300/8 local x=_beg_x local _end_x=150 local _d_x=(_end_x-_beg_x)/(8-1)
                local _beg_w=90 local w=_beg_w local _end_w=10 local _d_w=(_end_w-_beg_w)/(8-1)
                for _=1,8 do
                    last=New(_editor_class["T_Terrence_Boss_Smear"],self.x,self.y)
                    _connect(self,last,0,true)
                    local sm=last;
                    local x1,y1=self.x,self.y;
                    task.MoveTo(x,45+k*125,w,MOVE_DECEL)
                    _del(sm,true)
                    local x2,y2=self.x,self.y;
                    last=New(_editor_class["T_Terrence_Line"],self.x,self.y,x1,y1,x2,y2)
                    PlaySound("tan00",0.1,self.x/256,false)
                    k=-k;
                    x=x+_d_x
                    w=w+_d_w
                end
            end
            task._Wait(120)
            New(boss_cast_ef,self.x,self.y)
            task._Wait(60)
        end
    end)
end
function _tmp_sc:beforedel()
end
function _tmp_sc:del()
end
function _tmp_sc:after()
end
_tmp_sc.perform=false
table.insert(_editor_class["T_Terrence_Boss"].cards,_tmp_sc)
table.insert(_sc_table,{"T_Terrence_Boss","「圣尼公的气之魔法卷轴」",_tmp_sc,#_editor_class["T_Terrence_Boss"].cards,false})
_tmp_sc=boss.dialog.New(true)
function _tmp_sc:init()
    lstg.player.dialog=true
    _dialog_can_skip=true
    self.dialog_displayer=New(dialog_displayer)
    lasttask=task.New(self,function()
    end)
end
table.insert(_editor_class["T_Terrence_Boss"].cards,_tmp_sc)
--[[ 1
]]
_tmp_sc=boss.card.New("「飞行幻想」",5,10,120,5000,{0,0,0},true)
function _tmp_sc:before()
    self.group=GROUP_NONTJT;
    task._Wait(120)
    ui.lstg_weekly.SetFlag(true, false, false)
    ui.lstg_weekly.SetEditor("T_Terrence")
end
function _tmp_sc:init()
    lasttask=task.New(self,function()
        task.MoveTo(0,100,60,MOVE_DECEL)
        local colors={{200,112,7,148},{200,231,251,16},{200,28,8,157},{200,240,45,42}};
        local scol={COLOR_PURPLE,COLOR_YELLOW,COLOR_BLUE,COLOR_RED};
        T_Terrence_Summon_Magic(self);
        task._Wait(60)
        local k=1;
        local w=300;
        lasttask=task.New(self,function()
            do local t,_d_t=(1),(3) for _=1,_infinite do
                self.y=100-5*sin(t);
                task._Wait(1)
            t=t+_d_t end end
        end)
        do local i,_d_i=(1),(1) for _=1,_infinite do
            if i%4==0 or i%4==1 then
                do local j,_d_j=(1),(1) for _=1,4 do
                    last=New(_editor_class["T_Terrence_plate"],self.x+px[j],self.y+py[j],k*0.3, -90, colors[i%4+1], scol[i%4+1])
                    if j%2==1 then k=-k; end
                j=j+_d_j end end
            else
                do local j,_d_j=(1),(1) for _=1,4 do
                    last=New(_editor_class["T_Terrence_plate"],self.x+px[j],self.y+py[j],k*0.3, Angle(self.x+px[j],self.y+py[j],player.x,player.y), colors[i%4+1], scol[i%4+1])
                    if j%2==1 then k=-k; end
                j=j+_d_j end end
            end
            PlaySound("tan01",0.1,self.x/256,false)
            task._Wait(w)
            if w>=180 and i%6==0 then
                w=w-60;
            else
            end
            k=-k;
        i=i+_d_i end end
    end)
end
function _tmp_sc:beforedel()
end
function _tmp_sc:del()
end
function _tmp_sc:after()
    for _,unit in ObjList(GROUP_BACK) do
        _kill(unit,true)
    end
end
_tmp_sc.perform=false
table.insert(_editor_class["T_Terrence_Boss"].cards,_tmp_sc)
table.insert(_sc_table,{"T_Terrence_Boss","「飞行幻想」",_tmp_sc,#_editor_class["T_Terrence_Boss"].cards,false})
_editor_class["T_Terrence_2_non_Lazer"]=Class(laser)
_editor_class["T_Terrence_2_non_Lazer"].init=function(self,_x,_y,ang)
    laser.init(self,COLOR_RED,_x,_y,0,0,0,0,8,8,0)
    
    self.rot=ang;
    lasttask=task.New(self,function()
        laser._TurnHalfOn(self,0,true)
        do
            local _beg_l=0 local l=_beg_l local _end_l=100 local _d_l=(_end_l-_beg_l)/(30-1)
            for _=1,30 do
                self.l1,self.l2,self.l3=2*l,l,2*l;
                task._Wait(1)
                l=l+_d_l
            end
        end
        laser._TurnOn(self,30,true,true)
        task._Wait(60)
        _del(self,true)
    end)
end
_editor_class["T_Terrence_2_non_Bullet"]=Class(bullet)
_editor_class["T_Terrence_2_non_Bullet"].init=function(self,_x,_y,ang)
bullet.init(self,water_drop,COLOR_PURPLE,true,true)
self.x,self.y=_x,_y
    lasttask=task.New(self,function()
        local v=6;
        SetV2(self,v,ang,true,false)
        _set_a(self,-v/60,ang,false)
        task._Wait(60)
        _set_a(self,0,0,false)
        SetV2(self,2,-90,true,false)
    end)
end
_editor_class["T_Terrence_3_non"]=Class(_object)
_editor_class["T_Terrence_3_non"].init=function(self,_x,_y,col,ang1,k)
    self.x,self.y=_x,_y
    self.img="img_void"
    self.layer=LAYER_ENEMY_BULLET
    self.group=GROUP_ENEMY_BULLET
    self.hide=false
    self.bound=true
    self.navi=false
    self.hp=10
    self.maxhp=10
    self.colli=true
    self._servants={}
    self._blend,self._a,self._r,self._g,self._b='',255,255,255,255
    lasttask=task.New(self,function()
        do
            local _beg_ang=0 local ang=_beg_ang local _end_ang=540*k local _d_ang=(_end_ang-_beg_ang)/(60-1)
            for _=1,60 do
                _create_bullet_group(grain_a,col,self.x+10*cos(ang1+ang),self.y+10*sin(ang1+ang),4,0,3,3.5,ang1+ang-90*k,0,false,0,true,true,0,false,self)
                PlaySound("tan01",0.1,self.x/256,false)
                task._Wait(1)
                ang=ang+_d_ang
            end
        end
        _del(self,true)
    end)
end
_editor_class["T_Terrence_3_spell_curve"]=Class(laser_bent)
_editor_class["T_Terrence_3_spell_curve"].init=function(self,_x,_y,ang)
    laser_bent.init(self,COLOR_GOLDEN_YELLOW,_x,_y,32,8,4,0)
    self.bound=false;
    PlaySound("lazer01",0.1,self.x/256,false)
    lasttask=task.New(self,function()
        do local a,_d_a=(ang),(-0.7) for _=1,515 do
            SetV2(self,3,a,true,false)
            task._Wait(1)
        a=a+_d_a end end
        SetV2(self,0,0,true,false)
        task._Wait(60)
        _del(self,true)
    end)
    lasttask=task.New(self,function()
        task._Wait(60)
        self.bound=true;
    end)
end
_editor_class["T_Terrence_4_Spell"]=Class(laser)
_editor_class["T_Terrence_4_Spell"].init=function(self,_x,_y,ang,x,y)
    laser.init(self,COLOR_RED,_x,_y,0,0,500,0,30,20,0)
    laser.ChangeImage(self,4)
    self.rot=ang;
    lasttask=task.New(self,function()
        laser._TurnHalfOn(self,0,true)
        task._Wait(60)
        laser._TurnOn(self,30,true,true)
    end)
    lasttask=task.New(self,function()
        for _=1,_infinite do
            _set_rel_pos(self,x,y,self.rot,false)
            task._Wait(1)
        end
    end)
end
_editor_class["T_Terrence_4_spell_1"]=Class(_object)
_editor_class["T_Terrence_4_spell_1"].init=function(self,_x,_y,k)
    self.x,self.y=_x,_y
    self.img="img_void"
    self.layer=LAYER_ENEMY_BULLET
    self.group=GROUP_INDES
    self.hide=false
    self.bound=true
    self.navi=false
    self.hp=10
    self.maxhp=10
    self.colli=false
    self._servants={}
    self._blend,self._a,self._r,self._g,self._b='',255,255,255,255
    self.rot=-90;
    lasttask=task.New(self,function()
        do
            local _beg_ang=-90 local ang=_beg_ang local _end_ang=-90+8*k local _d_ang=(_end_ang-_beg_ang)/(75)
            for _=1,75 do
                self.rot=ang;
                task._Wait(1)
                ang=ang+_d_ang
            end
        end
        for _=1,_infinite do
            do
                local _beg_ang=-90+8*k local ang=_beg_ang local _end_ang=-90-8*k local _d_ang=(_end_ang-_beg_ang)/(150)
                for _=1,150 do
                    self.rot=ang;
                    task._Wait(1)
                    ang=ang+_d_ang
                end
            end
            do
                local _beg_ang=-90-8*k local ang=_beg_ang local _end_ang=-90+8*k local _d_ang=(_end_ang-_beg_ang)/(150)
                for _=1,150 do
                    self.rot=ang;
                    task._Wait(1)
                    ang=ang+_d_ang
                end
            end
        end
    end)
    lasttask=task.New(self,function()
        for _=1,_infinite do
            _create_bullet_group(arrow_big,COLOR_BLUE,self.x,self.y,3,0,5,5,self.rot,180,false,0,true,true,0,false,self)
            PlaySound("tan02",0.1,self.x/256,false)
            task._Wait(4)
        end
    end)
end
_editor_class["T_Terrence_4_spell_Bullet"]=Class(bullet)
_editor_class["T_Terrence_4_spell_Bullet"].init=function(self,_x,_y,ang)
bullet.init(self,ball_big,COLOR_PURPLE,true,true)
self.x,self.y=_x,_y
    lasttask=task.New(self,function()
        SetV2(self,3,ang,true,false)
        for _=1,_infinite do
            if self.x<-192 or self.x>192 or self.y>224 or self.y<-224 then break end
            task._Wait(1)
        end
        _object.set_color(self,"mul+add",255,255,255,255)
        SetV2(self,0,0,true,false)
        _set_a(self,0.02,0,true)
    end)
end
_editor_class["T_Terrence_4_spell_Lazer2"]=Class(laser)
_editor_class["T_Terrence_4_spell_Lazer2"].init=function(self,_x,_y,k)
    laser.init(self,COLOR_RED,_x,_y,0,0,500,0,30,20,0)
    laser.ChangeImage(self,4)
    self.rot=-90;
    lasttask=task.New(self,function()
        laser._TurnHalfOn(self,0,true)
        task._Wait(120)
        laser._TurnOn(self,30,true,false)
        lasttask=task.New(self,function()
            do
                local _beg_ang=-90 local ang=_beg_ang local _end_ang=-90+5*k local _d_ang=(_end_ang-_beg_ang)/(60)
                for _=1,60 do
                    self.rot=ang;
                    task._Wait(1)
                    ang=ang+_d_ang
                end
            end
            for _=1,_infinite do
                do
                    local _beg_ang=-90+5*k local ang=_beg_ang local _end_ang=-90-5*k local _d_ang=(_end_ang-_beg_ang)/(120)
                    for _=1,120 do
                        self.rot=ang;
                        task._Wait(1)
                        ang=ang+_d_ang
                    end
                end
                do
                    local _beg_ang=-90-5*k local ang=_beg_ang local _end_ang=-90+5*k local _d_ang=(_end_ang-_beg_ang)/(120)
                    for _=1,120 do
                        self.rot=ang;
                        task._Wait(1)
                        ang=ang+_d_ang
                    end
                end
            end
        end)
    end)
end
_editor_class["T_Terrence_Boss_Smear"]=Class(_object)
_editor_class["T_Terrence_Boss_Smear"].init=function(self,_x,_y)
    self.x,self.y=_x,_y
    self.img="img_void"
    self.layer=LAYER_ENEMY-5
    self.group=GROUP_INDES
    self.hide=false
    self.bound=true
    self.navi=false
    self.hp=10
    self.maxhp=10
    self.colli=true
    self._servants={}
    self._blend,self._a,self._r,self._g,self._b='',255,255,255,255
    self.smx={};
    self.smy={};
    do local i,_d_i=(1),(1) for _=1,30 do
        self.smx[i]=self.x;
        self.smy[i]=self.y;
    i=i+_d_i end end
    lasttask=task.New(self,function()
        for _=1,_infinite do
            do local i,_d_i=(1),(1) for _=1,30 do
                self.smx[i]=self.x;
                self.smy[i]=self.y;
                task._Wait(1)
            i=i+_d_i end end
        end
    end)
end
_editor_class["T_Terrence_Boss_Smear"].frame=function(self)
    self.class.base.frame(self)
    _set_rel_pos(self,0,0,self.rot,false)
end
_editor_class["T_Terrence_Boss_Smear"].render=function(self)
    do local i,_d_i=(1),(1) for _=1,30 do
        SetImageState("image:T_Terrence_stage06e01_4","mul+add",Color(200,0,0,255));
        Render("image:T_Terrence_stage06e01_4",self.smx[i],self.smy[i],self.rot)
    i=i+_d_i end end
    self.class.base.render(self)
end
_editor_class["T_Terrence_Line"]=Class(_object)
_editor_class["T_Terrence_Line"].init=function(self,_x,_y,x1,y1,x2,y2)
    self.x,self.y=_x,_y
    self.img="img_void"
    self.layer=LAYER_ENEMY_BULLET
    self.group=GROUP_INDES
    self.hide=false
    self.bound=true
    self.navi=false
    self.hp=10
    self.maxhp=10
    self.colli=false
    self._servants={}
    self._blend,self._a,self._r,self._g,self._b='',255,255,255,255
    do
        local _beg_x=x1 local x=_beg_x local _end_x=x2 local _d_x=(_end_x-_beg_x)/(60-1)
        local _beg_y=y1 local y=_beg_y local _end_y=y2 local _d_y=(_end_y-_beg_y)/(60-1)
        local _beg_ang=Angle(x1,y1,x2,y2) local ang=_beg_ang local _end_ang=Angle(x1,y1,x2,y2)-630 local _d_ang=(_end_ang-_beg_ang)/(60-1)
        for _=1,60 do
            last=New(_straight,ball_mid,COLOR_BLUE,x,y,0,ang,false,0,true,true,0,false,0,0,0,false)
            do
                local self = last
                lasttask=task.New(self,function()
                    _object.set_color(self,"mul+add",255,255,255,255)
                    task._Wait(180)
                    _set_a(self,0.03,self.rot,false)
                    task._Wait(60)
                    _set_a(self,0,0,false)
                end)
            end
            x=x+_d_x
            y=y+_d_y
            ang=ang+_d_ang
        end
    end
end
_editor_class["T_Terrence_Circle"]=Class(_object)
_editor_class["T_Terrence_Circle"].init=function(self,_x,_y,x,y,r,d,col)
    self.x,self.y=_x,_y
    self.img="img_void"
    self.layer=LAYER_ENEMY_BULLET-5
    self.group=GROUP_INDES
    self.hide=false
    self.bound=false
    self.navi=false
    self.hp=10
    self.maxhp=10
    self.colli=false
    self._servants={}
    self._blend,self._a,self._r,self._g,self._b='',255,255,255,255
    self.x,self.y,self.r,self.d,self.color=x,y,r,d,Color(unpack(col));
end
_editor_class["T_Terrence_Circle"].render=function(self)
    SetImageState("white","mul+add",self.color);
    do local i,_d_i=(1),(1) for _=1,360 do
        Render4V("white",self.x+self.r*cos(i+1),self.y+self.r*sin(i+1),0.5
                        ,self.x+(self.r+self.d)*cos(i+1),self.y+(self.r+self.d)*sin(i+1),0.5
                        ,self.x+(self.r+self.d)*cos(i),self.y+(self.r+self.d)*sin(i),0.5
                        ,self.x+self.r*cos(i),self.y+self.r*sin(i),0.5)
    i=i+_d_i end end
end
_editor_class["T_Terrence_plate"]=Class(_object)
_editor_class["T_Terrence_plate"].init=function(self,_x,_y,rot_v,dir,col,scol)
    self.x,self.y=_x,_y
    self.img="img_void"
    self.layer=LAYER_ENEMY_BULLET
    self.group=GROUP_INDES
    self.hide=false
    self.bound=false
    self.navi=false
    self.hp=10
    self.maxhp=10
    self.colli=false
    self._servants={}
    self._blend,self._a,self._r,self._g,self._b='',255,255,255,255
    SetV2(self,0,dir,false,false)
    _set_a(self,0.003,dir,false)
    lasttask=task.New(self,function()
        last=New(_editor_class["T_Terrence_Circle"],self.x,self.y,self.x,self.y,0,2,col)
        _connect(self,last,0,true)
        local edge=last;
        self.r=0;
        self.rot=ran:Float(0,360);
        local dr=10;
        for _=1,_infinite do
            do
                local _beg_r=0 local r=_beg_r local _end_r=300 local _w_r=0 local _d_w_r=1/(600-1)
                for _=1,600 do
                    if IsValid(edge) then
                        edge.x,edge.y,edge.r=self.x,self.y,r;
                        self.r=r;
                        self.rot=self.rot+rot_v;
                    else
                    end
                    task._Wait(1)
                    _w_r=_w_r+_d_w_r r=(_beg_r-_end_r)*(_w_r-1)^2+_end_r
                end
            end
            do
                local _beg_r=300 local r=_beg_r local _end_r=0 local _w_r=0  local _d_w_r=1/(600-1)
                for _=1,600 do
                    if IsValid(edge) then
                        edge.x,edge.y,edge.r=self.x,self.y,r;
                        self.r=r;
                        self.rot=self.rot+rot_v;
                    else
                    end
                    task._Wait(1)
                    _w_r=_w_r+_d_w_r r=(_end_r-_beg_r)*_w_r^2+_beg_r
                end
            end
        end
    end)
    lasttask=task.New(self,function()
        local bullets={};
        do local i,_d_i=(1),(1) for _=1,24 do
            last=New(_editor_class["T_Terrence_spell"],self.x,self.y,scol)
            _connect(self,last,0,true)
            bullets[i]=last;
        i=i+_d_i end end
        for _=1,_infinite do
            do
                local _beg_i=1 local i=_beg_i local _end_i=24 local _d_i=(_end_i-_beg_i)/(24-1)
                for _=1,24 do
                    if IsValid(bullets[i]) then
                        local ang=360/24*i+self.rot;
                        bullets[i].x=self.x+self.r*cos(ang);
                        bullets[i].y=self.y+self.r*sin(ang);
                    else
                    end
                    i=i+_d_i
                end
            end
            task._Wait(1)
        end
    end)
    lasttask=task.New(self,function()
        for _=1,_infinite do
            if self.x-self.r>192 or self.x+self.r<-192 or self.y+self.r<-224 or self.y-self.r>224 then
                _del(self,false)
            else
            end
            task._Wait(1)
        end
    end)
end
_editor_class["T_Terrence_spell"]=Class(bullet)
_editor_class["T_Terrence_spell"].init=function(self,_x,_y,col)
bullet.init(self,square,col,true,false)
self.x,self.y=_x,_y
    self.x,self.y=0,0;
    self.bound=false;
    self.navi=true;
    _object.set_color(self,"mul+add",255,255,255,255)
end
_editor_class["T_Terrence_SpellBG"]=Class(_spellcard_background)
_editor_class["T_Terrence_SpellBG"].init=function(self)
    _spellcard_background.init(self)
    _spellcard_background.AddLayer(self,"image:T_Terrence_cdbg06b",false,0,0,0,0,0,0.5,"mul+add",1,1,
        function(self)
            self.task={}
        end,
        function(self)
            task.Do(self)
        end,
        function(self)
        end
    )
    _spellcard_background.AddLayer(self,"image:T_Terrence_cdbg06a",true,0,0,0,0,1,0,"",1,1,
        function(self)
            self.task={}
        end,
        function(self)
            task.Do(self)
        end,
        function(self)
        end
    )
end
_editor_class["T_Terrence_Back1"]=Class(_object)
_editor_class["T_Terrence_Back1"].init=function(self,_x,_y)
    self.x,self.y=_x,_y
    self.img="image:T_Terrence_stage06e03"
    self.layer=LAYER_ENEMY-5
    self.group=GROUP_BACK
    self.hide=false
    self.bound=false
    self.navi=false
    self.hp=10
    self.maxhp=10
    self.colli=false
    self._servants={}
    self._blend,self._a,self._r,self._g,self._b='',255,255,255,255
    self.rot=-180;
    self.hscale,self.vscale=0,0;
    lasttask=task.New(self,function()
        do
            local _beg_rot=-180 local rot=_beg_rot local _end_rot=0 local _w_rot=0 local _d_w_rot=1/(60-1)
            local _beg_s=0 local s=_beg_s local _end_s=1 local _w_s=0 local _d_w_s=1/(60-1)
            for _=1,60 do
                self.rot=rot;
                self.hscale,self.vscale=s,s;
                task._Wait(1)
                _w_rot=_w_rot+_d_w_rot rot=(_beg_rot-_end_rot)*(_w_rot-1)^2+_end_rot
                _w_s=_w_s+_d_w_s s=(_beg_s-_end_s)*(_w_s-1)^2+_end_s
            end
        end
        task._Wait(180)
        for _=1,_infinite do
            do
                local _beg_s=1 local s=_beg_s local _end_s=0.9 local _w_s=0 local _d_w_s=1/(60-1)
                for _=1,60 do
                    self.hscale,self.vscale=s,s;
                    task._Wait(1)
                    _w_s=_w_s+_d_w_s if _w_s<0.5 then s=2*(_end_s-_beg_s)*_w_s^2+_beg_s else s=(_end_s-_beg_s)*(-2*_w_s^2+4*_w_s-1)+_beg_s end
                end
            end
            do
                local _beg_s=0.9 local s=_beg_s local _end_s=1 local _w_s=0 local _d_w_s=1/(60-1)
                for _=1,60 do
                    self.hscale,self.vscale=s,s;
                    task._Wait(1)
                    _w_s=_w_s+_d_w_s if _w_s<0.5 then s=2*(_end_s-_beg_s)*_w_s^2+_beg_s else s=(_end_s-_beg_s)*(-2*_w_s^2+4*_w_s-1)+_beg_s end
                end
            end
        end
    end)
end
_editor_class["T_Terrence_Back1"].frame=function(self)
    self.class.base.frame(self)
    _set_rel_pos(self,0,0,self.rot,false)
end
_editor_class["T_Terrence_Back2"]=Class(_object)
_editor_class["T_Terrence_Back2"].init=function(self,_x,_y)
    self.x,self.y=_x,_y
    self.img="image:T_Terrence_stage06e03_2"
    self.layer=LAYER_ENEMY-6
    self.group=GROUP_BACK
    self.hide=false
    self.bound=false
    self.navi=false
    self.hp=10
    self.maxhp=10
    self.colli=false
    self._servants={}
    self._blend,self._a,self._r,self._g,self._b='',255,255,255,255
    self.hscale,self.vscale=0,1;
    lasttask=task.New(self,function()
        do
            local _beg_s=0 local s=_beg_s local _end_s=1 local _w_s=0 local _d_w_s=1/(60-1)
            for _=1,60 do
                self.hscale=s;
                task._Wait(1)
                _w_s=_w_s+_d_w_s s=(_beg_s-_end_s)*(_w_s-1)^2+_end_s
            end
        end
        task._Wait(60)
        for _=1,_infinite do
            do
                local _beg_s=1 local s=_beg_s local _end_s=0.95 local _w_s=0 local _d_w_s=1/(60-1)
                for _=1,60 do
                    self.hscale=s;
                    task._Wait(1)
                    _w_s=_w_s+_d_w_s if _w_s<0.5 then s=2*(_end_s-_beg_s)*_w_s^2+_beg_s else s=(_end_s-_beg_s)*(-2*_w_s^2+4*_w_s-1)+_beg_s end
                end
            end
            do
                local _beg_s=0.95 local s=_beg_s local _end_s=1 local _w_s=0 local _d_w_s=1/(60-1)
                for _=1,60 do
                    self.hscale=s;
                    task._Wait(1)
                    _w_s=_w_s+_d_w_s if _w_s<0.5 then s=2*(_end_s-_beg_s)*_w_s^2+_beg_s else s=(_end_s-_beg_s)*(-2*_w_s^2+4*_w_s-1)+_beg_s end
                end
            end
        end
    end)
end
_editor_class["T_Terrence_Back2"].frame=function(self)
    self.class.base.frame(self)
    _set_rel_pos(self,0,0,self.rot,false)
end
_editor_class["T_Terrence_Flower"]=Class(_object)
_editor_class["T_Terrence_Flower"].init=function(self,_x,_y,x,y,k,c)
    self.x,self.y=_x,_y
    self.img="image:T_Terrence_stage06e03_3_"..c
    self.layer=LAYER_ENEMY
    self.group=GROUP_BACK
    self.hide=false
    self.bound=false
    self.navi=false
    self.hp=10
    self.maxhp=10
    self.colli=false
    self._servants={}
    self._blend,self._a,self._r,self._g,self._b='',255,255,255,255
    lasttask=task.New(self,function()
        do
            local _beg_s=0 local s=_beg_s local _end_s=1 local _w_s=0 local _d_w_s=1/(60-1)
            for _=1,60 do
                self.hscale,self.vscale=s*k,s;
                task._Wait(1)
                _w_s=_w_s+_d_w_s s=(_beg_s-_end_s)*(_w_s-1)^2+_end_s
            end
        end
        for _=1,_infinite do
            do
                local _beg_r=0 local r=_beg_r local _end_r=-k*5 local _w_r=0 local _d_w_r=1/(60-1)
                for _=1,60 do
                    self.rot=r;
                    task._Wait(1)
                    _w_r=_w_r+_d_w_r r=(_beg_r-_end_r)*(_w_r-1)^2+_end_r
                end
            end
            do
                local _beg_r=-k*5 local r=_beg_r local _end_r=0 local _w_r=0 local _d_w_r=1/(60-1)
                for _=1,60 do
                    self.rot=r;
                    task._Wait(1)
                    _w_r=_w_r+_d_w_r if _w_r<0.5 then r=2*(_end_r-_beg_r)*_w_r^2+_beg_r else r=(_end_r-_beg_r)*(-2*_w_r^2+4*_w_r-1)+_beg_r end
                end
            end
        end
    end)
    lasttask=task.New(self,function()
        for _=1,_infinite do
            _set_rel_pos(self,x,y,self.rot,false)
            task._Wait(1)
        end
    end)
end
_editor_class["T_Terrence_Flower"].kill=function(self)
    self.class.base.kill(self)
    _drop_item(item_point,15,self.x,self.y)
    _drop_item(item_power,15,self.x,self.y)
end
stage.group.AddStage(__WEEK_ID,'T_Terrence@'..__WEEK_ID,{lifeleft=7,power=400,faith=50000,bomb=3},true)
stage.group.DefStageFunc('T_Terrence@'..__WEEK_ID,'init',function(self)
    _init_item(self)
    difficulty=self.group.difficulty
    New(mask_fader,'open')
    if jstg then jstg.CreatePlayers() else New(_G[lstg.var.player_name]) end
    lasttask=task.New(self,function()
        LoadMusic('spellcard','THlib\\music\\spellcard.ogg',75,0xc36e80/44100/4)
        New(temple_background)
        task._Wait(60)
        local _boss_wait=true
        local _ref=New(_editor_class["T_Terrence_Boss"],_editor_class["T_Terrence_Boss"].cards)
        last=_ref
        if _boss_wait then while IsValid(_ref) do task.Wait() end end
        task._Wait(180)
    end)
    ui.lstg_weekly.stage_init(self)
    task.New(self,function()
        while coroutine.status(self.task[1])~='dead' do task.Wait() end
        stage.group.FinishReplay()
        New(mask_fader,'close')
        task.New(self,function()
            local _,bgm=EnumRes('bgm')
            for i=1,30 do
                for _,v in pairs(bgm) do
                    if GetMusicState(v)=='playing' then
                        SetBGMVolume(v,1-i/30)
                    end
                end
                task.Wait()
            end
        end)
        task.Wait(30)
        stage.group.FinishStage()
    end)
end)
