-- Generated by LuaSTG Editor Sharp
-- Mod name: 
_author = "LuaSTG User"
_mod_version = 4096
_allow_practice = true
_allow_sc_practice =true
-- archive space: Comet_Fox\music\
MusicRecord('bgm:'..'Comet_Fox_aka_music','Comet_Fox\\music\\Comet_Fox_aka_music.ogg',0x132BA00/44100/4,0x1290800/44100)
MusicRecord('bgm:'..'Comet_Fox_smith_theme','Comet_Fox\\music\\Comet_Fox_smith_theme.ogg',0x1A97160/44100/4,0x1A120A0/44100)
-- archive space: Comet_Fox\boss_enm\
_LoadImageFromFile('image:'..'Comet_Fox_smith','Comet_Fox\\boss_enm\\Comet_Fox_smith.png',true,0,0,false,0)
_LoadImageFromFile('image:'..'Comet_Fox_Aka','Comet_Fox\\boss_enm\\Comet_Fox_Aka.png',true,0,0,false,0)
_editor_class["Comet_Fox_ct"]=Class(_object)
_editor_class["Comet_Fox_ct"].init=function(self,_x,_y,flag,flag_img)
    self.x,self.y=_x,_y
    self.img="image:Comet_Fox_smith"
    self.layer=LAYER_TOP
    self.group=GROUP_GHOST
    self.hide=false
    self.bound=false
    self.navi=false
    self.hp=10
    self.maxhp=10
    self.colli=false
    self._servants={}
    self._blend,self._a,self._r,self._g,self._b='',255,255,255,255
    _object.set_color(self,"",255,255,255,255)
    lasttask=task.New(self,function()
        if flag==1 then
            lasttask=task.New(self,function()
                task.MoveTo(0,-100,60,MOVE_ACC_DEC)
                task._Wait(11)
                do
                    local _beg_x=0 local x=_beg_x local _end_x=-192 local _w_x=0 local _d_w_x=1/(61-1)
                    local _beg_y=-100 local y=_beg_y local _end_y=-500 local _w_y=0 local _d_w_y=1/(61-1)
                    local _beg_hv=1 local hv=_beg_hv local _end_hv=3 local _w_hv=0 local _d_w_hv=1/(61-1)
                    local _beg_alpha=255 local alpha=_beg_alpha local _end_alpha=0 local _w_alpha=0 local _d_w_alpha=1/(61-1)
                    for _=1,61 do
                        self.x=x
                        self.y=y
                        self.hscale=hv
                        self.vscale=hv
                        self._a=alpha
                        task._Wait(1)
                        _w_x=_w_x+_d_w_x if _w_x<0.5 then x=2*(_end_x-_beg_x)*_w_x^2+_beg_x else x=(_end_x-_beg_x)*(-2*_w_x^2+4*_w_x-1)+_beg_x end
                        _w_y=_w_y+_d_w_y if _w_y<0.5 then y=2*(_end_y-_beg_y)*_w_y^2+_beg_y else y=(_end_y-_beg_y)*(-2*_w_y^2+4*_w_y-1)+_beg_y end
                        _w_hv=_w_hv+_d_w_hv if _w_hv<0.5 then hv=2*(_end_hv-_beg_hv)*_w_hv^2+_beg_hv else hv=(_end_hv-_beg_hv)*(-2*_w_hv^2+4*_w_hv-1)+_beg_hv end
                        _w_alpha=_w_alpha+_d_w_alpha if _w_alpha<0.5 then alpha=2*(_end_alpha-_beg_alpha)*_w_alpha^2+_beg_alpha else alpha=(_end_alpha-_beg_alpha)*(-2*_w_alpha^2+4*_w_alpha-1)+_beg_alpha end
                    end
                end
            end)
            lasttask=task.New(self,function()
                for _=1,60 do
                    last=New(_editor_class["Comet_Fox_ct"],self.x,self.y,0,0)
                    task._Wait(1)
                end
            end)
        else
            lasttask=task.New(self,function()
                do
                    local _beg_alpha=255 local alpha=_beg_alpha local _end_alpha=0 local _d_alpha=(_end_alpha-_beg_alpha)/(11-1)
                    for _=1,11 do
                        self._a=alpha
                        task._Wait(1)
                        alpha=alpha+_d_alpha
                    end
                end
                _del(self,true)
            end)
        end
    end)
    lasttask=task.New(self,function()
        if flag_img==0 then
            self.img="image:Comet_Fox_smith"
        else
            self.img="image:Comet_Fox_Aka"
        end
    end)
end
-- archive space: Comet_Fox\boss_scbg\
_LoadImageFromFile('image:'..'Comet_Fox_smith_bga','Comet_Fox\\boss_scbg\\Comet_Fox_smith_bga.png',true,0,0,false,0)
_LoadImageFromFile('image:'..'Comet_Fox_smith_bgb','Comet_Fox\\boss_scbg\\Comet_Fox_smith_bgb.png',true,0,0,false,0)
_LoadImageFromFile('image:'..'Comet_Fox_aka_bga','Comet_Fox\\boss_scbg\\Comet_Fox_aka_bga.png',true,0,0,false,0)
_LoadImageFromFile('image:'..'Comet_Fox_aka_bgb','Comet_Fox\\boss_scbg\\Comet_Fox_aka_bgb.png',true,0,0,false,0)
_editor_class["Comet_Fox_smith_scbg"]=Class(_spellcard_background)
_editor_class["Comet_Fox_smith_scbg"].init=function(self)
    _spellcard_background.init(self)
    _spellcard_background.AddLayer(self,"image:Comet_Fox_smith_bga",false,0,0,0,0,0,0,"mul+rev",0.6,0.6,
        function(self)
            self.task={}
            self._a=0
            lasttask=task.New(self,function()
                do local ra,_d_ra=(0),(255/60) for _=1,61 do
                    self._a=ra
                    task._Wait(1)
                ra=ra+_d_ra end end
            end)
        end,
        function(self)
            task.Do(self)
        end,
        function(self)
        end
    )
    _spellcard_background.AddLayer(self,"image:Comet_Fox_smith_bgb",true,0,0,0,0,0.3,0,"mul+add",1,1,
        function(self)
            self.task={}
            self._a=0
            lasttask=task.New(self,function()
                do local a,_d_a=(0),(100/60) for _=1,61 do
                    self._a=a
                    task._Wait(1)
                a=a+_d_a end end
            end)
        end,
        function(self)
            task.Do(self)
        end,
        function(self)
        end
    )
end
_editor_class["Comet_Fox_aka_scbg"]=Class(_spellcard_background)
_editor_class["Comet_Fox_aka_scbg"].init=function(self)
    _spellcard_background.init(self)
    _spellcard_background.AddLayer(self,"image:Comet_Fox_aka_bgb",true,0,0,0,0,-0.3,0,"mul+rev",1,1,
        function(self)
            self.task={}
            self.a=0
            lasttask=task.New(self,function()
                do local a,_d_a=(0),(122/30) for _=1,31 do
                    self.a=a
                    task._Wait(1)
                a=a+_d_a end end
            end)
        end,
        function(self)
            task.Do(self)
        end,
        function(self)
        end
    )
    _spellcard_background.AddLayer(self,"image:Comet_Fox_aka_bgb",true,0,0,0,0,0.3,0,"mul+add",1,1,
        function(self)
            self.task={}
            self.a=0
            lasttask=task.New(self,function()
                do local a,_d_a=(0),(122/30) for _=1,31 do
                    self.a=a
                    task._Wait(1)
                a=a+_d_a end end
            end)
        end,
        function(self)
            task.Do(self)
        end,
        function(self)
        end
    )
    _spellcard_background.AddLayer(self,"image:Comet_Fox_aka_bga",false,0,0,0,0,0,0.1,"",1.5,1.5,
        function(self)
            self.task={}
            self.a=0
            lasttask=task.New(self,function()
                do local ra,_d_ra=(0),(255/30) for _=1,31 do
                    self.a=ra
                    self.r=ra/2
                    self.g=ra/2
                    self.b=ra/2
                    task._Wait(1)
                ra=ra+_d_ra end end
            end)
        end,
        function(self)
            task.Do(self)
        end,
        function(self)
        end
    )
end
-- archive space: Comet_Fox\eff\
Include'Comet_Fox\\eff\\boss_other.lua'
_LoadImageFromFile('image:'..'Comet_Fox_Cherry','Comet_Fox\\eff\\Comet_Fox_Cherry.png',true,0,0,false,0)
_LoadImageFromFile('image:'..'magic','Comet_Fox\\eff\\magic.png',true,0,0,false,0)
_editor_class["tuoying"]=Class(_object)
_editor_class["tuoying"].init=function(self,_x,_y,img,r,g,b)
    self.x,self.y=_x,_y
    self.img="img_void"
    self.layer=LAYER_ENEMY
    self.group=GROUP_GHOST
    self.hide=false
    self.bound=false
    self.navi=false
    self.hp=10
    self.maxhp=10
    self.colli=false
    self._servants={}
    self._blend,self._a,self._r,self._g,self._b='',255,255,255,255
    self.img=img
    _object.set_color(self,"mul+add",255,r,g,b)
    lasttask=task.New(self,function()
        do
            local _beg_a=255 local a=_beg_a local _end_a=0 local _d_a=(_end_a-_beg_a)/(31-1)
            for _=1,31 do
                self._a=a
                task._Wait(1)
                a=a+_d_a
            end
        end
        _del(self,true)
    end)
end
_editor_class["magicbg"]=Class(_object)
_editor_class["magicbg"].init=function(self,_x,_y)
    self.x,self.y=_x,_y
    self.img="image:magic"
    self.layer=LAYER_ENEMY-5
    self.group=GROUP_INDES
    self.hide=false
    self.bound=false
    self.navi=true
    self.hp=10
    self.maxhp=10
    self.colli=false
    self._servants={}
    self._blend,self._a,self._r,self._g,self._b='',255,255,255,255
    lasttask=task.New(self,function()
        _object.set_color(self,"mul+add",255,0,190,255)
        do
            local _beg_hv=0 local hv=_beg_hv local _end_hv=0.75 local _w_hv=0 local _d_w_hv=1/(91)
            for _=1,91 do
                self.hscale=hv
                self.vscale=hv
                task._Wait(1)
                _w_hv=_w_hv+_d_w_hv if _w_hv<0.5 then hv=2*(_end_hv-_beg_hv)*_w_hv^2+_beg_hv else hv=(_end_hv-_beg_hv)*(-2*_w_hv^2+4*_w_hv-1)+_beg_hv end
            end
        end
    end)
    lasttask=task.New(self,function()
        for _=1,_infinite do
            self.x=_boss.x
            self.y=_boss.y
            if _boss.hp<0.00001 then
                _del(self,true)
            else
            end
            task._Wait(1)
        end
    end)
    lasttask=task.New(self,function()
        do local rot,_d_rot=(0),(3) for _=1,_infinite do
            self.rot=rot
            task._Wait(1)
        rot=rot+_d_rot end end
    end)
end
_editor_tasks["atk_n1_at1"]=function()
    return function()
        local self=task.GetSelf()
        do
            local a1=ran:Float(0,360) local _d_a1=(1.6)
            local a2=ran:Float(0,360) local _d_a2=(90)
            for _=1,_infinite do
                do
                    local _beg_a=0 local a=_beg_a local _end_a=360 local _d_a=(_end_a-_beg_a)/(21)
                    for _=1,21 do
                        last=New(_straight,square,COLOR_BLUE,self.x,self.y,2,a+a1,false,3,false,true,0,false,0.01,a2,0,false)
                        do
                            local self = last
                            _object.set_color(self,"mul+add",255,255,255,255)
                        end
                        a=a+_d_a
                    end
                end
                PlaySound("kira00",0.1,self.x/256,true)
                task._Wait(9)
                a1=a1+_d_a1
                a2=a2+_d_a2
            end
        end
    end
end
_editor_tasks["atk_sc1_at1"]=function()
    return function()
        local self=task.GetSelf()
        for _=1,_infinite do
            do local a,_d_a=(Angle(self.x,self.y,player.x,player.y)+45),(90) for _=1,4 do
                last=New(_editor_class["sc2_bullet_ma"],self.x+120*cos(a),self.y+120*sin(a),a)
                PlaySound("tan00",0.1,self.x/256,true)
                PlaySound("kira00",0.1,self.x/256,true)
            a=a+_d_a end end
            task._Wait(180)
        end
    end
end
_editor_tasks["atk_sc1_at2"]=function()
    return function()
        local self=task.GetSelf()
        task._Wait(120)
        for _=1,_infinite do
            do
                local _beg_a=-45 local a=_beg_a local _end_a=45 local _d_a=(_end_a-_beg_a)/(10-1)
                for _=1,10 do
                    last=New(_editor_class["sc2_bullet_fire"],self.x,self.y,a)
                    a=a+_d_a
                end
            end
            PlaySound("kira01",0.1,self.x/256,true)
            task._Wait(120)
        end
    end
end
_editor_class["sc2_bullet_ma"]=Class(_object)
_editor_class["sc2_bullet_ma"].init=function(self,_x,_y,a)
    self.x,self.y=_x,_y
    self.img="img_void"
    self.layer=LAYER_ENEMY_BULLET
    self.group=GROUP_ENEMY_BULLET
    self.hide=false
    self.bound=false
    self.navi=true
    self.hp=10
    self.maxhp=10
    self.colli=false
    self._servants={}
    self._blend,self._a,self._r,self._g,self._b='',255,255,255,255
    SetV2(self,0,a,true,false)
    lasttask=task.New(self,function()
        task._Wait(60)
        _del(self,true)
    end)
    lasttask=task.New(self,function()
        if self.x<0 then
            do local a1,_d_a1=(a),(360/27) for _=1,27 do
                last=New(_editor_class["sc2_bullet_ser"],self.x,self.y,a1,-0.4)
            a1=a1+_d_a1 end end
        else
        end
        if self.x>0 then
            do local a1,_d_a1=(a),(360/27) for _=1,27 do
                last=New(_editor_class["sc2_bullet_ser"],self.x,self.y,a1,0.4)
            a1=a1+_d_a1 end end
        else
        end
    end)
end
_editor_class["sc2_bullet_ser"]=Class(bullet)
_editor_class["sc2_bullet_ser"].init=function(self,_x,_y,a,ap)
bullet.init(self,square,COLOR_DEEP_BLUE,true,true)
self.x,self.y=_x,_y
    self.bound=false
    _object.set_color(self,"mul+add",255,255,255,255)
    SetV2(self,1,a,true,false)
    lasttask=task.New(self,function()
        task._Wait(60)
        PlaySound("kira00",0.1,self.x/256,true)
        do
            local _beg_v=0 local v=_beg_v local _end_v=0.6 local _d_v=(_end_v-_beg_v)/(61-1)
            for _=1,61 do
                _set_a(self,v,-90,false)
                task._Wait(1)
                v=v+_d_v
            end
        end
        task._Wait(600)
        self.bound=true
    end)
    lasttask=task.New(self,function()
        for _=1,_infinite do
            SetV2(self,1,self.rot+ap,true,false)
            task._Wait(1)
        end
    end)
end
_editor_class["sc2_bullet_fire"]=Class(bullet)
_editor_class["sc2_bullet_fire"].init=function(self,_x,_y,a)
bullet.init(self,water_drop,COLOR_BLUE,false,true)
self.x,self.y=_x,_y
    self.timer=11
    SetV2(self,2,a+180,true,true)
end
_editor_class["sc2_bullet_fire"].frame=function(self)
    self.class.base.frame(self)
    if self.x<-192 then
        ChangeBulletImage(self,water_drop,COLOR_RED)
        PlaySound("kira00",0.1,self.x/256,true)
        SetV2(self,ran:Float(1,2),0,true,true)
    else
    end
    if self.x>192 then
        ChangeBulletImage(self,water_drop,COLOR_RED)
        PlaySound("kira00",0.1,self.x/256,true)
        SetV2(self,ran:Float(1,2),0,true,true)
    else
    end
    if self.y>224 then
        ChangeBulletImage(self,water_drop,COLOR_RED)
        PlaySound("kira00",0.1,self.x/256,true)
        SetV2(self,ran:Float(1,2),0,true,true)
    else
    end
end
_editor_class["CF_smith"]=Class(boss)
_editor_class["CF_smith"].cards={}
_editor_class["CF_smith"].name="Diane·Smith"
_editor_class["CF_smith"].bgm="bgm:Comet_Fox_music"
_editor_class["CF_smith"]._bg=gensokyosora_background
_editor_class["CF_smith"].difficulty="All"
_editor_class["CF_smith"].init=function(self,cards)
boss.init(self,240,384,_editor_class["CF_smith"].name,cards,New(_editor_class["Comet_Fox_smith_scbg"]),_editor_class["CF_smith"].difficulty)
    self._wisys = BossWalkImageSystem(self)
    self._wisys:SetImage("Comet_Fox\\eff\\Comet_Fox_Smith_enm1.png",4,5,{5,5,5,5},{1,1,2},6,16,16)
    _boss.fxr=0
    _boss.fxg=120
    _boss.fxb=255
end
--[[ 1]]

_tmp_sc=boss.card.New("",2,5,100,1000,{0,0,0},false)
function _tmp_sc:before()
    task.MoveTo(0,120,60,MOVE_ACC_DEC)
    ui.lstg_weekly.SetFlag(true, false, false)
    ui.lstg_weekly.SetEditor("Comet_Fox")
end
function _tmp_sc:init()
    lasttask=task.New(self,function()
        boss.cast(self,_infinite)
        New(boss_cast_ef_in,0,120,"image:Comet_Fox_Cherry",122,122,255,"ch02")
        task._Wait(60)
        New(boss_cast_ef_out,0,120,"image:Comet_Fox_Cherry",122,122,255,"enep02")
        lasttask=task.New(self,_editor_tasks["atk_n1_at1"]())
    end)
end
function _tmp_sc:beforedel()
end
function _tmp_sc:del()
end
function _tmp_sc:after()
end
_tmp_sc.perform=false
table.insert(_editor_class["CF_smith"].cards,_tmp_sc)

--[[ 1]]

_tmp_sc=boss.card.New("「108张符札灭咒」",2,5,70,1500,{0,0,0},false)
function _tmp_sc:before()
    ui.lstg_weekly.SetFlag(true, false, false)
    ui.lstg_weekly.SetEditor("Comet_Fox")
end
function _tmp_sc:init()
    lasttask=task.New(self,function()
        boss.show_aura(self,false)
        New(boss_cast_ef_in,0,120,"image:Comet_Fox_Cherry",122,122,255,"ch02")
        last=New(_editor_class["Comet_Fox_ct"],382, -100,1,0)
        task.MoveTo(0,120,60,MOVE_NORMAL)
        New(boss_cast_ef_out,0,120,"image:Comet_Fox_Cherry",122,122,255,"enep02")
        task._Wait(30)
        boss.cast(self,_infinite)
        PlaySound("boon01",10,self.x/256,true)
        last=New(_editor_class["magicbg"],self.x,self.y)
        task._Wait(90)
        lasttask=task.New(self,_editor_tasks["atk_sc1_at1"]())
        lasttask=task.New(self,_editor_tasks["atk_sc1_at2"]())
    end)
end
function _tmp_sc:beforedel()
end
function _tmp_sc:del()
end
function _tmp_sc:after()
end
_tmp_sc.perform=false
table.insert(_editor_class["CF_smith"].cards,_tmp_sc)
table.insert(_sc_table,{"CF_smith","「108张符札灭咒」",_tmp_sc,#_editor_class["CF_smith"].cards,false})
stage.group.AddStage(__WEEK_ID,'Comet_Fox@'..__WEEK_ID,{lifeleft=7,power=400,faith=50000,bomb=3},true)
stage.group.DefStageFunc('Comet_Fox@'..__WEEK_ID,'init',function(self)
    _init_item(self)
    difficulty=self.group.difficulty
    New(mask_fader,'open')
    if jstg then jstg.CreatePlayers() else New(_G[lstg.var.player_name]) end
    lasttask=task.New(self,function()
        LoadMusicRecord("bgm:Comet_Fox_smith_theme")
        _play_music("bgm:Comet_Fox_smith_theme")
        New(gensokyosora_background)
        task._Wait(60)
        local _boss_wait=true
        local _ref=New(_editor_class["CF_smith"],_editor_class["CF_smith"].cards)
        last=_ref
        if _boss_wait then while IsValid(_ref) do task.Wait() end end
        task._Wait(180)
    end)
    ui.lstg_weekly.stage_init(self)
    task.New(self,function()
        while coroutine.status(self.task[1])~='dead' do task.Wait() end
        stage.group.FinishReplay()
        New(mask_fader,'close')
        task.New(self,function()
            local _,bgm=EnumRes('bgm')
            for i=1,30 do
                for _,v in pairs(bgm) do
                    if GetMusicState(v)=='playing' then
                        SetBGMVolume(v,1-i/30)
                    end
                end
                task.Wait()
            end
        end)
        task.Wait(30)
        stage.group.FinishStage()
    end)
end)
