-- Generated by LuaSTG Editor Sharp
-- Mod name: 
_author = "LuaSTG User"
_mod_version = 4096
_allow_practice = true
_allow_sc_practice =true
Include'le03_7.lua'
MusicRecord('bgm:'..'LHX_bgm','LHX_bgm.ogg',253,216.75)
_LoadImageFromFile('image:'..'LHX_scbg_a','LHX_scbg_a (1).png',true,0,0,false,0)
_LoadImageFromFile('image:'..'LHX_scbg_b','LHX_scbg_b.png',true,0,0,false,0)
_LoadImageFromFile('image:'..'LHX_scbg_c','LHX_scbg_c.png',true,0,0,false,0)
_LoadImageFromFile('image:'..'LHX_boss_sc','LHX_boss_sc.png',true,0,0,false,0)
_LoadImageGroupFromFile('image:'..'LHX_eff','LHX_eff.png',true,4,1,0,0,false)
_LoadImageFromFile('image:'..'music_07_01','music_07_01.png',true,0,0,false,0)
_editor_class["LHX_bg"]=Class(_spellcard_background)
_editor_class["LHX_bg"].init=function(self)
    _spellcard_background.init(self)
    _spellcard_background.AddLayer(self,"image:LHX_scbg_b",false,0,0,0,0,0,0,"",1,1,
        function(self)
            self.task={}
            lasttask=task.New(self,function()
                self._r = 200 self._g = 200 self._b = 200 self._blend = 'mul+add'
                do
                    local _h_alpha=(200-(100))/2 local _t_alpha=(200+(100))/2 local alpha=_h_alpha*sin(90)+_t_alpha local _w_alpha=90 local _d_w_alpha=0.5
                    for _=1,_infinite do
                        self.a = alpha
                        task._Wait(1)
                        _w_alpha=_w_alpha+_d_w_alpha alpha=_h_alpha*sin(_w_alpha)+_t_alpha
                    end
                end
            end)
        end,
        function(self)
            task.Do(self)
        end,
        function(self)
        end
    )
    _spellcard_background.AddLayer(self,"white",false,0,0,0,0,0,0,"mul+alpha",30,30,
        function(self)
            self.task={}
            self.a = 100 self._r = 200 self._g = 200 self._b = 200 self._blend = 'mul+alpha'
        end,
        function(self)
            task.Do(self)
        end,
        function(self)
        end
    )
    _spellcard_background.AddLayer(self,"image:LHX_scbg_a",false,0,0,0,0,0,0,"mul+add",1,1,
        function(self)
            self.task={}
            self.a = 122
            self.r = 255
            self.g = 255
            self.b = 255
            self.blend = 'add+add'
            lasttask=task.New(self,function()
                do
                    local rot=0 local _d_rot=(-0.5)
                    for _=1,_infinite do
                        self.x = 180 * cos(rot)
                        self.y = 180 * sin(rot)
                        self.rot = rot
                        task._Wait(1)
                        rot=rot+_d_rot
                    end
                end
            end)
        end,
        function(self)
            task.Do(self)
        end,
        function(self)
        end
    )
    _spellcard_background.AddLayer(self,"image:LHX_scbg_c",false,0,0,0,0,0,0.5,"mul+alpha",1.5,1.5,
        function(self)
            self.task={}
            self.a = 168
        end,
        function(self)
            task.Do(self)
        end,
        function(self)
        end
    )
end
_editor_class["LHX_sc_ph"]=Class(_object)
_editor_class["LHX_sc_ph"].init=function(self,_x,_y)
    self.x,self.y=_x,_y
    self.img="image:LHX_boss_sc"
    self.layer=LAYER_ENEMY
    self.group=GROUP_GHOST
    self.hide=false
    self.bound=true
    self.navi=false
    self.hp=10
    self.maxhp=10
    self.colli=true
    self._servants={}
    self._blend,self._a,self._r,self._g,self._b='',255,255,255,255
    _object.set_color(self,"mul+alpha",0,255,255,255)
    lasttask=task.New(self,function()
        local rot = 30
        do
            local _beg_a=5 local a=_beg_a local _end_a=255 local _w_a=0 local _d_w_a=1/(30)
            local _beg_r=rot local r=_beg_r local _end_r=rot-30 local _w_r=0 local _d_w_r=1/(30)
            local _beg_y=-60 local y=_beg_y local _end_y=-30 local _w_y=0 local _d_w_y=1/(30)
            local _beg_scale=0 local scale=_beg_scale local _end_scale=0.7 local _w_scale=0 local _d_w_scale=1/(30)
            for _=1,30 do
                _object.set_color(self,"mul+alpha",a,255,255,255)
                self.rot = r
                self.y =y
                self.hscale = scale
                self.vscale = scale
                task._Wait(1)
                _w_a=_w_a+_d_w_a a=(_beg_a-_end_a)*(_w_a-1)^2+_end_a
                _w_r=_w_r+_d_w_r r=(_beg_r-_end_r)*(_w_r-1)^2+_end_r
                _w_y=_w_y+_d_w_y y=(_beg_y-_end_y)*(_w_y-1)^2+_end_y
                _w_scale=_w_scale+_d_w_scale scale=(_beg_scale-_end_scale)*(_w_scale-1)^2+_end_scale
            end
        end
        do
            local _beg_a=255 local a=_beg_a local _end_a=0 local _w_a=0  local _d_w_a=1/(120)
            local _beg_y=-30 local y=_beg_y local _end_y=90 local _w_y=0  local _d_w_y=1/(120)
            for _=1,120 do
                _object.set_color(self,"mul+alpha",a,255,255,255)
                self.y =y
                task._Wait(1)
                _w_a=_w_a+_d_w_a a=(_end_a-_beg_a)*_w_a^2+_beg_a
                _w_y=_w_y+_d_w_y y=(_end_y-_beg_y)*_w_y^2+_beg_y
            end
        end
        _del(self,true)
    end)
end
_editor_class["LHX_sc_eff2"]=Class(_object)
_editor_class["LHX_sc_eff2"].init=function(self,_x,_y,v,rot,hscale,vscale,rot1,rot2)
    self.x,self.y=_x,_y
    self.img="image:LHX_eff4"
    self.layer=LAYER_ENEMY_BULLET
    self.group=GROUP_GHOST
    self.hide=false
    self.bound=true
    self.navi=false
    self.hp=10
    self.maxhp=10
    self.colli=true
    self._servants={}
    self._blend,self._a,self._r,self._g,self._b='',255,255,255,255
    self.hscale = 0
    self.vscale = 0
    lasttask=task.New(self,function()
        SetV2(self,v,rot,true,false)
        _set_a(self,-v/60,rot,false)
        task._Wait(60)
        _set_a(self,0,0,false)
        task._Wait(60)
        _del(self,true)
    end)
    lasttask=task.New(self,function()
        do
            local _beg_r=rot1 local r=_beg_r  local _w_r=-90 local _end_r=rot1+90*rot2 local _d_w_r=180/(120-1)
            local _beg_hs=0 local hs=_beg_hs local _end_hs=hscale local _w_hs=0 local _d_w_hs=1/(120-1)
            local _beg_vs=0 local vs=_beg_vs local _end_vs=vscale local _w_vs=0 local _d_w_vs=1/(120-1)
            for _=1,120 do
                self.rot = r self.hscale = hs self.vscale = vs
                task._Wait(1)
                _w_r=_w_r+_d_w_r r=(_end_r-_beg_r)/2*sin(_w_r)+((_end_r+_beg_r)/2)
                _w_hs=_w_hs+_d_w_hs hs=(_beg_hs-_end_hs)*(_w_hs-1)^2+_end_hs
                _w_vs=_w_vs+_d_w_vs vs=(_beg_vs-_end_vs)*(_w_vs-1)^2+_end_vs
            end
        end
    end)
    lasttask=task.New(self,function()
        task._Wait(45)
        self.layer = LAYER_TOP + 10
        self.img="white"        _object.set_color(self,"mul+sub",255,255,255,255)
        task._Wait(60)
        self.img="image:LHX_eff4"        _object.set_color(self,"",255,255,255,255)
    end)
end
_editor_class["LHX_sc_eff"]=Class(_object)
_editor_class["LHX_sc_eff"].init=function(self,_x,_y,v,rot,r,g,b)
    self.x,self.y=_x,_y
    self.img="img_void"
    self.layer=LAYER_TOP+5
    self.group=GROUP_GHOST
    self.hide=false
    self.bound=false
    self.navi=false
    self.hp=10
    self.maxhp=10
    self.colli=true
    self._servants={}
    self._blend,self._a,self._r,self._g,self._b='',255,255,255,255
    SetV2(self,v,rot,true,false)
    lasttask=task.New(self,function()
        _set_a(self,-v/60,rot,false)
        task._Wait(60)
    end)
    local st = ran:Int(1,4)
    local drot = -1 + 2*ran:Int(0,1)
    local rot = ran:Int(0,360)
    self.hscale = 1.5
    self.vscale = 1.5
    if st == 1 then
        self.img="image:LHX_eff1"    elseif st == 2 then
        self.img="image:LHX_eff2"    elseif st == 3 then
        self.img="image:LHX_eff3"    else
        self.img="image:LHX_eff4"    end
    _object.set_color(self,"mul+add",0,r,g,b)
    lasttask=task.New(self,function()
        local maxa = ran:Int(120,200)
        do
            local _beg_a=5 local a=_beg_a local _end_a=maxa local _w_a=0 local _d_w_a=1/(30)
            local _beg_angle=rot local angle=_beg_angle local _end_angle=rot+drot*30 local _w_angle=0 local _d_w_angle=1/(30)
            for _=1,30 do
                _object.set_color(self,"mul+add",a,r,g,b)
                self.rot = angle
                task._Wait(1)
                _w_a=_w_a+_d_w_a a=(_beg_a-_end_a)*(_w_a-1)^2+_end_a
                _w_angle=_w_angle+_d_w_angle angle=(_beg_angle-_end_angle)*(_w_angle-1)^2+_end_angle
            end
        end
        do
            local _beg_a=maxa local a=_beg_a local _end_a=0 local _w_a=0  local _d_w_a=1/(90)
            local _beg_angle=rot+drot*30 local angle=_beg_angle local _end_angle=rot+drot*60 local _w_angle=0 local _d_w_angle=1/(90)
            for _=1,90 do
                _object.set_color(self,"mul+add",a,r,g,b)
                self.rot = angle
                task._Wait(1)
                _w_a=_w_a+_d_w_a a=(_end_a-_beg_a)*_w_a^2+_beg_a
                _w_angle=_w_angle+_d_w_angle angle=(_beg_angle-_end_angle)*(_w_angle-1)^2+_end_angle
            end
        end
        _del(self,true)
    end)
end
_editor_class["LHX_sc_eff3"]=Class(_object)
_editor_class["LHX_sc_eff3"].init=function(self,_x,_y,r,g,b)
    self.x,self.y=_x,_y
    self.img="parimg12"
    self.layer=LAYER_TOP-5
    self.group=GROUP_GHOST
    self.hide=false
    self.bound=false
    self.navi=false
    self.hp=10
    self.maxhp=10
    self.colli=false
    self._servants={}
    self._blend,self._a,self._r,self._g,self._b='',255,255,255,255
    do
        local __terminated = false
        local __terminateCount = 0
        local _0 = 0
        local _1 = 0
        task.New(self, function()
            local self = task.GetSelf()
            task.Wait(0)
            local i = 0
            local offset = 0
            local curr, ibeg, ky, kx
            local prev = 0
            local target = offset
            curr = 0
            ibeg = i
            target = 0 + offset
            kx = target - ibeg
            ky = curr - prev
            while i < target do
                _0 = prev + ky * (i - ibeg) / kx
                i = i + 1
                task.Wait()
            end
            _0 = curr
            prev = curr
            curr = 255
            ibeg = i
            target = 15 + offset
            kx = target - ibeg
            ky = curr - prev
            while i < target do
                _0 = prev + ky * (i - ibeg) / kx
                i = i + 1
                task.Wait()
            end
            _0 = curr
            prev = curr
            curr = 0
            ibeg = i
            target = 90 + offset
            kx = target - ibeg
            ky = curr - prev
            while i < target do
                _0 = prev + ky * (i - ibeg) / kx
                i = i + 1
                task.Wait()
            end
            _0 = curr
            prev = curr
            offset = target
            __terminateCount = __terminateCount + 1
        end)
        task.New(self, function()
            local self = task.GetSelf()
            task.Wait(0)
            local i = 0
            local offset = 0
            local curr, ibeg, ky, kx
            local prev = 0
            local target = offset
            curr = 0
            ibeg = i
            target = 0 + offset
            kx = target - ibeg
            ky = curr - prev
            while i < target do
                _1 = prev + ky * (i - ibeg) / kx
                i = i + 1
                task.Wait()
            end
            _1 = curr
            prev = curr
            curr = 15
            ibeg = i
            target = 60 + offset
            kx = target - ibeg
            ky = curr - prev
            while i < target do
                _1 = prev + ky * (i - ibeg) / kx
                i = i + 1
                task.Wait()
            end
            _1 = curr
            prev = curr
            offset = target
            __terminateCount = __terminateCount + 1
        end)
        task.New(self, function()
            local self = task.GetSelf()
            for _ = 1, _infinite do
                _object.set_color(self, "mul+add", _0, r, g, b) self.hscale = _1 self.vscale = _1
                if __terminated or __terminateCount >= 2 then break end
                task.Wait()
            end
        end)
    end
    lasttask=task.New(self,function()
        task._Wait(120)
        _del(self,true)
    end)
end
_editor_class["LHX_musicback"]=Class(_object)
_editor_class["LHX_musicback"].init=function(self,_x,_y)
    self.x,self.y=_x,_y
    self.img="white"
    self.layer=LAYER_ENEMY_BULLET_EF+5
    self.group=GROUP_GHOST
    self.hide=false
    self.bound=true
    self.navi=false
    self.hp=10
    self.maxhp=10
    self.colli=true
    self._servants={}
    self._blend,self._a,self._r,self._g,self._b='',255,255,255,255
    last=New(_editor_class["LHX_musicinfo"],self.x,self.y)
    _object.set_color(self,"mul+alpha",0,0,0,0)
    self.hscale = 16 self.vscale = 2
    lasttask=task.New(self,function()
        do
            local _beg_alpha=0 local alpha=_beg_alpha local _end_alpha=127 local _w_alpha=0 local _d_w_alpha=1/(30)
            for _=1,30 do
                _object.set_color(self,"mul+alpha",alpha,0,0,0)
                task._Wait(1)
                _w_alpha=_w_alpha+_d_w_alpha alpha=(_beg_alpha-_end_alpha)*(_w_alpha-1)^2+_end_alpha
            end
        end
        task._Wait(180)
        do
            local _beg_alpha=127 local alpha=_beg_alpha local _end_alpha=0 local _w_alpha=0 local _d_w_alpha=1/(30)
            for _=1,30 do
                _object.set_color(self,"mul+alpha",alpha,0,0,0)
                task._Wait(1)
                _w_alpha=_w_alpha+_d_w_alpha alpha=(_beg_alpha-_end_alpha)*(_w_alpha-1)^2+_end_alpha
            end
        end
        self.x = 400
        _del(self,true)
    end)
end
_editor_class["LHX_musicinfo"]=Class(_object)
_editor_class["LHX_musicinfo"].init=function(self,_x,_y)
    self.x,self.y=_x,_y
    self.img="image:music_07_01"
    self.layer=LAYER_ENEMY_BULLET_EF+5
    self.group=GROUP_GHOST
    self.hide=false
    self.bound=true
    self.navi=false
    self.hp=10
    self.maxhp=10
    self.colli=true
    self._servants={}
    self._blend,self._a,self._r,self._g,self._b='',255,255,255,255
    self.hscale = 0.35 self.vscale = 0.35
    lasttask=task.New(self,function()
        do
            local _beg_alpha=0 local alpha=_beg_alpha local _end_alpha=255 local _w_alpha=0 local _d_w_alpha=1/(30)
            for _=1,30 do
                _object.set_color(self,"mul+alpha",alpha,255,255,255)
                task._Wait(1)
                _w_alpha=_w_alpha+_d_w_alpha alpha=(_beg_alpha-_end_alpha)*(_w_alpha-1)^2+_end_alpha
            end
        end
        task._Wait(180)
        do
            local _beg_alpha=255 local alpha=_beg_alpha local _end_alpha=0 local _w_alpha=0 local _d_w_alpha=1/(30)
            for _=1,30 do
                _object.set_color(self,"mul+alpha",alpha,255,255,255)
                task._Wait(1)
                _w_alpha=_w_alpha+_d_w_alpha alpha=(_beg_alpha-_end_alpha)*(_w_alpha-1)^2+_end_alpha
            end
        end
        self.x = 400
        _del(self,true)
    end)
end
_editor_class["LHX_charge_particle"]=Class(_object)
_editor_class["LHX_charge_particle"].init=function(self,_x,_y,st,rot,size,omiga,a0,a1,v0,a,t)
    self.x,self.y=_x,_y
    self.img="img_void"
    self.layer=LAYER_ENEMY_BULLET
    self.group=GROUP_GHOST
    self.hide=false
    self.bound=false
    self.navi=false
    self.hp=10
    self.maxhp=10
    self.colli=true
    self._servants={}
    self._blend,self._a,self._r,self._g,self._b='',255,255,255,255
    self._a = 0
    self.omiga = omiga
    self.hscale = size self.vscale = size
    if st <= 4 then self.img = "image:LHX_eff"..st end
    SetV2(self,v0,rot,true,false)
    _set_a(self,a,rot+180,false)
    lasttask=task.New(self,function()
        do
            local _beg_alpha=a0 local alpha=_beg_alpha local _end_alpha=a1 local _w_alpha=0  local _d_w_alpha=1/(t-1)
            for _=1,t do
                _object.set_color(self,"mul+add",alpha,255,122,0)
                task._Wait(1)
                _w_alpha=_w_alpha+_d_w_alpha alpha=(_end_alpha-_beg_alpha)*_w_alpha^2+_beg_alpha
            end
        end
        _del(self,true)
    end)
end
_editor_class["LHX_charge_bubble"]=Class(_object)
_editor_class["LHX_charge_bubble"].init=function(self,_x,_y,hsc0,hsc1,vsc0,vsc1,t,r,g,b,a0,a1)
    self.x,self.y=_x,_y
    self.img="parimg12"
    self.layer=LAYER_ENEMY_BULLET_EF+5
    self.group=GROUP_GHOST
    self.hide=false
    self.bound=false
    self.navi=false
    self.hp=10
    self.maxhp=10
    self.colli=true
    self._servants={}
    self._blend,self._a,self._r,self._g,self._b='',255,255,255,255
    lasttask=task.New(self,function()
        do
            local _beg_alpha=a0 local alpha=_beg_alpha local _end_alpha=a1 local _d_alpha=(_end_alpha-_beg_alpha)/(t-1)
            local _beg_hs=hsc0 local hs=_beg_hs local _end_hs=hsc1 local _d_hs=(_end_hs-_beg_hs)/(t-1)
            local _beg_vs=vsc0 local vs=_beg_vs local _end_vs=vsc1 local _d_vs=(_end_vs-_beg_vs)/(t-1)
            for _=1,t do
                _object.set_color(self,"mul+add",alpha,r,g,b)
                self.hscale = hs self.vscale = vs
                task._Wait(1)
                alpha=alpha+_d_alpha
                hs=hs+_d_hs
                vs=vs+_d_vs
            end
        end
        _del(self,true)
    end)
end
_editor_tasks["sc_open"]=function(r,g,b)
    return function()
        local self=task.GetSelf()
        PlaySound("old_cat00",0.1,self.x/256,false)
        misc.ShakeScreen(60,2)
        last=New(_editor_class["LHX_sc_eff2"],0,0,6,135,8,8,90,-1)
        last=New(_editor_class["LHX_sc_eff2"],0,0,6,225,6,6,48,1)
        last=New(_editor_class["LHX_sc_eff2"],0,0,6,315,11,11,7,1)
        last=New(_editor_class["LHX_sc_eff2"],0,0,6,45,7,7,60,1)
        last=New(_editor_class["LHX_sc_ph"],0,-60)
        lasttask=task.New(self,function()
            for _=1,3 do
                last=New(_editor_class["LHX_sc_eff3"],0,60,r,g,b)
                task._Wait(5)
            end
        end)
        for _=1,15 do
            for _=1,10 do
                local angle = ran:Float(0,360)
                last=New(_editor_class["LHX_sc_eff"],0,0,ran:Float(6,8),angle,r,g,b)
            end
            task._Wait(1)
        end
    end
end
_editor_tasks["LHX_charge"]=function(x,y,d,mode)
    return function()
        local self=task.GetSelf()
        if mode == "_cast_in_" then
            PlaySound("ch02",0.1,self.x/256,false)
            for _=1,30 do
                for _=1,3 do
                    local a = ran:Float(0,360) local rnum = ran:Float(0.8,1)
                    last=New(_editor_class["LHX_charge_particle"],x+d*cos(a)*rnum,y+d*sin(a)*rnum,ran:Int(1,4), a, ran:Float(0.9,1.7), 2*ran:Int(0,1)-1, 0, 255, 0, d/2700*rnum, 60)
                end
                task._Wait(1)
            end
            last=New(_editor_class["LHX_charge_bubble"],x,y,d/16, 0, d/16, 0, 60, 255, 122, 0, 0, 255)
        elseif mode == "_cast_out_" then
            PlaySound("enep02",0.1,self.x/256,false)
            last=New(_editor_class["LHX_charge_bubble"],x,y,0,d/16,0,d/16,90,255,122,0,255,0)
            for _=1,180 do
                local a = ran:Float(0,360) local rnum = ran:Float(0.6,1)
                last=New(_editor_class["LHX_charge_particle"],x,y,ran:Int(1,4), a, ran:Float(0.9,2), 2*ran:Int(0,1)-1, 255, 0, d/120*rnum, d/1800*rnum, 90)
            end
        else
            PlaySound("invalid",0.1,self.x/256,false)
        end
    end
end
_editor_tasks["LHX_charge_aad"]=function(x,y,r)
    return function()
        local self=task.GetSelf()
        PlaySound("ch00",0.1,self.x/256,false)
        do local a,_d_a=(ran:Float(0,360)),(15) for _=1,24 do
            local d = r + ran:Int(-12,12) local s = ran:Float(3.5,5.5)
            last=New(_straight,grain_a,COLOR_BLUE,self.x,self.y,0,a,false,0,true,true,0,false,0,0,0,false)
            do
                local self = last
                self.colli = false
                self.bound = false
                self.vscale = 0.5
                self.timer = 11
                lasttask=task.New(self,function()
                    do
                        local _beg_dd=d local dd=_beg_dd local _end_dd=-d/4 local _d_dd=(_end_dd-_beg_dd)/(90)
                        local _beg_ss=s local ss=_beg_ss local _end_ss=0 local _d_ss=(_end_ss-_beg_ss)/(90)
                        local _h_alpha=(255-(0))/2 local _t_alpha=(255+(0))/2 local alpha=_h_alpha*sin(-90)+_t_alpha local _w_alpha=-90 local _d_w_alpha=1*360/(90)
                        for _=1,90 do
                            self.x = x + dd * cos(self.rot) self.y = y + dd * sin(self.rot)
                            self.hscale = ss
                            --_object.set_color(self,'mul+add',Color(alpha,255,255,255))
                            _object.set_color(self,"mul+add",alpha,255,255,255)
                            task._Wait(1)
                            dd=dd+_d_dd
                            ss=ss+_d_ss
                            _w_alpha=_w_alpha+_d_w_alpha alpha=_h_alpha*sin(_w_alpha)+_t_alpha
                        end
                    end
                    _del(self,false)
                end)
            end
            last=New(_straight,grain_a,COLOR_BLUE,self.x,self.y,0,a,false,0,true,true,0,false,0,0,0,false)
            do
                local self = last
                self.colli = false
                self.bound = false
                self.vscale = 1
                self.timer = 11
                self.img = "parimg1"
                lasttask=task.New(self,function()
                    do
                        local _beg_dd=d local dd=_beg_dd local _end_dd=-d/4 local _d_dd=(_end_dd-_beg_dd)/(90)
                        local _beg_ss=s*1.2 local ss=_beg_ss local _end_ss=0 local _d_ss=(_end_ss-_beg_ss)/(90)
                        local _h_alpha=(127-(0))/2 local _t_alpha=(127+(0))/2 local alpha=_h_alpha*sin(-90)+_t_alpha local _w_alpha=-90 local _d_w_alpha=1*360/(90)
                        for _=1,90 do
                            self.x = x + dd * cos(self.rot) self.y = y + dd * sin(self.rot)
                            self.hscale = ss
                            --_object.set_color(self,'mul+add',Color(alpha,255,255,255))
                            _object.set_color(self,"mul+add",alpha,200,200,255)
                            task._Wait(1)
                            dd=dd+_d_dd
                            ss=ss+_d_ss
                            _w_alpha=_w_alpha+_d_w_alpha alpha=_h_alpha*sin(_w_alpha)+_t_alpha
                        end
                    end
                    _del(self,false)
                end)
            end
        a=a+_d_a end end
    end
end
_editor_class["LHX_hint"]=Class(_object)
_editor_class["LHX_hint"].init=function(self,_x,_y,rot,width,color,r,g,b)
    self.x,self.y=_x,_y
    self.img="img_void"
    self.layer=LAYER_ENEMY_BULLET
    self.group=GROUP_GHOST
    self.hide=true
    self.bound=false
    self.navi=false
    self.hp=10
    self.maxhp=10
    self.colli=false
    self._servants={}
    self._blend,self._a,self._r,self._g,self._b='',255,255,255,255
    lasttask=task.New(self,function()
        do
            local _beg_d=0 local d=_beg_d local _end_d=width local _w_d=0 local _d_w_d=1/(8-1)
            for _=1,8 do
                do
                    last=New(_straight,grain_a,color,self.x,self.y,0,rot,false,0,true,false,0,false,0,0,0,false)
                    last.rot = rot
                    last.d = d
                    last.bound = false
                    bullet.skip_fade_in(last)
                    _connect(self,last,0,true)
                    lasttask=task.New(last,function()
                        local self=task.GetSelf()
                        self.hscale = 100 self.vscale = 0.1
                        _object.set_color(self,"mul+add",255,r,g,b)
                        do
                            local _beg_dd=0 local dd=_beg_dd local _end_dd=self.d local _w_dd=0 local _d_w_dd=1/(60-1)
                            local _beg_alpha=250 local alpha=_beg_alpha local _end_alpha=0 local _w_alpha=0  local _d_w_alpha=1/(60-1)
                            for _=1,60 do
                                _set_rel_pos(self,dd * cos(self.rot+90),dd * sin(self.rot+90),self.rot,false)
                                _object.set_color(self,"mul+add",alpha,r,g,b)
                                task._Wait(1)
                                _w_dd=_w_dd+_d_w_dd dd=(_beg_dd-_end_dd)*(_w_dd-1)^2+_end_dd
                                _w_alpha=_w_alpha+_d_w_alpha alpha=(_end_alpha-_beg_alpha)*_w_alpha^2+_beg_alpha
                            end
                        end
                        _del(self,false)
                    end)
                end
                do
                    last=New(_straight,grain_a,color,self.x,self.y,0,rot,false,0,true,false,0,false,0,0,0,false)
                    last.rot = rot
                    last.d = -d
                    last.bound = false
                    bullet.skip_fade_in(last)
                    _connect(self,last,0,true)
                    lasttask=task.New(last,function()
                        local self=task.GetSelf()
                        self.hscale = 100 self.vscale = 0.1
                        _object.set_color(self,"mul+add",255,r,g,b)
                        do
                            local _beg_dd=0 local dd=_beg_dd local _end_dd=self.d local _w_dd=0 local _d_w_dd=1/(60-1)
                            local _beg_alpha=250 local alpha=_beg_alpha local _end_alpha=0 local _w_alpha=0  local _d_w_alpha=1/(60-1)
                            for _=1,60 do
                                _set_rel_pos(self,dd * cos(self.rot+90),dd * sin(self.rot+90),self.rot,false)
                                _object.set_color(self,"mul+add",alpha,r,g,b)
                                task._Wait(1)
                                _w_dd=_w_dd+_d_w_dd dd=(_beg_dd-_end_dd)*(_w_dd-1)^2+_end_dd
                                _w_alpha=_w_alpha+_d_w_alpha alpha=(_end_alpha-_beg_alpha)*_w_alpha^2+_beg_alpha
                            end
                        end
                        _del(self,false)
                    end)
                end
                _w_d=_w_d+_d_w_d d=(_beg_d-_end_d)*(_w_d-1)^2+_end_d
            end
        end
        task._Wait(60)
        _del(self,false)
    end)
end
local pi = 180
local function easeInSine(x)
    return 1 - cos(x * pi / 2)
end
local function easeOutSine(x)
    return sin(x * pi / 2);
end
local function easeInOutSine(x)
    return (1 - cos(x * pi)) / 2;
end
_editor_class["LHX_144th_laser"]=Class(laser)
_editor_class["LHX_144th_laser"].init=function(self,_x,_y,obj1,obj2)
    laser.init(self,COLOR_BLUE,_x,_y,0,0,32,0,8,0,0)
    laser.ChangeImage(self,2)
    self.m1 = obj1 self.m2 = obj2 self.bound = false self.colli = false
    lasttask=task.New(self,function()
        laser._TurnHalfOn(self,30,true)
    end)
end
_editor_class["LHX_144th_laser"].frame=function(self)
    self.class.base.frame(self)
    if IsValid(self.m1) and IsValid(self.m2) then
    	local m1 = self.m1 local m2 = self.m2
    	self.l2 = Dist(m1,m2)
    	self.rot = Angle(m1,m2)
    	self.x = m1.x
    	self.y = m1.y
    else
    	_del(self,false)
    end
end
_editor_class["LHX_144th_nsc_obj1"]=Class(_object)
_editor_class["LHX_144th_nsc_obj1"].init=function(self,_x,_y,x0,y0,x1,y1,inia,omega,accrot)
    self.x,self.y=_x,_y
    self.img="parimg5"
    self.layer=LAYER_ENEMY_BULLET
    self.group=GROUP_INDES
    self.hide=false
    self.bound=false
    self.navi=false
    self.hp=10
    self.maxhp=10
    self.colli=false
    self._servants={}
    self._blend,self._a,self._r,self._g,self._b='',255,255,255,255
    self.rot = 45
    _object.set_color(self,"mul+add",255,255,122,0)
    lasttask=task.New(self,function()
        lasttask=task.New(self,function()
            for _=1,120 do
                last=New(_editor_class["LHX_144th_nsc_particle"],self.x,self.y,ran:Float(0,360),ran:Float(0.5,1))
                task._Wait(1)
            end
        end)
        task.BezierMoveTo(90,MODE_NORMAL,x0,y0,x1,y1)
        PlaySound("kira01",0.1,self.x/256,false)
        do
            local _beg_sc=1.2 local sc=_beg_sc local _end_sc=0 local _w_sc=0 local _d_w_sc=1/(15-1)
            for _=1,15 do
                self.hscale = sc self.vscale = sc
                task._Wait(1)
                _w_sc=_w_sc+_d_w_sc sc=(_beg_sc-_end_sc)*(_w_sc-1)^2+_end_sc
            end
        end
        PlaySound("tan00",0.1,self.x/256,false)
        local pre = nil local first = nil local cur = nil self.rad = 0
        do
            local a0=inia local _d_a0=(90)
            for _=1,4 do
                do
                    local _beg_a1=0 local a1=_beg_a1 local _end_a1=90 local _d_a1=(_end_a1-_beg_a1)/(12)
                    local i=0 local _d_i=(1)
                    local _h_g=(80-(0))/2 local _t_g=(80+(0))/2 local g=_h_g*sin(-90)+_t_g local _w_g=-90 local _d_w_g=1*360/(12)
                    for _=1,12 do
                        last=New(_editor_class["LHX_144th_nsc1_bullet1"],self.x,self.y,self, a0+a1, 1/cos(45-a1), omega, g)
                        if a0 == inia and a1 == 0 then self.s = last end
                        if a1 == 0 then
                            cur = last
                            if pre then
                                last=New(_editor_class["LHX_144th_laser"],self.x,self.y,pre,cur)
                            else
                                if a1 == 0 then first = last end
                            end
                            pre = cur
                        end
                        if i%2 == 0 then
                            do
                                local _beg_a2=-0.5 local a2=_beg_a2 local _end_a2=0.5 local _d_a2=(_end_a2-_beg_a2)/(3-1)
                                local _h_dv=(0.2-(0))/2 local _t_dv=(0.2+(0))/2 local dv=_h_dv*sin(-90)+_t_dv local _w_dv=-90 local _d_w_dv=1*360/(3-1)
                                for _=1,3 do
                                    last=New(_straight,square,COLOR_BLUE,self.x,self.y,dv,a0+a1+a2,false,0,true,true,0,false,0,0,0,false)
                                    do
                                        local self = last
                                        local rate = 1/cos(45-a1)
                                        do
                                            local __terminated = false
                                            local __terminateCount = 0
                                            local _0 = self._speed
                                            task.New(self, function()
                                                local self = task.GetSelf()
                                                task.Wait(0)
                                                local i = 0
                                                local offset = 0
                                                local curr, ibeg, ky, kx
                                                local prev = self._speed
                                                local target = offset
                                                curr = self._speed
                                                ibeg = i
                                                target = 0 + offset
                                                kx = target - ibeg
                                                ky = curr - prev
                                                while i < target do
                                                    _0 = prev + ky * (i - ibeg) / kx
                                                    i = i + 1
                                                    task.Wait()
                                                end
                                                _0 = curr
                                                prev = curr
                                                curr = rate
                                                ibeg = i
                                                target = 60 + offset
                                                kx = target - ibeg
                                                ky = curr - prev
                                                while i < target do
                                                    _0 = prev + ky * easeInSine((i - ibeg) / kx)
                                                    i = i + 1
                                                    task.Wait()
                                                end
                                                _0 = curr
                                                prev = curr
                                                offset = target
                                                __terminateCount = __terminateCount + 1
                                            end)
                                            task.New(self, function()
                                                local self = task.GetSelf()
                                                for _ = 1, _infinite do
                                                    SetV2(self, _0, self.rot, true, false)
                                                    if __terminated or __terminateCount >= 1 then break end
                                                    task.Wait()
                                                end
                                            end)
                                        end
                                    end
                                    a2=a2+_d_a2
                                    _w_dv=_w_dv+_d_w_dv dv=_h_dv*sin(_w_dv)+_t_dv
                                end
                            end
                        end
                        a1=a1+_d_a1
                        i=i+_d_i
                        _w_g=_w_g+_d_w_g g=_h_g*sin(_w_g)+_t_g
                    end
                end
                a0=a0+_d_a0
            end
        end
        last=New(_editor_class["LHX_144th_laser"],self.x,self.y,pre,first)
        self.img="img_void"        lasttask=task.New(self,function()
            task._Wait(60)
            _set_a(self,0.01,accrot,false)
            _forbid_v(self,1.4,'original','original')
            task._Wait(1200)
            self.bound = true
        end)
        lasttask=task.New(self,function()
            do
                local _beg_r=0 local r=_beg_r local _end_r=240 local _w_r=0 local _d_w_r=1/(240-1)
                for _=1,240 do
                    self.rad = r
                    task._Wait(1)
                    _w_r=_w_r+_d_w_r r=(_beg_r-_end_r)*(_w_r-1)^2+_end_r
                end
            end
        end)
        for _=1,_infinite do
            self.rot = self.s.angle + 45
            self.hscale = self.rad/8 self.vscale = self.hscale
            task._Wait(1)
        end
    end)
end
_editor_class["LHX_144th_nsc_obj1"].kill=function(self)
end
_editor_class["LHX_144th_nsc1_bullet1"]=Class(bullet)
_editor_class["LHX_144th_nsc1_bullet1"].init=function(self,_x,_y,master,rot,rate,omega,g)
bullet.init(self,ball_mid_c,COLOR_ORANGE,false,false)
self.x,self.y=_x,_y
    self.master = master self.angle = rot self.rate = rate
    self.bound = false
    local o = 0
    local sign = 1
    if omega < 0 then omega = - omega sign = -1 end
    _object.set_color(self,"add+alpha",255,255,g,0)
    lasttask=task.New(self,function()
        for _=1,_infinite do
            o = min(o+0.01,omega)
            self.angle = self.angle + o * sign
            task._Wait(1)
        end
    end)
end
_editor_class["LHX_144th_nsc1_bullet1"].frame=function(self)
    self.class.base.frame(self)
    if IsValid(self.master) then
    	local m = self.master
    	local rate = self.rate
    	local rot = self.angle
    	self.x = m.x + m.rad * rate * cos(rot)
    	self.y = m.y + m.rad * rate * sin(rot)
    else
    	_del(self,false)
    end
end
_editor_class["LHX_144th_nsc_particle"]=Class(_object)
_editor_class["LHX_144th_nsc_particle"].init=function(self,_x,_y,a,v)
    self.x,self.y=_x,_y
    self.img="parimg5"
    self.layer=LAYER_ENEMY_BULLET
    self.group=GROUP_ENEMY_BULLET
    self.hide=false
    self.bound=true
    self.navi=false
    self.hp=10
    self.maxhp=10
    self.colli=true
    self._servants={}
    self._blend,self._a,self._r,self._g,self._b='',255,255,255,255
    self.rot = 45
    _object.set_color(self,"mul+add",255,255,122,0)
    SetV2(self,v,a,false,false)
    lasttask=task.New(self,function()
        task._Wait(60)
        _del(self,true)
    end)
    lasttask=task.New(self,function()
        do
            local _h_alpha=(255-(100))/2 local _t_alpha=(255+(100))/2 local alpha=_h_alpha*sin(90)+_t_alpha local _w_alpha=90 local _d_w_alpha=5
            for _=1,_infinite do
                _object.set_color(self,"mul+add",alpha,255,122,0)
                task._Wait(1)
                _w_alpha=_w_alpha+_d_w_alpha alpha=_h_alpha*sin(_w_alpha)+_t_alpha
            end
        end
    end)
end
_editor_class["LHX_Boss"]=Class(boss)
_editor_class["LHX_Boss"].cards={}
_editor_class["LHX_Boss"].name="Zuifeng Tenkai"
_editor_class["LHX_Boss"].bgm="bgm:LHX_bgm"
_editor_class["LHX_Boss"]._bg=le03_7_background
_editor_class["LHX_Boss"].difficulty="All"
_editor_class["LHX_Boss"].init=function(self,cards)
boss.init(self,240,384,_editor_class["LHX_Boss"].name,cards,New(_editor_class["LHX_bg"]),_editor_class["LHX_Boss"].difficulty)
    self._wisys = BossWalkImageSystem(self)
    self._wisys:SetImage("LHX_boss.png",3,4,{4,4,4},{4,4},15,16,16)
end
_tmp_sc=boss.dialog.New(true)
function _tmp_sc:init()
    lstg.player.dialog=false
    _dialog_can_skip=true
    self.dialog_displayer=New(dialog_displayer)
    lasttask=task.New(self,function()
        boss.show_aura(self,false)
        self.hide = true self.colli = false
        lasttask=task.New(self,_editor_tasks["LHX_charge"](0,120,300,"_cast_in_"))
        task._Wait(150)
        lasttask=task.New(self,_editor_tasks["LHX_charge"](0,120,300,"_cast_out_"))
        boss.show_aura(self,true)
        self.hide = false self.colli = true self.x = 0 self.y = 120
    end)
end
table.insert(_editor_class["LHX_Boss"].cards,_tmp_sc)
--[[ 1
]]
_tmp_sc=boss.card.New("「乱改飞钵」",5,8,99,1800,{25,0,25},false)
function _tmp_sc:before()
    ui.lstg_weekly.SetFlag(true, false, false)
    ui.lstg_weekly.SetEditor("LHX")
end
function _tmp_sc:init()
    lasttask=task.New(self,function()
        lasttask=task.New(self,_editor_tasks["sc_open"](255,122,0))
        task.MoveTo(0,120,90,MOVE_ACC_DEC)
        lasttask=task.New(self,_editor_tasks["LHX_charge"](self.x,self.y,300,"_cast_in_"))
        task._Wait(90)
        lasttask=task.New(self,_editor_tasks["LHX_charge"](self.x,self.y,300,"_cast_out_"))
        local atable = {-120,30,-40,-20,40,-20,120,30} local inia = ran:Float(0,360)
        local sign = 1 local omega = 0.08
        for _=1,_infinite do
            for _=1,2 do
                local accrot = Angle(self,player)
                do local i,_d_i=(1),(2) for _=1,4 do
                    last=New(_editor_class["LHX_144th_nsc_obj1"],self.x,self.y,self.x, self.y-120, self.x+atable[i], self.y+atable[i+1]*sign, inia, omega, accrot)
                    inia = inia+45*(i+1)/2 omega = - omega
                i=i+_d_i end end
                sign = - sign
                task._Wait(150)
            end
            task._Wait(90)
            task.MoveToPlayer(60,-96,96,112,144,16,32,8,16,MOVE_ACC_DEC,MOVE_X_TOWARDS_PLAYER)
            lasttask=task.New(self,_editor_tasks["LHX_charge"](self.x,self.y,300,"_cast_in_"))
            task._Wait(90)
            lasttask=task.New(self,_editor_tasks["LHX_charge"](self.x,self.y,300,"_cast_out_"))
        end
    end)
end
function _tmp_sc:beforedel()
end
function _tmp_sc:del()
end
function _tmp_sc:after()
end
_tmp_sc.perform=false
table.insert(_editor_class["LHX_Boss"].cards,_tmp_sc)
table.insert(_sc_table,{"LHX_Boss","「乱改飞钵」",_tmp_sc,#_editor_class["LHX_Boss"].cards,false})
stage.group.AddStage(__WEEK_ID,'LHX@'..__WEEK_ID,{lifeleft=7,power=400,faith=50000,bomb=3},true)
stage.group.DefStageFunc('LHX@'..__WEEK_ID,'init',function(self)
    _init_item(self)
    difficulty=self.group.difficulty
    New(mask_fader,'open')
    if jstg then jstg.CreatePlayers() else New(_G[lstg.var.player_name]) end
    lasttask=task.New(self,function()
        New(le03_7_background)
        local hspeed = player.hspeed
        local lspeed = player.lspeed
        task._Wait(60)
        last=New(_editor_class["LHX_musicback"],0,-192)
        LoadMusicRecord("bgm:LHX_bgm")
        _play_music("bgm:LHX_bgm")
        task._Wait(180)
        local _boss_wait=true
        local _ref=New(_editor_class["LHX_Boss"],_editor_class["LHX_Boss"].cards)
        last=_ref
        if _boss_wait then while IsValid(_ref) do task.Wait() end end
        player.hspeed = hspeed
        player.lspeed = lspeed
        task._Wait(240)
    end)
    ui.lstg_weekly.stage_init(self)
    task.New(self,function()
        while coroutine.status(self.task[1])~='dead' do task.Wait() end
        stage.group.FinishReplay()
        New(mask_fader,'close')
        task.New(self,function()
            local _,bgm=EnumRes('bgm')
            for i=1,30 do
                for _,v in pairs(bgm) do
                    if GetMusicState(v)=='playing' then
                        SetBGMVolume(v,1-i/30)
                    end
                end
                task.Wait()
            end
        end)
        task.Wait(30)
        stage.group.FinishStage()
    end)
end)
