-- Generated by LuaSTG Editor Sharp
-- Mod name: 
_author = "LuaSTG User"
_mod_version = 4096
_allow_practice = true
_allow_sc_practice =true
_LoadImageFromFile('image:'..'Ronnie_Yukari_BGa','Ronnie_Yukari_BGa.png',true,0,0,false,0)
_LoadImageFromFile('image:'..'Ronnie_Yukari_BGb','Ronnie_Yukari_BGb.png',true,0,0,false,0)
_LoadImageFromFile('image:'..'Ronnie_Yukari_image','Ronnie_Yukari_image.png',true,0,0,false,0)
_LoadImageFromFile('image:'..'Ronnie_Animation_Yukari','Ronnie_Animation_Yukari.png',true,0,0,false,0)
_LoadImageFromFile('image:'..'Ronnie_Animation_Hongbao','Ronnie_Animation_Hongbao.png',true,0,0,false,0)
MusicRecord('bgm:'..'Ronnie_BGM','Ronnie_BGM.ogg',445,445)
_editor_class["Ronnie_Animations_Yukari"]=Class(_object)
_editor_class["Ronnie_Animations_Yukari"].init=function(self,_x,_y)
    self.x,self.y=_x,_y
    self.img="image:Ronnie_Animation_Yukari"
    self.layer=LAYER_ENEMY-9
    self.group=GROUP_GHOST
    self.hide=false
    self.bound=false
    self.navi=false
    self.hp=10
    self.maxhp=10
    self.colli=true
    self._servants={}
    self._blend,self._a,self._r,self._g,self._b='',255,255,255,255
    self.hscale=0.5
    self.vscale=0.5
    self.aa = 0
    self.x, self.y = 280,70
    _object.set_color(self,"",0,255,255,255)
    last=New(_editor_class["Ronnie_Animations_Hongbao"],self.x-10,self.y+42,self)
    _connect(self,last,0,true)
    lasttask=task.New(self,function()
        do local a,_d_a=(0),(90 / 20) for _=1,21 do
            self.aa = sin(a)
            _object.set_color(self,"",255*sin(a),255,255,255)
            task._Wait(1)
        a=a+_d_a end end
    end)
    lasttask=task.New(self,function()
        do local a,_d_a,v,_d_v=(220),(-20 / 60),(12),(-11 / 40) for _=1,41 do
            SetV2(self,v,a,false,false)
            task._Wait(1)
        a=a+_d_a v=v+_d_v end end
        do local a,_d_a=(200),(-20 / 45) for _=1,46 do
            SetV2(self,1,a,false,false)
            task._Wait(1)
        a=a+_d_a end end
        lasttask=task.New(self,function()
            task._Wait(20)
            do local a,_d_a=(1),(-1 / 40) for _=1,41 do
                self.aa = a
                _object.set_color(self,"",255 * a,255 * a,255 * a,255 * a)
                task._Wait(1)
            a=a+_d_a end end
            task._Wait(10)
            _del(self,false)
        end)
        do local v,_d_v=(1),(6 / 40) for _=1,41 do
            SetV2(self,v,180,false,false)
            task._Wait(1)
        v=v+_d_v end end
    end)
end
_editor_class["Ronnie_Animations_Hongbao"]=Class(_object)
_editor_class["Ronnie_Animations_Hongbao"].init=function(self,_x,_y,leader)
    self.x,self.y=_x,_y
    self.img="image:Ronnie_Animation_Hongbao"
    self.layer=LAYER_ENEMY-7
    self.group=GROUP_GHOST
    self.hide=false
    self.bound=false
    self.navi=false
    self.hp=10
    self.maxhp=10
    self.colli=true
    self._servants={}
    self._blend,self._a,self._r,self._g,self._b='',255,255,255,255
    self.hscale=0.2
    self.vscale=0.2
    self.leader=leader
    self.x=self.leader.x+50*cos(115)
    self.y=self.leader.y+50*sin(115)
    _object.set_color(self,"",0,255,255,255)
    self.aa = 0
    lasttask=task.New(self,function()
        task._Wait(24)
        lasttask=task.New(self,function()
            do local a,_d_a=(0),(90 / 20) for _=1,21 do
                self.aa = sin(a)
                _object.set_color(self,"",255*sin(a),255,255,255)
                task._Wait(1)
            a=a+_d_a end end
        end)
        do
            local _beg_scale=0.2 local scale=_beg_scale local _end_scale=0.45 local _w_scale=0 local _d_w_scale=1/(43)
            local _beg_trans=0 local trans=_beg_trans local _end_trans=255 local _w_trans=0 local _d_w_trans=1/(43)
            local _beg_l=60 local l=_beg_l local _end_l=10 local _w_l=0 local _d_w_l=1/(43)
            for _=1,43 do
                task._Wait(1)
                self.hscale=scale
                self.vscale=scale
                self.x=self.leader.x-10+l*cos(115)
                self.y=self.leader.y+42+l*sin(115)
                _w_scale=_w_scale+_d_w_scale scale=(_beg_scale-_end_scale)*(_w_scale-1)^2+_end_scale
                _w_trans=_w_trans+_d_w_trans trans=(_beg_trans-_end_trans)*(_w_trans-1)^2+_end_trans
                _w_l=_w_l+_d_w_l l=(_beg_l-_end_l)*(_w_l-1)^2+_end_l
            end
        end
        task._Wait(20)
        lasttask=task.New(self,function()
            task._Wait(20)
            do local a,_d_a=(1),(-1 / 40) for _=1,41 do
                self.aa = a
                _object.set_color(self,"",255 * a,255 * a,255 * a,255 * a)
                task._Wait(1)
            a=a+_d_a end end
            task._Wait(10)
            _del(self,true)
        end)
    end)
end
_editor_class["Ronnie_Animations_Hongbao"].frame=function(self)
    self.class.base.frame(self)
    if IsValid(self.leader) and self.timer>=68 then
        self.x=self.leader.x-10+10*cos(115)
        self.y=self.leader.y+42+10*sin(115)
    end
end
_editor_class["Ronnie_Effect_MagicLight"]=Class(_object)
_editor_class["Ronnie_Effect_MagicLight"].init=function(self,_x,_y,R,G,B)
    self.x,self.y=_x,_y
    self.img="img_void"
    self.layer=LAYER_ENEMY+5
    self.group=GROUP_GHOST
    self.hide=false
    self.bound=false
    self.navi=false
    self.hp=10
    self.maxhp=10
    self.colli=true
    self._servants={}
    self._blend,self._a,self._r,self._g,self._b='',255,255,255,255
    lasttask=task.New(self,function()
        do local a,_d_a=(0),(2.1) for _=1,63 do
            do local an0,_d_an0=(a),(60) for _=1,3 do
                last=New(_straight,ball_light,COLOR_PURPLE,self.x,self.y,0,0,false,0,true,true,0,false,0,0,0,false)
                do
                    local self = last
                    do
                        local an=(an0)
                        self.vscale=4.5
                        self.hscale=0.12
                        self.rot=an
                        self.layer=LAYER_ENEMY+5
                        self.colli=false
                        self.timer=11
                        _object.set_color(self,"mul+add",0,R,G,B)
                        lasttask=task.New(self,function()
                            do local tran,_d_tran,x,_d_x=(0),(125/30),(3),(3) for _=1,30 do
                                _object.set_color(self,"mul+add",tran+tran*sin(x),R,G,B)
                                task._Wait(1)
                            tran=tran+_d_tran x=x+_d_x end end
                            do local tran,_d_tran,x,_d_x=(125),(-125/30),(90),(-3) for _=1,30 do
                                _object.set_color(self,"mul+add",tran+tran^sin(x),R,G,B)
                                task._Wait(1)
                            tran=tran+_d_tran x=x+_d_x end end
                            _del(self,false)
                        end)
                    end
                end
            an0=an0+_d_an0 end end
            task._Wait(2)
        a=a+_d_a end end
        task._Wait(300)
        _del(self,true)
    end)
end
_editor_class["Ronnie_Effect_EnergyStorage"]=Class(_object)
_editor_class["Ronnie_Effect_EnergyStorage"].init=function(self,_x,_y,R,G,B)
    self.x,self.y=_x,_y
    self.img="img_void"
    self.layer=LAYER_ENEMY-5
    self.group=GROUP_GHOST
    self.hide=false
    self.bound=true
    self.navi=false
    self.hp=10
    self.maxhp=10
    self.colli=true
    self._servants={}
    self._blend,self._a,self._r,self._g,self._b='',255,255,255,255
    lasttask=task.New(self,function()
        for _=1,3 do
            last=New(_straight,ball_big,COLOR_GRAY,self.x,self.y,0,0,false,0,true,true,0,false,0,0,0,false)
            do
                local self = last
                _object.set_color(self,"mul+add",0,R,G,B)
                self.hscale,self.vscale=0,0
                PlaySound("power02",0.1,self.x/256,false)
                lasttask=task.New(self,function()
                    do
                        local _beg_scale=14 local scale=_beg_scale local _end_scale=0 local _w_scale=0 local _d_w_scale=1/(70)
                        local _beg_tran=0 local tran=_beg_tran local _end_tran=255 local _d_tran=(_end_tran-_beg_tran)/(70)
                        for _=1,70 do
                            self.hscale,self.vscale=scale,scale
                            _object.set_color(self,"mul+add",tran,R,G,B)
                            task._Wait(1)
                            _w_scale=_w_scale+_d_w_scale scale=(_beg_scale-_end_scale)*(_w_scale-1)^2+_end_scale
                            tran=tran+_d_tran
                        end
                    end
                    task._Wait(10)
                    _del(self,true)
                end)
            end
            _connect(self,last,0,true)
            task._Wait(22)
        end
        task._Wait(79)
        PlaySound("enep02",0.1,self.x/256,false)
        last=New(_straight,ball_big,COLOR_GRAY,self.x,self.y,0,0,false,0,true,true,0,false,0,0,0,false)
        do
            local self = last
            _object.set_color(self,"mul+add",0,235,87,51)
            self.hscale,self.vscale=0,0
            lasttask=task.New(self,function()
                do
                    local _beg_scale=0 local scale=_beg_scale local _end_scale=16 local _w_scale=0 local _d_w_scale=1/(40)
                    local _beg_tran=255 local tran=_beg_tran local _end_tran=0 local _d_tran=(_end_tran-_beg_tran)/(40)
                    for _=1,40 do
                        self.hscale,self.vscale=scale,scale
                        _object.set_color(self,"mul+add",tran,R,G,B)
                        task._Wait(1)
                        _w_scale=_w_scale+_d_w_scale scale=(_beg_scale-_end_scale)*(_w_scale-1)^2+_end_scale
                        tran=tran+_d_tran
                    end
                end
                task._Wait(10)
                _del(self,false)
            end)
        end
        _connect(self,last,0,true)
        task._Wait(200)
        _del(self,false)
    end)
end
_editor_class["Ronnie_Effect_BorderOpen"]=Class(_object)
_editor_class["Ronnie_Effect_BorderOpen"].init=function(self,_x,_y)
    self.x,self.y=_x,_y
    self.img="white"
    self.layer=LAYER_BG+5
    self.group=GROUP_GHOST
    self.hide=false
    self.bound=true
    self.navi=false
    self.hp=10
    self.maxhp=10
    self.colli=false
    self._servants={}
    self._blend,self._a,self._r,self._g,self._b='',255,255,255,255
    self.rot=37.6
    self.hscale=0.1
    self.vscale=0.1
    _object.set_color(self,"",0,0,0,0)
    lasttask=task.New(self,function()
        do
            local _beg_tran=0 local tran=_beg_tran local _end_tran=255 local _w_tran=0  local _d_w_tran=1/(30)
            local _beg_scale=0.1 local scale=_beg_scale local _end_scale=60 local _w_scale=0  local _d_w_scale=1/(30)
            for _=1,30 do
                _object.set_color(self,"",tran,0,0,0)
                self.hscale=scale
                task._Wait(1)
                _w_tran=_w_tran+_d_w_tran tran=(_end_tran-_beg_tran)*_w_tran^2+_beg_tran
                _w_scale=_w_scale+_d_w_scale scale=(_end_scale-_beg_scale)*_w_scale^2+_beg_scale
            end
        end
        task._Wait(15)
        do
            local _beg_scale=0.1 local scale=_beg_scale local _end_scale=60 local _w_scale=0  local _d_w_scale=1/(80)
            for _=1,80 do
                self.vscale=scale
                task._Wait(1)
                _w_scale=_w_scale+_d_w_scale scale=(_end_scale-_beg_scale)*_w_scale^2+_beg_scale
            end
        end
        task._Wait(15)
        do
            local _beg_tran=255 local tran=_beg_tran local _end_tran=0 local _d_tran=(_end_tran-_beg_tran)/(60)
            for _=1,60 do
                _object.set_color(self,"",tran,0,0,0)
                task._Wait(1)
                tran=tran+_d_tran
            end
        end
        task._Wait(60)
        _del(self,false)
    end)
end
_editor_class["Ronnie_Yukari_BG"]=Class(_spellcard_background)
_editor_class["Ronnie_Yukari_BG"].init=function(self)
    _spellcard_background.init(self)
    _spellcard_background.AddLayer(self,"image:Ronnie_Yukari_BGb",false,0,0,0,0,0,0.4,"mul+add",2,2,
        function(self)
            self.task={}
            self.layer=LAYER_BG+3
        end,
        function(self)
            task.Do(self)
        end,
        function(self)
        end
    )
    _spellcard_background.AddLayer(self,"image:Ronnie_Yukari_BGa",false,0,0,0,0,0,0,"",1.7,1.7,
        function(self)
            self.task={}
            self.layer=LAYER_BG
        end,
        function(self)
            task.Do(self)
        end,
        function(self)
        end
    )
end
_editor_class["Ronnie_Laser_1"]=Class(laser)
_editor_class["Ronnie_Laser_1"].init=function(self,_x,_y,leader,LB,LS,R,G,B)
    laser.init(self,COLOR_PURPLE,_x,_y,0,0,LB*1.414,0,6,0,0)
    laser.ChangeImage(self,2)
    self.rot=leader.rot-135
    self.bound=false
    lasttask=task.New(self,function()
        do
            local _beg_tran=0 local tran=_beg_tran local _end_tran=255 local _w_tran=0 local _d_w_tran=1/(30)
            for _=1,30 do
                _object.set_color(self,"mul+add",tran,R,G,B)
                task._Wait(1)
                _w_tran=_w_tran+_d_w_tran if _w_tran<0.5 then tran=2*(_end_tran-_beg_tran)*_w_tran^2+_beg_tran else tran=(_end_tran-_beg_tran)*(-2*_w_tran^2+4*_w_tran-1)+_beg_tran end
            end
        end
        do return end
    end)
    lasttask=task.New(self,function()
        for _=1,_infinite do
            self.rot=leader.rot-135
            self.x=leader.x
            self.y=leader.y
            self.l2=leader.l*1.414
            task._Wait(1)
        end
    end)
    lasttask=task.New(self,function()
        laser._TurnHalfOn(self,30,true)
        laser._TurnOn(self,30,false,true)
    end)
end
_editor_class["Ronnie_Laser_2"]=Class(laser)
_editor_class["Ronnie_Laser_2"].init=function(self,_x,_y,tran,an,leader,l0,l1,dir,R,G,B,color)
    laser.init(self,color,_x,_y,0,10,400,64,8,0,0)
    laser.ChangeImage(self,4)
    _object.set_color(self,"mul+add",tran,R,G,B)
    self.rot=an
    self.layer=LAYER_ENEMY-7
    self.colli=false
    self.bound=false
    lasttask=task.New(self,function()
        do
            local _beg_l=l0 local l=_beg_l local _end_l=l1 local _w_l=0 local _d_w_l=1/(50)
            for _=1,50 do
                self.x=leader.x+l*cos(an+90)*dir
                self.y=leader.y+l*sin(an+90)*dir
                task._Wait(1)
                _w_l=_w_l+_d_w_l l=(_beg_l-_end_l)*(_w_l-1)^2+_end_l
            end
        end
    end)
    lasttask=task.New(self,function()
        laser._TurnOn(self,20,false,true)
        task._Wait(155)
        do
            local _beg_tran0=tran local tran0=_beg_tran0 local _end_tran0=0 local _d_tran0=(_end_tran0-_beg_tran0)/(30)
            for _=1,30 do
                _object.set_color(self,"mul+add",tran0,R,G,B)
                task._Wait(1)
                tran0=tran0+_d_tran0
            end
        end
        _del(self,true)
    end)
end
_editor_class["Ronnie_Laser_3"]=Class(laser)
_editor_class["Ronnie_Laser_3"].init=function(self,_x,_y,an,R,G,B,color)
    laser.init(self,color,_x,_y,0,20,400,64,35,0,0)
    laser.ChangeImage(self,4)
    self.rot=an
    self.layer=LAYER_ENEMY-7
    _object.set_color(self,"mul+add",255,R,G,B)
    lasttask=task.New(self,function()
        laser._TurnOn(self,15,true,true)
        misc.ShakeScreen(30,3)
        task._Wait(60)
        do
            local _beg_tran0=255 local tran0=_beg_tran0 local _end_tran0=0 local _d_tran0=(_end_tran0-_beg_tran0)/(30)
            for _=1,30 do
                _object.set_color(self,"mul+add",tran0,R,G,B)
                task._Wait(1)
                tran0=tran0+_d_tran0
            end
        end
        _del(self,true)
    end)
end
_editor_class["Ronnie_BentLaser_1"]=Class(laser_bent)
_editor_class["Ronnie_BentLaser_1"].init=function(self,_x,_y,dir,R,G,B)
    laser_bent.init(self,COLOR_GRAY,_x,_y,150,6,4,0)
    self.bound=false
    self.colli=false
    lasttask=task.New(self,function()
        SetV2(self,6.17,-90+45*dir,true,false)
        for _=1,_infinite do
            if dir==1 then
                if self.x>=-250 and self.x<=250 then
                    last=New(_editor_class["Ronnie_Obj_1"],self.x,self.y+48,R,G,B)
                    _connect(_boss,last,0,true)
                end
            end
            task._Wait(11)
        end
        task._Wait(300)
        _del(self,true)
    end)
end
_editor_class["Ronnie_Obj_1"]=Class(_object)
_editor_class["Ronnie_Obj_1"].init=function(self,_x,_y,R,G,B)
    self.x,self.y=_x,_y
    self.img="white"
    self.layer=LAYER_ENEMY_BULLET
    self.group=GROUP_GHOST
    self.hide=false
    self.bound=false
    self.navi=false
    self.hp=10
    self.maxhp=10
    self.colli=true
    self._servants={}
    self._blend,self._a,self._r,self._g,self._b='',255,255,255,255
    _object.set_color(self,"",0,R,G,B)
    self.rot=45
    self.hscale,self.vscale=3.85,3.85
    local LB=(45)
    local LS=(27)
    local Leader=(self)
    lasttask=task.New(self,function()
        do local an0,_d_an0=(90),(90) for _=1,4 do
            last=New(_straight,ball_mid_c,COLOR_GRAY,self.x+LB*cos(an0),self.y+LB*sin(an0),0,0,false,0,true,true,0,false,0,0,0,false)
            do
                local self = last
                do
                    local an=(an0)
                    self.hscale,self.vscale=0.6,0.6
                    self.rot=an
                    self.colli=false
                    self.bound=false
                    self.group=GROUP_INDES
                    self.layer=LAYER_ENEMY_BULLET+10
                    self.timer=10
                    _object.set_color(self,"mul+add",0,R,G,B)
                    lasttask=task.New(self,function()
                        last=New(_editor_class["Ronnie_Laser_1"],self.x,self.y,self,LB,LS,R,G,B)
                        _connect(_boss,last,0,true)
                        _connect(Leader,last,0,true)
                        do
                            local _beg_tran=0 local tran=_beg_tran local _end_tran=255 local _w_tran=0 local _d_w_tran=1/(30)
                            for _=1,30 do
                                _object.set_color(self,"mul+add",tran,R,G,B)
                                task._Wait(1)
                                _w_tran=_w_tran+_d_w_tran if _w_tran<0.5 then tran=2*(_end_tran-_beg_tran)*_w_tran^2+_beg_tran else tran=(_end_tran-_beg_tran)*(-2*_w_tran^2+4*_w_tran-1)+_beg_tran end
                            end
                        end
                    end)
                    lasttask=task.New(self,function()
                        for _=1,52 do
                            self.l=(LB/3.85)*Leader.hscale
                            self.x=Leader.x+self.l*cos(an)
                            self.y=Leader.y+self.l*sin(an)
                            task._Wait(1)
                        end
                        for _=1,_infinite do
                            self.l=(LB/3.85)*Leader.hscale
                            self.x=Leader.x+self.l*cos(Leader.rot+an-45)
                            self.y=Leader.y+self.l*sin(Leader.rot+an-45)
                            self.rot=Leader.rot+an-45
                            task._Wait(1)
                        end
                    end)
                end
            end
            _connect(_boss,last,0,true)
            _connect(Leader,last,0,true)
        an0=an0+_d_an0 end end
        lasttask=task.New(self,function()
            task._Wait(2)
            do
                local _beg_scale=3.85 local scale=_beg_scale local _end_scale=(LS*3.85)/LB local _w_scale=0 local _d_w_scale=1/(50)
                for _=1,50 do
                    self.hscale,self.vscale=scale,scale
                    task._Wait(1)
                    _w_scale=_w_scale+_d_w_scale scale=(_beg_scale-_end_scale)*(_w_scale-1)^2+_end_scale
                end
            end
        end)
        do
            local _beg_tran=0 local tran=_beg_tran local _end_tran=170 local _w_tran=0 local _d_w_tran=1/(30)
            for _=1,30 do
                _object.set_color(self,"",tran,R,G,B)
                task._Wait(1)
                _w_tran=_w_tran+_d_w_tran if _w_tran<0.5 then tran=2*(_end_tran-_beg_tran)*_w_tran^2+_beg_tran else tran=(_end_tran-_beg_tran)*(-2*_w_tran^2+4*_w_tran-1)+_beg_tran end
            end
        end
        task._Wait(70)
        _set_a(self,0.007+0.007*cos(self.x*0.6),-90+20*sin(self.x*0.6),false)
        local o=(2*sin(self.x))
        if self.x<=5 and self.x>=-5 then
            o=2*sin(self.y)
            _set_a(self,0.007+0.007*cos(self.x*1.4),-90+20*sin(self.y*0.6),false)
        end
        do
            local _beg_O=0 local O=_beg_O local _end_O=o local _d_O=(_end_O-_beg_O)/(30)
            for _=1,30 do
                self.omiga=o
                task._Wait(1)
                O=O+_d_O
            end
        end
        for _=1,_infinite do
            self.hscale=self.hscale-0.003
            self.vscale=self.vscale-0.003
            if self.y<=-260 then
                _del_servants(self)
                task._Wait(1)
                _del(self,true)
            end
            task._Wait(1)
        end
    end)
end
_editor_class["Ronnie_Obj_1"].del=function(self)
    self.class.base.del(self)
    _del_servants(self)
end
_editor_class["Ronnie_Obj_1"].kill=function(self)
    self.class.base.kill(self)
    _del_servants(self)
end
_editor_class["Yukari"]=Class(boss)
_editor_class["Yukari"].cards={}
_editor_class["Yukari"].name="被作者拉过来当临时工的油咖喱"
_editor_class["Yukari"].bgm="bgm:Ronnie_BGM"
_editor_class["Yukari"]._bg=nil
_editor_class["Yukari"].difficulty="All"
_editor_class["Yukari"].init=function(self,cards)
boss.init(self,240,384,_editor_class["Yukari"].name,cards,New(_editor_class["Ronnie_Yukari_BG"]),_editor_class["Yukari"].difficulty)
    self._wisys = BossWalkImageSystem(self)
    self._wisys:SetImage("Ronnie_Yukari_image.png",4,10,{7,10,10,7},{3,3,3},4,16,16)
end
--[[ 名字可能多少带点抽象，不过我也不擅长起名字
]]
--[[ 2
]]
_tmp_sc=boss.card.New("",2,5,60,800,{0,0,0},false)
function _tmp_sc:before()
    ui.lstg_weekly.SetFlag(false, true, false)
    ui.lstg_weekly.SetEditor("Ronnie")
end
function _tmp_sc:init()
    lasttask=task.New(self,function()
        task.MoveTo(0,120,60,MOVE_NORMAL)
        lasttask=task.New(self,function()
            for _=1,_infinite do
                do local an,_d_an=(Angle(self,player)),(40) for _=1,9 do
                    last=New(_straight,ball_huge,COLOR_BLUE,self.x,self.y,3.2,an,false,0,true,true,0,false,0,0,0,false)
                    do
                        local self = last
                        lasttask=task.New(self,function()
                            self.num=0
                            for _=1,_infinite do
                                if self.x>=185 or self.x<=-185 then
                                    self.vx=self.vx*-1
                                    self.num=self.num+1
                                else
                                    if self.y>=210 or self.y<=-210 then
                                        self.vy=self.vy*-1
                                        self.num=self.num+1
                                    end
                                end
                                if self.num==3 then
                                    do break end
                                end
                                task._Wait(1)
                            end
                        end)
                    end
                    task._Wait(8)
                an=an+_d_an end end
                task._Wait(480)
            end
        end)
        do local an,_d_an=(4),(97) for _=1,_infinite do
            _create_bullet_group(grain_a,COLOR_PURPLE,self.x+20*cos(an),self.y+20*sin(an),50,0,1,1,0,360,true,0,true,true,0,false,self)
            task._Wait(65)
        an=an+_d_an end end
    end)
end
function _tmp_sc:beforedel()
end
function _tmp_sc:del()
end
function _tmp_sc:after()
end
_tmp_sc.perform=false
table.insert(_editor_class["Yukari"].cards,_tmp_sc)

_tmp_sc=boss.card.New("走向抽象的理解「切割与熔毁的境界」",3,7,60,1600,{0,0,0},false)
function _tmp_sc:before()
    task.MoveTo(0,120,60,MOVE_NORMAL)
    last=New(_editor_class["Ronnie_Effect_EnergyStorage"],self.x,self.y,237,174,255)
    last=New(_editor_class["Ronnie_Effect_MagicLight"],self.x,self.y,237,174,255)
    last=New(_editor_class["Ronnie_Effect_BorderOpen"],0,0)
    task._Wait(140)
end
function _tmp_sc:init()
    lasttask=task.New(self,function()
        task._Wait(40)
        last=New(_editor_class["Ronnie_Animations_Yukari"],self.x,self.y)
        task._Wait(130)
        for _=1,_infinite do
            task._Wait(20)
            do local Xinit,_d_Xinit=(-192),(96) for _=1,10 do
                last=New(_editor_class["Ronnie_BentLaser_1"],Xinit+48,224+48,-1,245,112,119)
                _connect(self,last,0,true)
            Xinit=Xinit+_d_Xinit end end
            do local Xinit,_d_Xinit=(192),(-96) for _=1,10 do
                last=New(_editor_class["Ronnie_BentLaser_1"],Xinit-48,224+48,1,245,112,119)
                _connect(self,last,0,true)
            Xinit=Xinit+_d_Xinit end end
            task._Wait(160)
            do local initX,_d_initX=(-140),(70) for _=1,5 do
                last=New(_straight,ball_light,COLOR_ORANGE,initX,self.y,0,0,false,0,true,true,0,false,0,0,0,false)
                do
                    local self = last
                    do
                        self.vscale=2.5
                        self.hscale=2.5
                        self.hide=true
                        lasttask=task.New(self,function()
                            local an=(-90)
                            local R=(219)
                            local G=(137)
                            local B=(251)
                            local color=(2)
                            do
                                local _beg_tran=10 local tran=_beg_tran local _end_tran=240 local _w_tran=0 local _d_w_tran=1/(12)
                                local _beg_l=0 local l=_beg_l local _end_l=80 local _d_l=(_end_l-_beg_l)/(12)
                                local _beg_ll=0 local ll=_beg_ll local _end_ll=20 local _d_ll=(_end_ll-_beg_ll)/(12)
                                for _=1,12 do
                                    last=New(_editor_class["Ronnie_Laser_2"],self.x+l*sin(an),self.y+l*cos(an),tran,an,self,l,ll,1,R,G,B,color)
                                    _connect(self,last,0,true)
                                    last=New(_editor_class["Ronnie_Laser_2"],self.x-l*sin(an),self.y-l*cos(an),tran,an,self,l,ll,-1,R,G,B,color)
                                    _connect(self,last,0,true)
                                    last=New(_editor_class["Ronnie_Laser_2"],self.x+l*sin(an),self.y+l*cos(an),tran,an+180,self,l,ll,1,R,G,B,color)
                                    _connect(self,last,0,true)
                                    last=New(_editor_class["Ronnie_Laser_2"],self.x-l*sin(an),self.y-l*cos(an),tran,an+180,self,l,ll,-1,R,G,B,color)
                                    _connect(self,last,0,true)
                                    task._Wait(2)
                                    _w_tran=_w_tran+_d_w_tran if _w_tran<0.5 then tran=2*(_end_tran-_beg_tran)*_w_tran^2+_beg_tran else tran=(_end_tran-_beg_tran)*(-2*_w_tran^2+4*_w_tran-1)+_beg_tran end
                                    l=l+_d_l
                                    ll=ll+_d_ll
                                end
                            end
                            task._Wait(108)
                            last=New(_editor_class["Ronnie_Laser_3"],self.x,self.y,an,R,G,B,color)
                            _connect(self,last,0,true)
                            last=New(_editor_class["Ronnie_Laser_3"],self.x,self.y,an+180,R,G,B,color)
                            _connect(self,last,0,true)
                            task._Wait(100)
                            _del(self,false)
                        end)
                    end
                end
                task._Wait(25)
            initX=initX+_d_initX end end
            task._Wait(15)
            do local initY,_d_initY=(-185),(74) for _=1,6 do
                last=New(_straight,ball_light,COLOR_ORANGE,self.y,initY,0,0,false,0,true,true,0,false,0,0,0,false)
                do
                    local self = last
                    do
                        self.vscale=2.5
                        self.hscale=2.5
                        self.hide=true
                        lasttask=task.New(self,function()
                            local an=(0)
                            local R=(219)
                            local G=(137)
                            local B=(251)
                            local color=(2)
                            do
                                local _beg_tran=10 local tran=_beg_tran local _end_tran=240 local _w_tran=0 local _d_w_tran=1/(12)
                                local _beg_l=0 local l=_beg_l local _end_l=80 local _d_l=(_end_l-_beg_l)/(12)
                                local _beg_ll=0 local ll=_beg_ll local _end_ll=20 local _d_ll=(_end_ll-_beg_ll)/(12)
                                for _=1,12 do
                                    last=New(_editor_class["Ronnie_Laser_2"],self.x+l*sin(an),self.y+l*cos(an),tran,an,self,l,ll,1,R,G,B,color)
                                    _connect(self,last,0,true)
                                    last=New(_editor_class["Ronnie_Laser_2"],self.x-l*sin(an),self.y-l*cos(an),tran,an,self,l,ll,-1,R,G,B,color)
                                    _connect(self,last,0,true)
                                    last=New(_editor_class["Ronnie_Laser_2"],self.x+l*sin(an),self.y+l*cos(an),tran,an+180,self,l,ll,1,R,G,B,color)
                                    _connect(self,last,0,true)
                                    last=New(_editor_class["Ronnie_Laser_2"],self.x-l*sin(an),self.y-l*cos(an),tran,an+180,self,l,ll,-1,R,G,B,color)
                                    _connect(self,last,0,true)
                                    task._Wait(2)
                                    _w_tran=_w_tran+_d_w_tran if _w_tran<0.5 then tran=2*(_end_tran-_beg_tran)*_w_tran^2+_beg_tran else tran=(_end_tran-_beg_tran)*(-2*_w_tran^2+4*_w_tran-1)+_beg_tran end
                                    l=l+_d_l
                                    ll=ll+_d_ll
                                end
                            end
                            task._Wait(108)
                            last=New(_editor_class["Ronnie_Laser_3"],self.x,self.y,an,R,G,B,color)
                            _connect(self,last,0,true)
                            last=New(_editor_class["Ronnie_Laser_3"],self.x,self.y,an+180,R,G,B,color)
                            _connect(self,last,0,true)
                            task._Wait(100)
                            _del(self,false)
                        end)
                    end
                end
                task._Wait(10)
            initY=initY+_d_initY end end
            task._Wait(130)
        end
    end)
end
function _tmp_sc:beforedel()
    _del_servants(self)
end
function _tmp_sc:del()
end
function _tmp_sc:after()
end
_tmp_sc.perform=false
table.insert(_editor_class["Yukari"].cards,_tmp_sc)
table.insert(_sc_table,{"Yukari","走向抽象的理解「切割与熔毁的境界」",_tmp_sc,#_editor_class["Yukari"].cards,false})
stage.group.AddStage(__WEEK_ID,'Ronnie@'..__WEEK_ID,{lifeleft=7,power=400,faith=50000,bomb=3},true)
stage.group.DefStageFunc('Ronnie@'..__WEEK_ID,'init',function(self)
    _init_item(self)
    difficulty=self.group.difficulty
    New(mask_fader,'open')
    if jstg then jstg.CreatePlayers() else New(_G[lstg.var.player_name]) end
    lasttask=task.New(self,function()
        LoadMusic('spellcard','THlib\\music\\spellcard.ogg',75,0xc36e80/44100/4)
        New(temple_background)
        task._Wait(60)
        LoadMusicRecord("bgm:Ronnie_BGM")
        _play_music("bgm:Ronnie_BGM")
        --[[ Insert after this]]
        
        task._Wait(100)
        local _boss_wait=true
        local _ref=New(_editor_class["Yukari"],_editor_class["Yukari"].cards)
        last=_ref
        if _boss_wait then while IsValid(_ref) do task.Wait() end end
        task._Wait(180)
    end)
    ui.lstg_weekly.stage_init(self)
    task.New(self,function()
        while coroutine.status(self.task[1])~='dead' do task.Wait() end
        stage.group.FinishReplay()
        New(mask_fader,'close')
        task.New(self,function()
            local _,bgm=EnumRes('bgm')
            for i=1,30 do
                for _,v in pairs(bgm) do
                    if GetMusicState(v)=='playing' then
                        SetBGMVolume(v,1-i/30)
                    end
                end
                task.Wait()
            end
        end)
        task.Wait(30)
        stage.group.FinishStage()
    end)
end)
