-- Generated by LuaSTG Editor Sharp
-- Mod name: 
_author = "Quein"
_mod_version = 4096
_allow_practice = true
_allow_sc_practice =true
_LoadImageFromFile('image:'..'Quein_Reisen01','Quein_Reisen01.png',true,0,0,false,0)
_LoadImageFromFile('image:'..'quein_bg','quein_bg.png',true,0,0,false,0)
MusicRecord('bgm:'..'Quein - Eientewi set 10~狂気の瞳 (Eientewi set 10~狂气之瞳)','Quein - Eientewi set 10~狂気の瞳 (Eientewi set 10~狂气之瞳).ogg',11802242/44100/4,(11802242-1268608)/44100/4)
_editor_class["quein_obj-1"]=Class(_object)
_editor_class["quein_obj-1"].init=function(self,_x,_y)
    self.x,self.y=_x,_y
    self.img="leaf"
    self.layer=LAYER_ENEMY_BULLET
    self.group=GROUP_ENEMY_BULLET
    self.hide=false
    self.bound=false
    self.navi=false
    self.hp=10
    self.maxhp=10
    self.colli=false
    self._servants={}
    self._blend,self._a,self._r,self._g,self._b='',255,255,255,255
    _object.set_color(self,"",55,200,0,0)
    self.vscale=20
    self.hscale=20
    lasttask=task.New(self,function()
        task._Wait(90)
        _del(self,true)
    end)
end
_editor_class["quein_bullet-1"]=Class(bullet)
_editor_class["quein_bullet-1"].init=function(self,_x,_y,co,v,a,list)
bullet.init(self,gun_bullet,co,true,true)
self.x,self.y=_x,_y
    self.rot=a
    self.vx=v*cos(a)
    self.vy=v*sin(a)
    self.list=list
    lasttask=task.New(self,function()
        for _=1,_infinite do
            if list.x==1 then
                self.vx=1*cos(-140)
                self.vy=1*sin(-140)
                _object.set_color(self,"mul+add",170,170,170,170)
                self.colli=false
            else
                self.rot=a
                self.vx=v*cos(a)
                self.vy=v*sin(a)
                _object.set_color(self,"",255,255,255,255)
                ChangeBulletImage(self,gun_bullet,co)
                self.colli=true
            end
            task._Wait(1)
        end
    end)
end
_editor_class["quein_bullet-2"]=Class(bullet)
_editor_class["quein_bullet-2"].init=function(self,_x,_y,co,v,a,list)
bullet.init(self,gun_bullet,COLOR_CYAN,true,true)
self.x,self.y=_x,_y
    self.rot=a
    self.vx=v*cos(a)
    self.vy=v*sin(a)
    self.list=list
    lasttask=task.New(self,function()
        for _=1,_infinite do
            if list.x==1 then
                self.rot=a
                self.vx=v*cos(a)
                self.vy=v*sin(a)
                _object.set_color(self,"mul+add",180,180,180,180)
                self.colli=false
            else
                self.rot=a
                self.vx=v*cos(a)
                self.vy=v*sin(a)
                _object.set_color(self,"",255,255,255,255)
                ChangeBulletImage(self,gun_bullet,COLOR_CYAN)
                self.colli=true
            end
            task._Wait(1)
        end
    end)
end
_editor_class["quein_laser-1"]=Class(laser)
_editor_class["quein_laser-1"].init=function(self,_x,_y,rot)
    laser.init(self,COLOR_YELLOW,_x,_y,0,0,1000,0,16,0,0)
    
    lasttask=task.New(self,function()
        self.rot=rot
        self.bound=false
        laser._TurnHalfOn(self,30,true)
        task._Wait(45)
        laser._TurnOn(self,5,true,true)
        task._Wait(55)
        laser._TurnOff(self,10,true)
        _del(self,true)
    end)
end
_editor_class["quein_bg"]=Class(_spellcard_background)
_editor_class["quein_bg"].init=function(self)
    _spellcard_background.init(self)
    _spellcard_background.AddLayer(self,"image:quein_bg",false,0,0,0,0,0,0,"",1,1,
        function(self)
            self.task={}
        end,
        function(self)
            task.Do(self)
        end,
        function(self)
        end
    )
end
_editor_class["Boss"]=Class(boss)
_editor_class["Boss"].cards={}
_editor_class["Boss"].name="行走图没画完就被拉来填线的可怜月战老兵"
_editor_class["Boss"].bgm="bgm:Quein - Eientewi set 10~狂気の瞳 (Eientewi set 10~狂气之瞳)"
_editor_class["Boss"]._bg=nil
_editor_class["Boss"].difficulty="All"
_editor_class["Boss"].init=function(self,cards)
boss.init(self,240,384,_editor_class["Boss"].name,cards,New(_editor_class["quein_bg"]),_editor_class["Boss"].difficulty)
    self._wisys = BossWalkImageSystem(self)
    self._wisys:SetImage("Quein_Reisen01.png",2,4,{4,4},{3},6,16,16)
end
--[[ 2
]]
_tmp_sc=boss.card.New("「刀锋弹雨」",2,5,60,1070,{0,0,0},false)
function _tmp_sc:before()
    ui.lstg_weekly.SetFlag(false, true, false)
    ui.lstg_weekly.SetEditor("Quein123")
end
function _tmp_sc:init()
    local list = { x = 0 }
    lasttask=task.New(self,function()
        task.MoveTo(0,120,60,MOVE_NORMAL)
        PlaySound("tan00",0.1,self.x/256,false)
        for _=1,_infinite do
            task.MoveToPlayer(30,-96,96,112,144,16,32,8,16,MOVE_NORMAL,MOVE_X_TOWARDS_PLAYER)
            PlaySound("tan00",0.1,self.x/256,false)
            do local a,_d_a=(ran:Float(0,360)),(5) for _=1,75 do
                last=New(_editor_class["quein_bullet-2"],self.x,self.y,2,1.5,a,list)
            a=a+_d_a end end
            do local a,_d_a=(ran:Float(0,360)),(5) for _=1,75 do
                last=New(_editor_class["quein_bullet-2"],self.x,self.y,2,1.5,a,list)
            a=a+_d_a end end
            task._Wait(20)
            PlaySound("tan00",0.1,self.x/256,false)
            do local a,_d_a=(ran:Float(0,360)),(5) for _=1,75 do
                last=New(_editor_class["quein_bullet-2"],self.x,self.y,2,1.5,a,list)
            a=a+_d_a end end
            task._Wait(20)
            PlaySound("tan00",0.1,self.x/256,false)
            task._Wait(130)
        end
    end)
    lasttask=task.New(self,function()
        task._Wait(150)
        for _=1,_infinite do
            last=New(_editor_class["quein_obj-1"],0,300)
            list.x=1
            PlaySound("slash",0.1,self.x/256,false)
            task._Wait(90)
            list.x=0
            PlaySound("kira00",0.1,self.x/256,false)
            task._Wait(120)
        end
    end)
    lasttask=task.New(self,function()
        task._Wait(60)
        for _=1,_infinite do
            do local y,_d_y=(192),(-80) for _=1,6 do
                last=New(_editor_class["quein_laser-1"],-220,y,0)
                do local a,_d_a=(ran:Float(0,360)),(7) for _=1,75 do
                    last=New(_editor_class["quein_bullet-1"],self.x,self.y,2,1.2,a,list)
                    task._Wait(1)
                a=a+_d_a end end
            y=y+_d_y end end
            do local x,_d_x=(200),(-80) for _=1,6 do
                last=New(_editor_class["quein_laser-1"],x,-250,90)
                do local a,_d_a=(ran:Float(0,360)),(-7) for _=1,75 do
                    last=New(_editor_class["quein_bullet-1"],self.x,self.y,2,1.2,a,list)
                    task._Wait(1)
                a=a+_d_a end end
            x=x+_d_x end end
            task._Wait(1)
        end
    end)
end
function _tmp_sc:beforedel()
end
function _tmp_sc:del()
end
function _tmp_sc:after()
end
_tmp_sc.perform=false
table.insert(_editor_class["Boss"].cards,_tmp_sc)
table.insert(_sc_table,{"Boss","「刀锋弹雨」",_tmp_sc,#_editor_class["Boss"].cards,false})
stage.group.AddStage(__WEEK_ID,'Quein123@'..__WEEK_ID,{lifeleft=7,power=400,faith=50000,bomb=3},true)
stage.group.DefStageFunc('Quein123@'..__WEEK_ID,'init',function(self)
    _init_item(self)
    difficulty=self.group.difficulty
    New(mask_fader,'open')
    if jstg then jstg.CreatePlayers() else New(_G[lstg.var.player_name]) end
    lasttask=task.New(self,function()
        New(temple_background)
        task._Wait(60)
        LoadMusicRecord("bgm:Quein - Eientewi set 10~狂気の瞳 (Eientewi set 10~狂气之瞳)")
        _play_music("bgm:Quein - Eientewi set 10~狂気の瞳 (Eientewi set 10~狂气之瞳)")
        local _boss_wait=true
        local _ref=New(_editor_class["Boss"],_editor_class["Boss"].cards)
        last=_ref
        if _boss_wait then while IsValid(_ref) do task.Wait() end end
        task._Wait(180)
    end)
    ui.lstg_weekly.stage_init(self)
    task.New(self,function()
        while coroutine.status(self.task[1])~='dead' do task.Wait() end
        stage.group.FinishReplay()
        New(mask_fader,'close')
        task.New(self,function()
            local _,bgm=EnumRes('bgm')
            for i=1,30 do
                for _,v in pairs(bgm) do
                    if GetMusicState(v)=='playing' then
                        SetBGMVolume(v,1-i/30)
                    end
                end
                task.Wait()
            end
        end)
        task.Wait(30)
        stage.group.FinishStage()
    end)
end)
