-- Generated by LuaSTG Editor Sharp
-- Mod name: 
_author = "LuaSTG User"
_mod_version = 4096
_allow_practice = true
_allow_sc_practice =true
--[[ PS修改三道题目的内容]]

-- define node named: week_stage
-- define node named: week_designer_and_questions
--[[ 根据次数修改下面两行]]

__WEEK_ID="Weekend Danmaku - 144th"
__WEEK_ID_SHORT="Weekend 144th"
LoadPack("mod\\weekend_UI.zip")
Include("LSTG_Weekend.lua")
ui.lstg_weekly.SetWeekTime(__WEEK_ID_SHORT)
stage.group.New('menu',{},__WEEK_ID,{lifeleft=2,power=400,faith=50000,bomb=2},true,1)
Include'LuaSTG_Weekend_Extension.lua'
local BeforeLoadSubProject, AfterLoadSubProject = BeforeLoadSubProject, AfterLoadSubProject
--[[ 在下面开始按顺序引用其他工程]]

--[[ 各作者工程将stagegroup与stage替换为绿色UFO中的week_stage]]

--[[ 并在符卡开卡前插入week_designer_and_questions，设置成对应作者与题目]]

if BeforeLoadSubProject then BeforeLoadSubProject("杠零") end
Include'144th_weekend_void.lua'
if AfterLoadSubProject then AfterLoadSubProject("杠零") end
if BeforeLoadSubProject then BeforeLoadSubProject("LHX") end
Include'144th_weekend_LHX.lua'
if AfterLoadSubProject then AfterLoadSubProject("LHX") end
if BeforeLoadSubProject then BeforeLoadSubProject("liu_10_mc") end
Include'144th_weekend_liu_10_mc.lua'
if AfterLoadSubProject then AfterLoadSubProject("liu_10_mc") end
if BeforeLoadSubProject then BeforeLoadSubProject("Quein123") end
Include'144th_weekend_Quein123.lua'
if AfterLoadSubProject then AfterLoadSubProject("Quein123") end
if BeforeLoadSubProject then BeforeLoadSubProject("T_Terrence") end
Include'144th_weekend_T_Terrence.lua'
if AfterLoadSubProject then AfterLoadSubProject("T_Terrence") end
if BeforeLoadSubProject then BeforeLoadSubProject("koishi72") end
Include'144th_weekend_koishi72.lua'
if AfterLoadSubProject then AfterLoadSubProject("koishi72") end
if BeforeLoadSubProject then BeforeLoadSubProject("Ronnie") end
Include'144th_weekend_Ronnie.lua'
if AfterLoadSubProject then AfterLoadSubProject("Ronnie") end
if BeforeLoadSubProject then BeforeLoadSubProject("Comet_Fox") end
Include'144th_weekend_Comet_Fox.lua'
if AfterLoadSubProject then AfterLoadSubProject("Comet_Fox") end
if BeforeLoadSubProject then BeforeLoadSubProject("Maths") end
Include'144th_weekend_Maths.lua'
if AfterLoadSubProject then AfterLoadSubProject("Maths") end
